// @generated by lunaris-codegen — do not edit
//
// Phase 8 Plan 08-01 (BIND-GEN-01..03). TypeScript declarations mirroring
// the napi-rs bindings. Regenerate with
// `cargo run -p lunaris-codegen -- --emit ts`.

/** High-level memory-engine handle. Opens a storage backend by URL and drives ingest, recall, forget, and snapshot. */
export class Lunaris {
  /** Production constructor. Routes `url` through the scheme dispatcher to pick a StoragePort backend. */
  static open(url: string): Promise<this>;
  /** Ingest one Episode through the hot path (graph-OFF default) or the graph-extraction path (toggle ON). */
  ingest(episode: Episode): Promise<string>;
  /** Build a RetrievalBuilder bound to this handle's storage / keyword / embedder / clock. */
  recall(): RetrievalBuilder;
  /** Single-entry-point erasure API (OPS-01/02/03/04). Soft-delete default; hard mode requires a confirmation token. */
  forget(req: ForgetRequest): Promise<ForgetReceipt>;
  /** Returns the current monotonic LSN — a cheap consistent snapshot marker. Implemented as no-op atomic_write(&[]). */
  snapshot(): Promise<string>;
}

/** Vector-search DSL operator; root-level constructor for kNN retrieval. */
export class Vector {
  /** Construct a Vector retriever over `index` with top-k fan-out. */
  static new(index: string, k: number): this;
}

/** Keyword / BM25 DSL operator; root-level constructor for lexical retrieval. */
export class Keyword {
  /** Construct a BM25 keyword retriever over `index` with top-k fan-out. */
  static bm25(index: string, k: number): this;
}

/** Graph-traversal DSL operator; anchors on a set of entity ids and expands N hops. */
export class Graph {
  /** Anchor on `entity_ids` and traverse up to `hops` edges out in the Lunaris graph. */
  static anchored(entity_ids: Array<EntityId>, hops: number): this;
}

/** Chainable retrieval plan builder. Terminal .execute() runs the plan through the hydrate stage. */
export class RetrievalBuilder {
  /** Compose `other` in parallel with the current plan; unions the result set. */
  and(other: RetrievalBuilder): this;
  /** Fuse two parallel branches via reciprocal-rank fusion (client-side or Moon-native depending on capabilities). */
  fuse_rrf(k: number): this;
  /** Keep only the top `n` hits after fusion. */
  top(n: number): this;
  /** Attach a filter predicate (parsed via filter_str) to the query; fails on a malformed predicate string. */
  filter(pred: string): this;
  /** Pin the query to an as-of-HLC time-travel view (SQL:2011 bi-temporal read). */
  as_of(hlc: Hlc): this;
}

/** Runtime toggle for the graph-extraction pipeline (default OFF per blueprint §5.2). The toggle method is the canonical single-item entry in the binding surface. */
export class GraphPipelineHandle {
  /** Flip the pipeline ON or OFF. Idempotent. Emits `tracing::info!` only on real state transitions (D-12). */
  toggle(on: boolean): void;
}

/** Runtime toggle for the ACT-R consolidator worker (default OFF per blueprint §5.1). Mirrors GraphPipelineHandle's single-item toggle surface. */
export class ConsolidatorPipelineHandle {
  /** Flip the pipeline ON or OFF. Idempotent. Emits `tracing::info!` only on real state transitions (D-12). */
  toggle(on: boolean): void;
}

/** Conversational wrapper exposing a `remember` / `recall` pair over a per-user `MessageStream + WorkingMemory` pair. */
export class ChatAgentMemory {
  /** Construct a ChatAgentMemory bound to `user_id`. */
  static new(lunaris: Lunaris, user_id: string): this;
  /** Record a single conversational turn. */
  remember(turn: string): Promise<string>;
  /** Recall turns matching `query`. */
  recall(query: string): Promise<Array<Hit>>;
}

/** Cross-session conversational wrapper with a per-user scoped `.consolidate()` cross-session promotion pass. */
export class MultiTurnConversation {
  /** Construct bound to `user_id`. */
  static new(lunaris: Lunaris, user_id: string): this;
  /** Record a turn for `thread_id` (session id). */
  remember(turn: string, thread_id: string): Promise<string>;
  /** Recall turns matching `query` across all sessions. */
  recall(query: string): Promise<Array<Hit>>;
  /** Run one scope-filtered consolidation pass (Phase 9.1 cross-user isolation). */
  consolidate(): Promise<ConsolidationReport>;
}

/** Slack archive wrapper. Holds a root MessageStream scoped at `slack:archive/`. */
export class SlackArchive {
  /** Construct a root archive handle. */
  static new(lunaris: Lunaris): this;
  /** Ingest one message into `channel` authored by `participant_id`. */
  ingest_channel(channel: string, participant_id: string, message: string): Promise<string>;
  /** Recall across the whole archive. */
  recall(query: string): Promise<Array<Hit>>;
  /** Narrow to one channel. Returns a SlackArchiveQuery. */
  channel(id: string): SlackArchiveQuery;
  /** Narrow to one user. Returns a SlackArchiveQuery. */
  user(id: string): SlackArchiveQuery;
}

/** Narrowed query builder returned by SlackArchive::channel / SlackArchive::user. */
export class SlackArchiveQuery {
  /** Add a `user` narrow on top of a `.channel(...)` narrow. */
  with_user(id: string): this;
  /** Execute the narrowed recall. */
  recall(query: string): Promise<Array<Hit>>;
}

/** Thread-scoped email wrapper with an opt-in graph-pipeline builder. */
export class EmailThreading {
  /** Construct a new email-archive handle rooted at `email:thread/`. */
  static new(lunaris: Lunaris): this;
  /** Ingest one email into `root_id`'s thread, authored by `from`. */
  ingest(root_id: string, from: string, body: string): Promise<string>;
  /** Narrow to one thread `root_id`. Returns a new EmailThreading. */
  thread(root_id: string): this;
  /** Recall across the current scope. */
  recall(query: string): Promise<Array<Hit>>;
  /** Opt-in the v0.1.0 graph pipeline (blueprint §5.2 graph-default-off preserved when enable=false). */
  with_graph_pipeline(enable: boolean): this;
}

/** Meeting-notes wrapper with heading-scoped ingest and an opt-in graph-pipeline builder. */
export class MeetingNotesMemory {
  /** Construct bound to `meeting:notes/`. */
  static new(lunaris: Lunaris): this;
  /** Record one note under `heading` (thread_id) with `body` content. */
  note(heading: string, body: string): Promise<string>;
  /** Recall across the meeting corpus. */
  recall(query: string): Promise<Array<Hit>>;
  /** Narrow to notes attributed to `attendees`. Returns a MeetingNotesQuery. */
  attendees(attendees: StrList): MeetingNotesQuery;
  /** Opt-in the v0.1.0 graph pipeline (blueprint §5.2). */
  with_graph_pipeline(enable: boolean): this;
}

/** Narrowed query builder returned by MeetingNotesMemory::attendees. */
export class MeetingNotesQuery {
  /** Execute the narrowed recall (per-attendee Filter::Eq And). */
  recall(query: string): Promise<Array<Hit>>;
}

/** Documentary knowledge-base wrapper. Owns a DocumentCorpus bound to a single `source_prefix`. */
export class DocumentKnowledgeBase {
  /** Construct a knowledge base bound to `source_prefix`. */
  static new(lunaris: Lunaris, source_prefix: string): this;
  /** Ingest chunked `(content, metadata)` pairs. */
  ingest(chunks: DocumentChunks): Promise<void>;
  /** Add an equality filter on a metadata field. */
  filter(field: string, value: JsonValue): this;
  /** Cap output at `k` hits. */
  top(k: number): this;
  /** Execute the fused Vector + Keyword RRF recall. */
  search(query: string): Promise<Array<Hit>>;
}

/** Research-paper corpus wrapper with opt-in citation graph. */
export class ResearchPaperCorpus {
  /** Construct bound to `source_prefix`. */
  static new(lunaris: Lunaris, source_prefix: string): this;
  /** Opt-in the citation graph (blueprint §5.2 graph-default-off). */
  with_graph_pipeline(on: boolean): this;
  /** Ingest chunked `(content, metadata)` pairs. */
  ingest(chunks: DocumentChunks): Promise<void>;
  /** Execute the RRF-fused recall. */
  search(query: string): Promise<Array<Hit>>;
}

/** Code-repository memory wrapper. Stores commit SHA in Episode metadata and recalls point-in-time function bodies. */
export class CodeRepoMemory {
  /** Construct bound to `repo_prefix`. */
  static new(lunaris: Lunaris, repo_prefix: string): this;
  /** Ingest one commit as a batch of `(function_body, metadata)` chunks. */
  ingest_commit(commit_sha: string, committer_date_unix_ms: UnixMs, chunks: DocumentChunks): Promise<void>;
  /** Recall at point-in-time `as_of`. */
  recall(query: string, as_of: Hlc): Promise<Array<Hit>>;
}

/** Timeline-reconstruction wrapper. Two-call composition of DocumentCorpus + TemporalQuery<Documents>. */
export class TimelineReconstruction {
  /** Construct bound to `source_prefix`. */
  static new(lunaris: Lunaris, source_prefix: string): this;
  /** Ingest timeline events as chunked `(content, metadata)` pairs. */
  ingest(events: DocumentChunks): Promise<void>;
  /** Recall all events in `[lo, hi)` — lower-inclusive, upper-exclusive (11-01 boundary semantics). */
  between(query: string, lo: Hlc, hi: Hlc): Promise<Array<Hit>>;
  /** Recall the snapshot at `ts`. */
  as_of(query: string, ts: Hlc): Promise<Array<Hit>>;
}

/** Customer-support history wrapper. Owns both a tickets DocumentCorpus and a chats MessageStream. */
export class CustomerSupportHistory {
  /** Construct with hard-coded source prefixes `ticket:` and `chat:`. */
  static new(lunaris: Lunaris): this;
  /** Opt-in the product/customer relationship graph (blueprint §5.2). */
  with_graph_pipeline(on: boolean): this;
  /** Ingest one ticket body. `ticket_id` is stamped into metadata. */
  ingest_ticket(ticket_id: string, body: string): Promise<void>;
  /** Ingest one chat-turn. `ticket_id/turn_idx` slug lands in the MessageStream thread_id. */
  ingest_chat(ticket_id: string, turn_idx: number, participant: string, msg: string): Promise<string>;
  /** Recall from both buckets; RRF fusion happens within each primitive's own bucket. */
  recall(query: string): Promise<Array<Hit>>;
}

