// @generated by lunaris-codegen — do not edit
//
// Phase 8 Plan 08-01 (BIND-GEN-01..03). PyO3 0.26 wrapper surface emitted
// from `crates/lunaris-codegen/annotations/surface.toml`. Regenerate with
// `cargo run -p lunaris-codegen -- --emit py`.
//
// CLAUDE.md invariant: every `.await` in this file is wrapped in
// `pyo3_async_runtimes::tokio::future_into_py` — the GIL is released across
// every async boundary. The parity-check CI job
// (`.github/workflows/ci.yml::parity-check`) fails the PR on any drift from
// this snapshot.

use pyo3::prelude::*;
use pyo3::types::PyModule;
use std::sync::Arc;

/// High-level memory-engine handle. Opens a storage backend by URL and drives ingest, recall, forget, and snapshot.
#[pyclass(name = "Lunaris", unsendable)]
pub struct PyLunaris {
    #[allow(dead_code)]
    pub(crate) inner: Arc<::lunaris::Lunaris>,
}

#[pymethods]
impl PyLunaris {
    /// Production constructor. Routes `url` through the scheme dispatcher to pick a StoragePort backend.
    #[staticmethod]
    fn open<'py>(py: Python<'py>, url: String) -> PyResult<Bound<'py, PyAny>> {
        pyo3_async_runtimes::tokio::future_into_py(py, async move {
            let inner = ::lunaris::Lunaris::open(&url).await.map_err(py_err)?;
            Ok(PyLunaris { inner: Arc::new(inner) })
        })
    }

    /// Ingest one Episode through the hot path (graph-OFF default) or the graph-extraction path (toggle ON).
    fn ingest<'py>(&self, py: Python<'py>, episode: &Bound<'_, PyAny>) -> PyResult<Bound<'py, PyAny>> {
        let inner = self.inner.clone();
        pyo3_async_runtimes::tokio::future_into_py(py, async move {
            let out = inner.ingest(pythonize::depythonize(&episode)?).await.map_err(py_err)?;
            Python::with_gil(|py| Ok(out.to_string().into_pyobject(py)?.into_any().unbind()))
        })
    }

    /// Build a RetrievalBuilder bound to this handle's storage / keyword / embedder / clock.
    fn recall(&self) -> PyResult<PyRetrievalBuilder> {
        let out = self.inner.recall();
        Ok(Self { inner: Arc::new(out) })
    }

    /// Single-entry-point erasure API (OPS-01/02/03/04). Soft-delete default; hard mode requires a confirmation token.
    fn forget<'py>(&self, py: Python<'py>, req: &Bound<'_, PyAny>) -> PyResult<Bound<'py, PyAny>> {
        let inner = self.inner.clone();
        pyo3_async_runtimes::tokio::future_into_py(py, async move {
            let out = inner.forget(pythonize::depythonize(&req)?).await.map_err(py_err)?;
            Python::with_gil(|py| Ok(pythonize::pythonize(py, &out)?.unbind()))
        })
    }

    /// Returns the current monotonic LSN — a cheap consistent snapshot marker. Implemented as no-op atomic_write(&[]).
    fn snapshot<'py>(&self, py: Python<'py>) -> PyResult<Bound<'py, PyAny>> {
        let inner = self.inner.clone();
        pyo3_async_runtimes::tokio::future_into_py(py, async move {
            let out = inner.snapshot().await.map_err(py_err)?;
            Python::with_gil(|py| Ok(out.to_string().into_pyobject(py)?.into_any().unbind()))
        })
    }

}

/// Vector-search DSL operator; root-level constructor for kNN retrieval.
#[pyclass(name = "Vector", unsendable)]
pub struct PyVector {
    #[allow(dead_code)]
    pub(crate) inner: Arc<::lunaris::Vector>,
}

#[pymethods]
impl PyVector {
    /// Construct a Vector retriever over `index` with top-k fan-out.
    #[staticmethod]
    fn new(index: String, k: usize) -> PyResult<Self> {
        let inner = ::lunaris::Vector::new(&index, k);
        Ok(Self { inner: Arc::new(inner) })
    }

}

/// Keyword / BM25 DSL operator; root-level constructor for lexical retrieval.
#[pyclass(name = "Keyword", unsendable)]
pub struct PyKeyword {
    #[allow(dead_code)]
    pub(crate) inner: Arc<::lunaris::Keyword>,
}

#[pymethods]
impl PyKeyword {
    /// Construct a BM25 keyword retriever over `index` with top-k fan-out.
    #[staticmethod]
    fn bm25(index: String, k: usize) -> PyResult<Self> {
        let inner = ::lunaris::Keyword::bm25(&index, k);
        Ok(Self { inner: Arc::new(inner) })
    }

}

/// Graph-traversal DSL operator; anchors on a set of entity ids and expands N hops.
#[pyclass(name = "Graph", unsendable)]
pub struct PyGraph {
    #[allow(dead_code)]
    pub(crate) inner: Arc<::lunaris::Graph>,
}

#[pymethods]
impl PyGraph {
    /// Anchor on `entity_ids` and traverse up to `hops` edges out in the Lunaris graph.
    #[staticmethod]
    fn anchored(entity_ids: &Bound<'_, PyAny>, hops: usize) -> PyResult<Self> {
        let inner = ::lunaris::Graph::anchored(entity_ids, hops);
        Ok(Self { inner: Arc::new(inner) })
    }

}

/// Chainable retrieval plan builder. Terminal .execute() runs the plan through the hydrate stage.
#[pyclass(name = "RetrievalBuilder", unsendable)]
pub struct PyRetrievalBuilder {
    #[allow(dead_code)]
    pub(crate) inner: Arc<::lunaris::RetrievalBuilder>,
}

#[pymethods]
impl PyRetrievalBuilder {
    /// Compose `other` in parallel with the current plan; unions the result set.
    fn and(slf: PyRefMut<'_, Self>, other: &Bound<'_, PyAny>) -> PyResult<PyRetrievalBuilder> {
        // Builder methods consume self; we clone the inner Arc so Python can keep the prior handle alive.
        let _ = slf; let _ = (other); // wired by Plan 08-02's emitter body; Plan 08-01 snapshot freezes the signature.
        unimplemented!("Plan 08-02 wires the body")
    }

    /// Fuse two parallel branches via reciprocal-rank fusion (client-side or Moon-native depending on capabilities).
    fn fuse_rrf(slf: PyRefMut<'_, Self>, k: usize) -> PyResult<PyRetrievalBuilder> {
        // Builder methods consume self; we clone the inner Arc so Python can keep the prior handle alive.
        let _ = slf; let _ = (k); // wired by Plan 08-02's emitter body; Plan 08-01 snapshot freezes the signature.
        unimplemented!("Plan 08-02 wires the body")
    }

    /// Keep only the top `n` hits after fusion.
    fn top(slf: PyRefMut<'_, Self>, n: usize) -> PyResult<PyRetrievalBuilder> {
        // Builder methods consume self; we clone the inner Arc so Python can keep the prior handle alive.
        let _ = slf; let _ = (n); // wired by Plan 08-02's emitter body; Plan 08-01 snapshot freezes the signature.
        unimplemented!("Plan 08-02 wires the body")
    }

    /// Attach a filter predicate (parsed via filter_str) to the query; fails on a malformed predicate string.
    fn filter(slf: PyRefMut<'_, Self>, pred: String) -> PyResult<PyRetrievalBuilder> {
        // Builder methods consume self; we clone the inner Arc so Python can keep the prior handle alive.
        let _ = slf; let _ = (&pred); // wired by Plan 08-02's emitter body; Plan 08-01 snapshot freezes the signature.
        unimplemented!("Plan 08-02 wires the body")
    }

    /// Pin the query to an as-of-HLC time-travel view (SQL:2011 bi-temporal read).
    fn as_of(slf: PyRefMut<'_, Self>, hlc: &Bound<'_, PyAny>) -> PyResult<PyRetrievalBuilder> {
        // Builder methods consume self; we clone the inner Arc so Python can keep the prior handle alive.
        let _ = slf; let _ = (hlc); // wired by Plan 08-02's emitter body; Plan 08-01 snapshot freezes the signature.
        unimplemented!("Plan 08-02 wires the body")
    }

}

/// Runtime toggle for the graph-extraction pipeline (default OFF per blueprint §5.2). The toggle method is the canonical single-item entry in the binding surface.
#[pyclass(name = "GraphPipelineHandle", unsendable)]
pub struct PyGraphPipelineHandle {
    #[allow(dead_code)]
    pub(crate) inner: Arc<::lunaris::GraphPipelineHandle>,
}

#[pymethods]
impl PyGraphPipelineHandle {
    /// Flip the pipeline ON or OFF. Idempotent. Emits `tracing::info!` only on real state transitions (D-12).
    fn toggle(&self, on: bool) -> PyResult<()> {
        let out = self.inner.toggle(on);
        let _ = out; Ok(())
    }

}

/// Runtime toggle for the ACT-R consolidator worker (default OFF per blueprint §5.1). Mirrors GraphPipelineHandle's single-item toggle surface.
#[pyclass(name = "ConsolidatorPipelineHandle", unsendable)]
pub struct PyConsolidatorPipelineHandle {
    #[allow(dead_code)]
    pub(crate) inner: Arc<::lunaris::ConsolidatorPipelineHandle>,
}

#[pymethods]
impl PyConsolidatorPipelineHandle {
    /// Flip the pipeline ON or OFF. Idempotent. Emits `tracing::info!` only on real state transitions (D-12).
    fn toggle(&self, on: bool) -> PyResult<()> {
        let out = self.inner.toggle(on);
        let _ = out; Ok(())
    }

}

/// Registers every generated `#[pyclass]` on the host crate's `#[pymodule] fn lunaris`.
pub(crate) fn register_generated(_py: Python<'_>, m: &Bound<'_, PyModule>) -> PyResult<()> {
    m.add_class::<PyLunaris>()?;
    m.add_class::<PyVector>()?;
    m.add_class::<PyKeyword>()?;
    m.add_class::<PyGraph>()?;
    m.add_class::<PyRetrievalBuilder>()?;
    m.add_class::<PyGraphPipelineHandle>()?;
    m.add_class::<PyConsolidatorPipelineHandle>()?;
    Ok(())
}
