// @generated by lunaris-codegen — do not edit
//
// Phase 8 Plan 08-01 (BIND-GEN-01..03). TypeScript declarations mirroring
// the napi-rs bindings. Regenerate with
// `cargo run -p lunaris-codegen -- --emit ts`.

/** High-level memory-engine handle. Opens a storage backend by URL and drives ingest, recall, forget, and snapshot. */
export class Lunaris {
  /** Production constructor. Routes `url` through the scheme dispatcher to pick a StoragePort backend. */
  static open(url: string): Promise<this>;
  /** Ingest one Episode through the hot path (graph-OFF default) or the graph-extraction path (toggle ON). */
  ingest(episode: Episode): Promise<string>;
  /** Build a RetrievalBuilder bound to this handle's storage / keyword / embedder / clock. */
  recall(): RetrievalBuilder;
  /** Single-entry-point erasure API (OPS-01/02/03/04). Soft-delete default; hard mode requires a confirmation token. */
  forget(req: ForgetRequest): Promise<ForgetReceipt>;
  /** Returns the current monotonic LSN — a cheap consistent snapshot marker. Implemented as no-op atomic_write(&[]). */
  snapshot(): Promise<string>;
}

/** Vector-search DSL operator; root-level constructor for kNN retrieval. */
export class Vector {
  /** Construct a Vector retriever over `index` with top-k fan-out. */
  static new(index: string, k: number): this;
}

/** Keyword / BM25 DSL operator; root-level constructor for lexical retrieval. */
export class Keyword {
  /** Construct a BM25 keyword retriever over `index` with top-k fan-out. */
  static bm25(index: string, k: number): this;
}

/** Graph-traversal DSL operator; anchors on a set of entity ids and expands N hops. */
export class Graph {
  /** Anchor on `entity_ids` and traverse up to `hops` edges out in the Lunaris graph. */
  static anchored(entity_ids: Array<EntityId>, hops: number): this;
}

/** Chainable retrieval plan builder. Terminal .execute() runs the plan through the hydrate stage. */
export class RetrievalBuilder {
  /** Compose `other` in parallel with the current plan; unions the result set. */
  and(other: RetrievalBuilder): this;
  /** Fuse two parallel branches via reciprocal-rank fusion (client-side or Moon-native depending on capabilities). */
  fuse_rrf(k: number): this;
  /** Keep only the top `n` hits after fusion. */
  top(n: number): this;
  /** Attach a filter predicate (parsed via filter_str) to the query; fails on a malformed predicate string. */
  filter(pred: string): this;
  /** Pin the query to an as-of-HLC time-travel view (SQL:2011 bi-temporal read). */
  as_of(hlc: Hlc): this;
}

/** Runtime toggle for the graph-extraction pipeline (default OFF per blueprint §5.2). The toggle method is the canonical single-item entry in the binding surface. */
export class GraphPipelineHandle {
  /** Flip the pipeline ON or OFF. Idempotent. Emits `tracing::info!` only on real state transitions (D-12). */
  toggle(on: boolean): void;
}

/** Runtime toggle for the ACT-R consolidator worker (default OFF per blueprint §5.1). Mirrors GraphPipelineHandle's single-item toggle surface. */
export class ConsolidatorPipelineHandle {
  /** Flip the pipeline ON or OFF. Idempotent. Emits `tracing::info!` only on real state transitions (D-12). */
  toggle(on: boolean): void;
}

