[package]
name        = "lunaris-storage-postgres"
version     = "0.0.1"
edition.workspace      = true
rust-version.workspace = true
license.workspace      = true
authors.workspace      = true

[dependencies]
lunaris-core   = { path = "../lunaris-core" }
async-trait    = { workspace = true }
bytes          = { workspace = true }
futures        = { workspace = true }
serde          = { workspace = true }
serde_json     = { workspace = true }
thiserror      = { workspace = true }
tokio          = { workspace = true }
tracing        = { workspace = true }
sqlx           = { workspace = true }
parking_lot    = { workspace = true }
url            = { workspace = true }
