//! Numerical-equivalence integration test for `lunaris-rerank-native`.
//!
//! Gated behind the `reranker-it` feature so it doesn't run in the default
//! `cargo test` matrix (the test needs ~1.1 GB of weights downloaded locally —
//! see `scripts/spike-generate-reference-rerank-scores.py`).
//!
//! ## Required env vars
//!
//! The test reads the on-disk path to each model artifact from these env vars.
//! If any is missing, the test is SKIPPED (prints a notice; does not fail the
//! suite) — same convention as `lunaris-embed-native`'s `embedder-it` IT.
//!
//! - `BGE_RERANKER_WEIGHTS_PATH`   — absolute path to `model.safetensors`
//! - `BGE_RERANKER_TOKENIZER_PATH` — absolute path to `tokenizer.json`
//! - `BGE_RERANKER_CONFIG_PATH`    — absolute path to `config.json`
//!
//! ## Drift gate
//!
//! Asserted against the 100-pair reference fixture
//! (`tests/fixtures/reference_scores.json`, generated by
//! `scripts/spike-generate-reference-rerank-scores.py` from HF
//! `sentence-transformers.CrossEncoder("BAAI/bge-reranker-v2-m3")` on CPU
//! fp32, with sigmoid applied to the raw logits before saving):
//!
//! - max absolute score delta ≤ 0.05 per pair
//! - score variance > 0.01 across the 100 pairs (non-vacuity check — catches
//!   the degenerate "constant output" failure mode where every pair scores
//!   the same value, which would pass the drift gate trivially)

#![cfg(feature = "reranker-it")]

use std::path::PathBuf;

use candle_core::Device;
use lunaris_rerank::{RerankCandidate, Reranker};
use lunaris_rerank_native::{NativeReranker, NativeRerankerOpts};
use serde::Deserialize;

#[derive(Debug, Deserialize)]
struct Fixture {
    schema_version: u32,
    model: String,
    activation: String,
    #[serde(default)]
    populated: bool,
    pairs: Vec<FixturePair>,
}

#[derive(Debug, Deserialize)]
struct FixturePair {
    id: String,
    query: String,
    doc: String,
    category: String,
    /// `Option<f64>` because the committed seed fixture ships
    /// `reference_score: null` for every pair; the spike script
    /// (`scripts/spike-generate-reference-rerank-scores.py`) populates real
    /// values before the IT can run. The `populated` flag on the parent
    /// `Fixture` is the canonical signal; this is `Option` so deserialization
    /// of the un-populated seed doesn't fail.
    reference_score: Option<f64>,
}

fn env_path(name: &str) -> Option<PathBuf> {
    std::env::var_os(name).map(PathBuf::from)
}

fn load_fixture() -> Fixture {
    let path = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("tests")
        .join("fixtures")
        .join("reference_scores.json");
    let bytes =
        std::fs::read(&path).unwrap_or_else(|e| panic!("read fixture {}: {e}", path.display()));
    let fx: Fixture = serde_json::from_slice(&bytes).expect("parse fixture json");
    assert_eq!(fx.schema_version, 1, "fixture schema version mismatch");
    assert_eq!(fx.model, "BAAI/bge-reranker-v2-m3", "model id mismatch");
    assert_eq!(
        fx.activation, "sigmoid",
        "reference scores must be sigmoid-bounded to match NativeReranker output"
    );
    assert_eq!(fx.pairs.len(), 100, "panel size must be exactly 100");
    // Category mix invariant: 25 of each.
    let mut counts = std::collections::BTreeMap::<&str, usize>::new();
    for p in &fx.pairs {
        *counts.entry(p.category.as_str()).or_default() += 1;
    }
    for cat in ["en_to_en", "en_to_vi", "en_to_code", "vi_to_vi"] {
        assert_eq!(
            counts.get(cat).copied().unwrap_or(0),
            25,
            "category {cat} must have exactly 25 pairs"
        );
    }
    fx
}

#[tokio::test(flavor = "multi_thread", worker_threads = 2)]
async fn native_reranker_matches_cross_encoder_within_drift_gate() {
    // Skip if any required env var is missing — same convention as the
    // existing lunaris-embed-native embedder-it tests.
    let weights = match env_path("BGE_RERANKER_WEIGHTS_PATH") {
        Some(p) => p,
        None => {
            eprintln!(
                "[skip] BGE_RERANKER_WEIGHTS_PATH unset; download the model with\n  \
                python3 scripts/spike-generate-reference-rerank-scores.py\n  \
                and export the three BGE_RERANKER_*_PATH env vars."
            );
            return;
        }
    };
    let tokenizer = match env_path("BGE_RERANKER_TOKENIZER_PATH") {
        Some(p) => p,
        None => {
            eprintln!("[skip] BGE_RERANKER_TOKENIZER_PATH unset");
            return;
        }
    };
    let config = match env_path("BGE_RERANKER_CONFIG_PATH") {
        Some(p) => p,
        None => {
            eprintln!("[skip] BGE_RERANKER_CONFIG_PATH unset");
            return;
        }
    };

    let fx = load_fixture();
    if !fx.populated {
        eprintln!(
            "[skip] reference fixture is un-populated (seed only). Run\n  \
             python3 scripts/spike-generate-reference-rerank-scores.py\n  \
             to fill in reference_score values, then re-run this test."
        );
        return;
    }
    eprintln!(
        "[it] reference: {} (activation={}, {} pairs)",
        fx.model,
        fx.activation,
        fx.pairs.len()
    );

    let opts = NativeRerankerOpts {
        weights_path: weights,
        tokenizer_path: tokenizer,
        config_path: config,
        device: Device::Cpu,
    };

    let reranker = NativeReranker::open(opts).expect("NativeReranker::open");

    // Score each pair through the public Reranker trait surface, batched at 8
    // to mirror the spike script's reference batch size (so any padding-induced
    // drift behaves identically across the two paths).
    //
    // The Reranker trait API is `rerank(query, docs) -> Vec<RerankCandidate>`
    // sorted by score desc — so we group pairs by query, call rerank, and
    // re-key by candidate id to recover the input order.
    let mut native_scores: Vec<f32> = vec![f32::NAN; fx.pairs.len()];
    use std::collections::HashMap;
    let mut by_query: HashMap<&str, Vec<(usize, &FixturePair)>> = HashMap::new();
    for (idx, p) in fx.pairs.iter().enumerate() {
        by_query.entry(p.query.as_str()).or_default().push((idx, p));
    }

    for (query, group) in &by_query {
        // Build candidates with their fixture index encoded in `id` so we can
        // route the score back after the rerank pass sorts them.
        let docs: Vec<RerankCandidate> = group
            .iter()
            .map(|(idx, p)| RerankCandidate {
                id: (*idx as u64).to_le_bytes().to_vec(),
                text: p.doc.clone(),
                score: 0.0,
                metadata: serde_json::Value::Null,
            })
            .collect();
        let scored = reranker.rerank(query, docs).await.expect("rerank");
        for cand in scored {
            let mut buf = [0u8; 8];
            buf.copy_from_slice(&cand.id);
            let idx = u64::from_le_bytes(buf) as usize;
            native_scores[idx] = cand.score;
        }
    }
    // Sanity: every slot was filled.
    for (i, s) in native_scores.iter().enumerate() {
        assert!(s.is_finite(), "row {i} never received a score (got {s})");
    }

    // Per-pair absolute score delta.
    let mut deltas: Vec<f64> = Vec::with_capacity(fx.pairs.len());
    let mut max_delta = 0.0_f64;
    let mut max_delta_idx = 0usize;
    for (idx, (p, s)) in fx.pairs.iter().zip(native_scores.iter()).enumerate() {
        let ref_score = p.reference_score.unwrap_or_else(|| {
            panic!("fixture pair {idx} ({}) has null reference_score but `populated: true`", p.id)
        });
        let delta = ((*s as f64) - ref_score).abs();
        if delta > max_delta {
            max_delta = delta;
            max_delta_idx = idx;
        }
        deltas.push(delta);
    }
    let mean_delta: f64 = deltas.iter().sum::<f64>() / (deltas.len() as f64);

    // Non-vacuity: the reference scores must themselves span a non-trivial
    // range. If `variance < 0.01` the fixture is degenerate; the gate is
    // meaningless. (We also check the native side has variance > 0 so a
    // pathological model that emits a constant score still fails.)
    let ref_mean: f64 = fx.pairs.iter().map(|p| p.reference_score.expect("populated")).sum::<f64>()
        / (fx.pairs.len() as f64);
    let ref_var: f64 = fx
        .pairs
        .iter()
        .map(|p| (p.reference_score.expect("populated") - ref_mean).powi(2))
        .sum::<f64>()
        / (fx.pairs.len() as f64);
    let nat_mean: f64 =
        native_scores.iter().map(|s| *s as f64).sum::<f64>() / (native_scores.len() as f64);
    let nat_var: f64 = native_scores.iter().map(|s| (*s as f64 - nat_mean).powi(2)).sum::<f64>()
        / (native_scores.len() as f64);

    eprintln!(
        "[it] score delta — mean = {:.6}, max = {:.6} (pair #{}: id={:?}, category={:?})",
        mean_delta,
        max_delta,
        max_delta_idx,
        fx.pairs[max_delta_idx].id,
        fx.pairs[max_delta_idx].category
    );
    eprintln!("[it] reference variance = {ref_var:.6}; native variance = {nat_var:.6}");
    eprintln!(
        "[it] sample — native[0] = {:.6}, ref[0] = {:.6} (id={:?})",
        native_scores[0],
        fx.pairs[0].reference_score.unwrap_or(f64::NAN),
        fx.pairs[0].id
    );

    assert!(
        ref_var > 0.01,
        "reference variance {ref_var:.6} is too low — fixture is degenerate; \
         the drift gate would be vacuous"
    );
    assert!(
        nat_var > 0.01,
        "native variance {nat_var:.6} is too low — model is producing near-constant \
         scores; the drift gate is vacuous"
    );

    assert!(
        max_delta <= 0.05,
        "max score delta {max_delta:.6} exceeds 0.05 gate \
         (worst pair #{max_delta_idx}, id={:?}, category={:?})",
        fx.pairs[max_delta_idx].id,
        fx.pairs[max_delta_idx].category
    );
}
