/* auto-generated by NAPI-RS */
/* eslint-disable */
/** Conversational wrapper exposing a `remember` / `recall` pair over a per-user `MessageStream + WorkingMemory` pair. */
export declare class ChatAgentMemory {
  /** Construct a ChatAgentMemory bound to `user_id`. */
  static new(lunaris: Lunaris, userId: string): ChatAgentMemory
  /** Record a single conversational turn. */
  remember(turn: string): Promise<string>
  /** Recall turns matching `query`. */
  recall(query: string): Promise<Array<any>>
}

/** Code-repository memory wrapper. Stores commit SHA in Episode metadata and recalls point-in-time function bodies. */
export declare class CodeRepoMemory {
  /** Construct bound to `repo_prefix`. */
  static new(lunaris: Lunaris, repoPrefix: string): CodeRepoMemory
  /** Ingest one commit as a batch of `(function_body, metadata)` chunks. */
  ingestCommit(commitSha: string, committerDateUnixMs: any, chunks: any): Promise<void>
  /** Recall at point-in-time `as_of`. */
  recall(query: string, asOf: any): Promise<Array<any>>
}

/** Runtime toggle for the ACT-R consolidator worker (default OFF per blueprint §5.1). Mirrors GraphPipelineHandle's single-item toggle surface. */
export declare class ConsolidatorPipelineHandle {
  /** Flip the pipeline ON or OFF. Idempotent. Emits `tracing::info!` only on real state transitions (D-12). */
  toggle(on: boolean): void
}

/** Customer-support history wrapper. Owns both a tickets DocumentCorpus and a chats MessageStream. */
export declare class CustomerSupportHistory {
  /** Construct with hard-coded source prefixes `ticket:` and `chat:`. */
  static new(lunaris: Lunaris): CustomerSupportHistory
  /** Opt-in the product/customer relationship graph (blueprint §5.2). */
  withGraphPipeline(on: boolean): CustomerSupportHistory
  /** Ingest one ticket body. `ticket_id` is stamped into metadata. */
  ingestTicket(ticketId: string, body: string): Promise<void>
  /** Ingest one chat-turn. `ticket_id/turn_idx` slug lands in the MessageStream thread_id. */
  ingestChat(ticketId: string, turnIdx: number, participant: string, msg: string): Promise<string>
  /** Recall from both buckets; RRF fusion happens within each primitive's own bucket. */
  recall(query: string): Promise<Array<any>>
}

/** Documentary knowledge-base wrapper. Owns a DocumentCorpus bound to a single `source_prefix`. */
export declare class DocumentKnowledgeBase {
  /** Construct a knowledge base bound to `source_prefix`. */
  static new(lunaris: Lunaris, sourcePrefix: string): DocumentKnowledgeBase
  /** Ingest chunked `(content, metadata)` pairs. */
  ingest(chunks: any): Promise<void>
  /** Add an equality filter on a metadata field. */
  filter(field: string, value: any): DocumentKnowledgeBase
  /** Cap output at `k` hits. */
  top(k: number): DocumentKnowledgeBase
  /** Execute the fused Vector + Keyword RRF recall. */
  search(query: string): Promise<Array<any>>
}

/** Thread-scoped email wrapper with an opt-in graph-pipeline builder. */
export declare class EmailThreading {
  /** Construct a new email-archive handle rooted at `email:thread/`. */
  static new(lunaris: Lunaris): EmailThreading
  /** Ingest one email into `root_id`'s thread, authored by `from`. */
  ingest(rootId: string, from: string, body: string): Promise<string>
  /** Narrow to one thread `root_id`. Returns a new EmailThreading. */
  thread(rootId: string): EmailThreading
  /** Recall across the current scope. */
  recall(query: string): Promise<Array<any>>
  /** Opt-in the v0.1.0 graph pipeline (blueprint §5.2 graph-default-off preserved when enable=false). */
  withGraphPipeline(enable: boolean): EmailThreading
}

/**
 * Opaque container around a resolved [`lunaris_core::Embedder`]. Constructed
 * via one of the `#[napi(factory)]` methods; consumed by
 * `crate::Lunaris::withEmbedder`.
 */
export declare class EmbedderConfig {
  /**
   * Zero-vector embedder — metadata-only ingest / BYO vector / unit-test
   * path. Default dim matches granite-r2 (768).
   */
  static noop(dim?: number | undefined | null): EmbedderConfig
  /**
   * llama.cpp `LlamaCppEmbedder` backed by the granite-r2 Q4_K_M GGUF
   * (768-d).
   *
   * `ggufPath` defaults to the staged artifact
   * `~/.lunaris/models/granite-embedding-311m-multilingual-r2.Q4_K_M.gguf`.
   */
  static llamacpp(opts?: LlamaCppConfigOpts | undefined | null): EmbedderConfig
  /**
   * Stub raising `InvalidArg` when the cdylib was built without the
   * `llamacpp` feature (Tier-0 build).
   */
  static llamacpp(opts?: LlamaCppConfigOpts | undefined | null): EmbedderConfig
  /**
   * RETIRED (llama.cpp-only cutover): the candle `NativeEmbedder` was
   * deleted. Use `EmbedderConfig.llamacpp()` instead.
   */
  static native(opts?: NativeConfigOpts | undefined | null): EmbedderConfig
  /**
   * RETIRED (llama.cpp-only cutover): the candle quantized embedder was
   * deleted. Use `EmbedderConfig.llamacpp()` instead.
   */
  static nativeQuantized(opts: NativeQuantizedConfigOpts): EmbedderConfig
  /**
   * Output dimensionality declared by the operator at config time.
   * For the llamacpp path this is granite-r2's 768.
   */
  get declaredDim(): number
}

/**
 * Scope-less payload builder for an `Episode`.
 *
 * Assemble all Episode fields **except** scope using this builder. The scope
 * is injected exactly once by `ScopedLunaris.ingest`. This makes it
 * impossible to construct an Episode with an arbitrary scope by bypassing
 * the `ScopedLunaris` wrapper.
 *
 * ```ts
 * import { EpisodeBuilder, Scope } from 'lunaris';
 *
 * const builder = new EpisodeBuilder("agent:fs/report.md", "# Q3 Report")
 *   .tRef("2026-01-01T00:00:00Z")
 *   .metadata({ author: "helios" });
 *
 * const lsn = await engine.scoped(Scope.new("acme:agent-1")).ingest(builder);
 * ```
 */
export declare class EpisodeBuilder {
  /**
   * Construct a builder with the required `source` and `content`.
   *
   * `source` is the namespace-qualified origin (e.g. `"helios:fs/report.md"`).
   * `content` is the raw text that will be chunked + embedded.
   */
  constructor(source: string, content: string)
  /**
   * Set the reference timestamp (valid time anchor).
   *
   * Accepts an ISO-8601 string (e.g. `"2026-01-01T00:00:00Z"`). When not
   * set the ingest pipeline uses the current wall time from the HlcClock.
   *
   * Returns a new `EpisodeBuilder` (builder pattern).
   */
  tRef(t: string): EpisodeBuilder
  /**
   * Merge metadata key/value pairs into the builder.
   *
   * `m` must be a JSON object. Values must be JSON-serialisable.
   *
   * Returns a new `EpisodeBuilder` (builder pattern).
   */
  metadata(m: any): EpisodeBuilder
}

/** Graph-traversal DSL operator; anchors on a set of entity ids and expands N hops. */
export declare class Graph {
  /** Anchor on `entity_ids` and traverse up to `hops` edges out in the Lunaris graph. */
  static anchored(entityIds: Array<any>, hops: number): Graph
}

/** Runtime toggle for the graph-extraction pipeline (default OFF per blueprint §5.2). The toggle method is the canonical single-item entry in the binding surface. */
export declare class GraphPipelineHandle {
  /** Flip the pipeline ON or OFF. Idempotent. Emits `tracing::info!` only on real state transitions (D-12). */
  toggle(on: boolean): void
}

/** Keyword / BM25 DSL operator; root-level constructor for lexical retrieval. */
export declare class Keyword {
  /** Construct a BM25 keyword retriever over `index` with top-k fan-out. */
  static bm25(index: string, k: number): Keyword
}

/** High-level memory-engine handle. Opens a storage backend by URL and drives ingest, recall, forget, and snapshot. */
export declare class Lunaris {
  /**
   * Plan 21-02 — swap the embedder on this handle and return a new
   * `Lunaris` carrying the override. The original handle is unaffected
   * (its `Arc` keeps pointing at the unwrapped inner).
   */
  withEmbedder(embedder: EmbedderConfig): Lunaris
  /**
   * Plan 21-02 — swap the reranker on this handle and return a new
   * `Lunaris` carrying the override. Symmetric to [`Self::with_embedder`].
   */
  withReranker(reranker: RerankerConfig): Lunaris
  /** Production constructor. Routes `url` through the scheme dispatcher to pick a StoragePort backend. */
  static open(url: string): Promise<Lunaris>
  /** Ingest one Episode through the hot path (graph-OFF default) or the graph-extraction path (toggle ON). */
  ingest(episode: any): Promise<string>
  /** Build a RetrievalBuilder bound to this handle's storage / keyword / embedder / clock. */
  recall(): RetrievalBuilder
  /** Single-entry-point erasure API (OPS-01/02/03/04). Soft-delete default; hard mode requires a confirmation token. */
  forget(req: any): Promise<any>
  /** Returns the current monotonic LSN — a cheap consistent snapshot marker. Implemented as no-op atomic_write(&[]). */
  snapshot(): Promise<string>
}

/** Meeting-notes wrapper with heading-scoped ingest and an opt-in graph-pipeline builder. */
export declare class MeetingNotesMemory {
  /** Construct bound to `meeting:notes/`. */
  static new(lunaris: Lunaris): MeetingNotesMemory
  /** Record one note under `heading` (thread_id) with `body` content. */
  note(heading: string, body: string): Promise<string>
  /** Recall across the meeting corpus. */
  recall(query: string): Promise<Array<any>>
  /** Narrow to notes attributed to `attendees`. Returns a MeetingNotesQuery. */
  attendees(attendees: any): MeetingNotesQuery
  /** Opt-in the v0.1.0 graph pipeline (blueprint §5.2). */
  withGraphPipeline(enable: boolean): MeetingNotesMemory
}

/** Narrowed query builder returned by MeetingNotesMemory::attendees. */
export declare class MeetingNotesQuery {
  /** Execute the narrowed recall (per-attendee Filter::Eq And). */
  recall(query: string): Promise<Array<any>>
}

/** Cross-session conversational wrapper with a per-user scoped `.consolidate()` cross-session promotion pass. */
export declare class MultiTurnConversation {
  /** Construct bound to `user_id`. */
  static new(lunaris: Lunaris, userId: string): MultiTurnConversation
  /** Record a turn for `thread_id` (session id). */
  remember(turn: string, threadId: string): Promise<string>
  /** Recall turns matching `query` across all sessions. */
  recall(query: string): Promise<Array<any>>
  /** Run one scope-filtered consolidation pass (Phase 9.1 cross-user isolation). */
  consolidate(): Promise<any>
}

/**
 * Opaque container around a resolved [`lunaris_rerank::Reranker`]. Constructed
 * via the `#[napi(factory)]` methods; consumed by
 * `crate::Lunaris::withReranker`.
 */
export declare class RerankerConfig {
  /**
   * llama.cpp `LlamaCppReranker` backed by the bge-reranker-v2-m3 Q5_K_M
   * GGUF (cross-encoder, sigmoid scores ∈ [0, 1]).
   *
   * `ggufPath` defaults to the staged artifact
   * `~/.lunaris/models/bge-reranker-v2-m3.Q5_K_M.gguf`. Loads eagerly and
   * raises on a missing/corrupt artifact (explicit construction = fail
   * fast; the umbrella's default resolution defers the load instead).
   */
  static llamacpp(opts?: LlamaCppRerankerConfigOpts | undefined | null): RerankerConfig
  /**
   * Stub raising `InvalidArg` when the cdylib was built without the
   * `llamacpp` feature (Tier-0 build).
   */
  static llamacpp(opts?: LlamaCppRerankerConfigOpts | undefined | null): RerankerConfig
  /**
   * RETIRED (llama.cpp-only cutover): the candle `NativeReranker` was
   * deleted. Use `RerankerConfig.llamacpp()` instead.
   */
  static native(opts?: NativeRerankerConfigOpts | undefined | null): RerankerConfig
  /**
   * RETIRED (llama.cpp-only cutover): the candle quantized reranker was
   * deleted. Use `RerankerConfig.llamacpp()` instead.
   */
  static nativeQuantized(opts: NativeQuantizedRerankerConfigOpts): RerankerConfig
  /** RETRIEVE-06 fallback — passes candidates through with original scores. */
  static noop(): RerankerConfig
}

/** Research-paper corpus wrapper with opt-in citation graph. */
export declare class ResearchPaperCorpus {
  /** Construct bound to `source_prefix`. */
  static new(lunaris: Lunaris, sourcePrefix: string): ResearchPaperCorpus
  /** Opt-in the citation graph (blueprint §5.2 graph-default-off). */
  withGraphPipeline(on: boolean): ResearchPaperCorpus
  /** Ingest chunked `(content, metadata)` pairs. */
  ingest(chunks: any): Promise<void>
  /** Execute the RRF-fused recall. */
  search(query: string): Promise<Array<any>>
}

/** Chainable retrieval plan builder. Terminal .execute() runs the plan through the hydrate stage. */
export declare class RetrievalBuilder {
  /** Compose `other` in parallel with the current plan; unions the result set. */
  and(other: any): RetrievalBuilder
  /** Fuse two parallel branches via reciprocal-rank fusion (client-side or Moon-native depending on capabilities). */
  fuseRrf(k: number): RetrievalBuilder
  /** Keep only the top `n` hits after fusion. */
  top(n: number): RetrievalBuilder
  /** Attach a filter predicate (parsed via filter_str) to the query; fails on a malformed predicate string. */
  filter(pred: string): RetrievalBuilder
  /** Pin the query to an as-of-HLC time-travel view (SQL:2011 bi-temporal read). */
  asOf(hlc: any): RetrievalBuilder
}

/**
 * Multi-agent / multi-tenant partition key (RFC 0001).
 *
 * Validates against `^[A-Za-z0-9_\\-:.]{1,128}$`. Throws on construction if
 * the string is empty, > 128 chars, or contains a character outside the
 * allowed set.
 *
 * ```ts
 * import { Scope } from 'lunaris';
 *
 * const s = Scope.new("acme:agent-42");   // OK
 * Scope.new("");                           // throws
 * Scope.new("a".repeat(129));             // throws
 * ```
 */
export declare class Scope {
  /**
   * Construct a `Scope` from `s`.
   *
   * Validates `^[A-Za-z0-9_\\-:.]{1,128}$`. Throws `Error` if the string
   * is empty, longer than 128 bytes, or contains an invalid character.
   */
  static new(s: string): Scope
  /** Return the scope as a plain string. */
  asStr(): string
  /** Return the scope as a plain string (alias for ergonomic `.toString()` TS usage). */
  toString(): string
}

/**
 * Scope-bound view over a `Lunaris` handle.
 *
 * Constructed via `engine.scoped(scope)`. All operations issued through this
 * wrapper carry the bound scope as their partitioning key.
 *
 * ```ts
 * import { Scope, EpisodeBuilder } from 'lunaris';
 *
 * const scoped = engine.scoped(Scope.new("acme:agent-1"));
 * const lsn = await scoped.ingest(new EpisodeBuilder("src", "content"));
 * const hits = await scoped.recall("brown fox");
 * ```
 *
 * ## Lifetime note
 *
 * The TS-side wrapper owns `Arc<Lunaris>` so it is safe to use from async
 * contexts. On each method call the Rust side re-derives `ScopedLunaris<'_>`
 * via `inner.scoped(scope.clone())` — the borrow is local to the async block.
 */
export declare class ScopedLunaris {
  /** Returns the scope this view is bound to. */
  get scope(): Scope
  /**
   * Ingest an episode payload under the bound scope.
   *
   * `builder` must be an `EpisodeBuilder`. The scope is stamped onto the
   * episode by this method — callers cannot inject an arbitrary scope.
   *
   * Returns the string-formatted Lsn (e.g. `"1746000000000:1"`).
   */
  ingest(builder: EpisodeBuilder): Promise<string>
  /**
   * Recall hits under the bound scope using a text query string.
   *
   * Returns a JSON array of hit objects. The scope is threaded through the
   * entire retrieval path — only hits from this scope's partition are
   * returned.
   */
  recall(query: string): Promise<any>
  /**
   * Return a `RetrievalBuilder` pre-seeded with this scope.
   *
   * Equivalent to `engine.recall().withScope(scope)` for DSL-style
   * query composition.
   */
  dsl(): RetrievalBuilder
}

/** Slack archive wrapper. Holds a root MessageStream scoped at `slack:archive/`. */
export declare class SlackArchive {
  /** Construct a root archive handle. */
  static new(lunaris: Lunaris): SlackArchive
  /** Ingest one message into `channel` authored by `participant_id`. */
  ingestChannel(channel: string, participantId: string, message: string): Promise<string>
  /** Recall across the whole archive. */
  recall(query: string): Promise<Array<any>>
  /** Narrow to one channel. Returns a SlackArchiveQuery. */
  channel(id: string): SlackArchiveQuery
  /** Narrow to one user. Returns a SlackArchiveQuery. */
  user(id: string): SlackArchiveQuery
}

/** Narrowed query builder returned by SlackArchive::channel / SlackArchive::user. */
export declare class SlackArchiveQuery {
  /** Add a `user` narrow on top of a `.channel(...)` narrow. */
  withUser(id: string): SlackArchiveQuery
  /** Execute the narrowed recall. */
  recall(query: string): Promise<Array<any>>
}

/** Timeline-reconstruction wrapper. Two-call composition of DocumentCorpus + `TemporalQuery<Documents>`. */
export declare class TimelineReconstruction {
  /** Construct bound to `source_prefix`. */
  static new(lunaris: Lunaris, sourcePrefix: string): TimelineReconstruction
  /** Ingest timeline events as chunked `(content, metadata)` pairs. */
  ingest(events: any): Promise<void>
  /** Recall all events in `[lo, hi)` — lower-inclusive, upper-exclusive (11-01 boundary semantics). */
  between(query: string, lo: any, hi: any): Promise<Array<any>>
  /** Recall the snapshot at `ts`. */
  asOf(query: string, ts: any): Promise<Array<any>>
}

/** Vector-search DSL operator; root-level constructor for kNN retrieval. */
export declare class Vector {
  /** Construct a Vector retriever over `index` with top-k fan-out. */
  static new(index: string, k: number): Vector
}

export declare function consolidatorPipelineDisable(handle: ConsolidatorPipelineHandle): void

export declare function consolidatorPipelineEnable(handle: ConsolidatorPipelineHandle): void

export declare function consolidatorPipelineIsEnabled(handle: ConsolidatorPipelineHandle): boolean

/**
 * Pure decision helper mirroring the Rust-side initial-state-from-env
 * readers but for a JS config object. Takes an opaque object of shape
 * `{ graphPipeline: { enabled: bool }, consolidatorPipeline: { enabled: bool } }`
 * and returns `[graphEnabled, consolidatorEnabled]`. Missing keys default
 * to `false` (default OFF per blueprint §5.1/§5.2).
 *
 * Accepts both camelCase (`graphPipeline`) and snake_case
 * (`graph_pipeline`) keys — TS-side convention is camelCase but the
 * Python-side config dict uses snake_case and some callers share the
 * same config file across both bindings.
 */
export declare function fromConfig(config: any): Array<boolean>

/**
 * Read the Rust-side env initial-state reader. Exposed so tests can
 * assert that the env surface is wired through to the underlying
 * handle reader without having to construct a real `Lunaris` handle.
 * Returns `[graph_enabled, consolidator_enabled]` — napi-rs 3.x maps
 * `(bool, bool)` to a 2-element TS array.
 *
 * NOTE: this reads `std::env::var(...)` on the Rust side, which bypasses
 * vitest's `process.env` Proxy layer — vitest-managed env mutations in
 * JS-land are NOT visible to `std::env::var` in the Rust side during
 * the same worker. Tests that want to exercise the env-parsing rules
 * should call [`from_env_value`] below with an explicit `Option<String>`.
 */
export declare function fromEnv(): Array<boolean>

/**
 * Pure env-value decoder — mirrors Rust's
 * `GraphPipelineHandle::initial_state_from_value(Option<&str>)`. Tests
 * use this to assert the env-parsing rules without mutating the process
 * env (which vitest's `process.env` Proxy doesn't propagate to
 * `std::env::var` on the Rust side).
 *
 * Accepts the RAW env-variable value (e.g. "1", "true", "on" → true;
 * anything else / null → false). Returns `[graph_enabled, consolidator_enabled]`
 * where both use the same parse rule.
 */
export declare function fromEnvValue(graphVal?: string | undefined | null, consolidatorVal?: string | undefined | null): Array<boolean>

/** Return a `ConsolidatorPipelineHandle` wrapping the inner Rust handle. */
export declare function getConsolidatorPipeline(handle: Lunaris): ConsolidatorPipelineHandle

/**
 * Return a `GraphPipelineHandle` wrapping the inner Rust handle.
 * TS callers reach this via `handle.graphPipeline` through the
 * `index.mts` getter installed on the class prototype.
 */
export declare function getGraphPipeline(handle: Lunaris): GraphPipelineHandle

export declare function graphPipelineDisable(handle: GraphPipelineHandle): void

export declare function graphPipelineEnable(handle: GraphPipelineHandle): void

export declare function graphPipelineIsEnabled(handle: GraphPipelineHandle): boolean

export interface LlamaCppConfigOpts {
  /**
   * Path to the GGUF artifact. Default:
   * `~/.lunaris/models/granite-embedding-311m-multilingual-r2.Q4_K_M.gguf`.
   */
  ggufPath?: string
}

export interface LlamaCppRerankerConfigOpts {
  /**
   * Path to the GGUF artifact. Default:
   * `~/.lunaris/models/bge-reranker-v2-m3.Q5_K_M.gguf`.
   */
  ggufPath?: string
}

/**
 * Construct a `ScopedLunaris` bound to `scope`.
 *
 * Exposed as a free function because napi-rs 3.x does not support adding
 * methods to a struct from outside its definition block. The TS-side
 * `index.mts` wrapper patches this as `Lunaris.prototype.scoped` so
 * callers can write `engine.scoped(scope)` naturally.
 *
 * napi-rs exposes this as `lunarisScoped(handle, scope): ScopedLunaris`.
 */
export declare function lunarisScoped(handle: Lunaris, scope: Scope): ScopedLunaris

export interface NativeConfigOpts {
  /**
   * RETIRED — kept so existing callers get the migration error, not a
   * TypeScript signature break.
   */
  modelDir?: string
}

export interface NativeQuantizedConfigOpts {
  /** RETIRED — see `EmbedderConfig.llamacpp()`. */
  ggufPath: string
  /** RETIRED — see `EmbedderConfig.llamacpp()`. */
  modelDir?: string
}

export interface NativeQuantizedRerankerConfigOpts {
  /** RETIRED — see `RerankerConfig.llamacpp()`. */
  ggufPath: string
  /** RETIRED — see `RerankerConfig.llamacpp()`. */
  modelDir?: string
}

export interface NativeRerankerConfigOpts {
  /**
   * RETIRED — kept so existing callers get the migration error, not a
   * TypeScript signature break.
   */
  modelDir?: string
}

/**
 * Ergonomic async `open` free function so TypeScript callers can write
 * `await open(url)` without importing the `Lunaris` class directly —
 * matches Plan 08-02's `lunaris.open(url)` surface.
 *
 * napi-rs 3.x exposes this as `openHandle(url: string): Promise<Lunaris>`
 * at the TS layer. The handwritten `index.mts` wrapper re-exports it as
 * `open(url, opts?)` with the three-surface config path.
 */
export declare function openHandle(url: string): Promise<Lunaris>

/**
 * Minimal `recall` execute bridge for the TS-side DSL.
 *
 * Accepts a plan JSON of shape:
 * `{"query": "...", "k": 5, "index": "chunks", "filter": "...", "as_of_ms": 123}`.
 * All keys are optional. `root` is the operator tree documented on
 * `lunaris_retrieve::plan`; when it is absent the flat pre-F14 fields
 * (`index`, `k`) are read instead and normalized into the equivalent
 * one-leg `vector` tree. Missing fields fall back to
 * `{query: "", k: 5, index: "chunks"}`. Returns a JSON array of hit
 * objects which napi-rs 3.x converts to a `Promise<Array<object>>` in TS.
 */
export declare function recallSimpleExecute(handle: Lunaris, plan: any): Promise<any>
