/* auto-generated by NAPI-RS */
/* eslint-disable */
/** Runtime toggle for the ACT-R consolidator worker (default OFF per blueprint §5.1). Mirrors GraphPipelineHandle's single-item toggle surface. */
export declare class ConsolidatorPipelineHandle {
  /** Flip the pipeline ON or OFF. Idempotent. Emits `tracing::info!` only on real state transitions (D-12). */
  toggle(on: boolean): void
}

/** Graph-traversal DSL operator; anchors on a set of entity ids and expands N hops. */
export declare class Graph {
  /** Anchor on `entity_ids` and traverse up to `hops` edges out in the Lunaris graph. */
  static anchored(entityIds: Array<any>, hops: number): Graph
}

/** Runtime toggle for the graph-extraction pipeline (default OFF per blueprint §5.2). The toggle method is the canonical single-item entry in the binding surface. */
export declare class GraphPipelineHandle {
  /** Flip the pipeline ON or OFF. Idempotent. Emits `tracing::info!` only on real state transitions (D-12). */
  toggle(on: boolean): void
}

/** Keyword / BM25 DSL operator; root-level constructor for lexical retrieval. */
export declare class Keyword {
  /** Construct a BM25 keyword retriever over `index` with top-k fan-out. */
  static bm25(index: string, k: number): Keyword
}

/** High-level memory-engine handle. Opens a storage backend by URL and drives ingest, recall, forget, and snapshot. */
export declare class Lunaris {
  /** Production constructor. Routes `url` through the scheme dispatcher to pick a StoragePort backend. */
  static open(url: string): Promise<Lunaris>
  /** Ingest one Episode through the hot path (graph-OFF default) or the graph-extraction path (toggle ON). */
  ingest(episode: any): Promise<string>
  /** Build a RetrievalBuilder bound to this handle's storage / keyword / embedder / clock. */
  recall(): RetrievalBuilder
  /** Single-entry-point erasure API (OPS-01/02/03/04). Soft-delete default; hard mode requires a confirmation token. */
  forget(req: any): Promise<any>
  /** Returns the current monotonic LSN — a cheap consistent snapshot marker. Implemented as no-op atomic_write(&[]). */
  snapshot(): Promise<string>
}

/** Chainable retrieval plan builder. Terminal .execute() runs the plan through the hydrate stage. */
export declare class RetrievalBuilder {
  /** Compose `other` in parallel with the current plan; unions the result set. */
  and(other: any): RetrievalBuilder
  /** Fuse two parallel branches via reciprocal-rank fusion (client-side or Moon-native depending on capabilities). */
  fuseRrf(k: number): RetrievalBuilder
  /** Keep only the top `n` hits after fusion. */
  top(n: number): RetrievalBuilder
  /** Attach a filter predicate (parsed via filter_str) to the query; fails on a malformed predicate string. */
  filter(pred: string): RetrievalBuilder
  /** Pin the query to an as-of-HLC time-travel view (SQL:2011 bi-temporal read). */
  asOf(hlc: any): RetrievalBuilder
}

/** Vector-search DSL operator; root-level constructor for kNN retrieval. */
export declare class Vector {
  /** Construct a Vector retriever over `index` with top-k fan-out. */
  static new(index: string, k: number): Vector
}

export declare function consolidatorPipelineDisable(handle: ConsolidatorPipelineHandle): void

export declare function consolidatorPipelineEnable(handle: ConsolidatorPipelineHandle): void

export declare function consolidatorPipelineIsEnabled(handle: ConsolidatorPipelineHandle): boolean

/**
 * Pure decision helper mirroring the Rust-side initial-state-from-env
 * readers but for a JS config object. Takes an opaque object of shape
 * `{ graphPipeline: { enabled: bool }, consolidatorPipeline: { enabled: bool } }`
 * and returns `[graphEnabled, consolidatorEnabled]`. Missing keys default
 * to `false` (default OFF per blueprint §5.1/§5.2).
 *
 * Accepts both camelCase (`graphPipeline`) and snake_case
 * (`graph_pipeline`) keys — TS-side convention is camelCase but the
 * Python-side config dict uses snake_case and some callers share the
 * same config file across both bindings.
 */
export declare function fromConfig(config: any): Array<boolean>

/**
 * Read the Rust-side env initial-state reader. Exposed so tests can
 * assert that the env surface is wired through to the underlying
 * handle reader without having to construct a real `Lunaris` handle.
 * Returns `[graph_enabled, consolidator_enabled]` — napi-rs 3.x maps
 * `(bool, bool)` to a 2-element TS array.
 *
 * NOTE: this reads `std::env::var(...)` on the Rust side, which bypasses
 * vitest's `process.env` Proxy layer — vitest-managed env mutations in
 * JS-land are NOT visible to `std::env::var` in the Rust side during
 * the same worker. Tests that want to exercise the env-parsing rules
 * should call [`from_env_value`] below with an explicit `Option<String>`.
 */
export declare function fromEnv(): Array<boolean>

/**
 * Pure env-value decoder — mirrors Rust's
 * `GraphPipelineHandle::initial_state_from_value(Option<&str>)`. Tests
 * use this to assert the env-parsing rules without mutating the process
 * env (which vitest's `process.env` Proxy doesn't propagate to
 * `std::env::var` on the Rust side).
 *
 * Accepts the RAW env-variable value (e.g. "1", "true", "on" → true;
 * anything else / null → false). Returns `[graph_enabled, consolidator_enabled]`
 * where both use the same parse rule.
 */
export declare function fromEnvValue(graphVal?: string | undefined | null, consolidatorVal?: string | undefined | null): Array<boolean>

/** Return a `ConsolidatorPipelineHandle` wrapping the inner Rust handle. */
export declare function getConsolidatorPipeline(handle: Lunaris): ConsolidatorPipelineHandle

/**
 * Return a `GraphPipelineHandle` wrapping the inner Rust handle.
 * TS callers reach this via `handle.graphPipeline` through the
 * `index.mts` getter installed on the class prototype.
 */
export declare function getGraphPipeline(handle: Lunaris): GraphPipelineHandle

export declare function graphPipelineDisable(handle: GraphPipelineHandle): void

export declare function graphPipelineEnable(handle: GraphPipelineHandle): void

export declare function graphPipelineIsEnabled(handle: GraphPipelineHandle): boolean

/**
 * Ergonomic async `open` free function so TypeScript callers can write
 * `await open(url)` without importing the `Lunaris` class directly —
 * matches Plan 08-02's `lunaris.open(url)` surface.
 *
 * napi-rs 3.x exposes this as `openHandle(url: string): Promise<Lunaris>`
 * at the TS layer. The handwritten `index.mts` wrapper re-exports it as
 * `open(url, opts?)` with the three-surface config path.
 */
export declare function openHandle(url: string): Promise<Lunaris>

/**
 * Minimal `recall` execute bridge for the TS-side DSL.
 *
 * Accepts a plan JSON of shape:
 * `{"query": "...", "k": 5, "index": "chunks", "filter": "...", "as_of_ms": 123}`.
 * All keys are optional; missing fields fall back to
 * `{query: "", k: 5, index: "chunks"}`. Returns a JSON array of hit
 * objects which napi-rs 3.x converts to a `Promise<Array<object>>` in TS.
 */
export declare function recallSimpleExecute(handle: Lunaris, plan: any): Promise<any>
