// Plan 08-03 — ESM entry for the `lunaris` napi-rs binding.
//
// Provides the richer TS-side retrieve DSL (Vector / Keyword / Graph /
// RetrievalBuilder with camelCase combinators) on top of the raw codegen
// surface re-exported from the auto-generated `index.js`. Mirrors the
// Python-side `python/lunaris/dsl.py` plan-builder shape: each DSL entry
// point is a pure-JS plan tree; the terminal `.execute()` calls the Rust
// FFI `recallSimpleExecute` that collapses the plan against the handle's
// storage.
//
// `index.js` is auto-generated by `napi build` and ships a smart loader
// that picks the correct `.node` artefact per platform/arch. We import
// from it via CJS interop, re-export the raw napi-rs classes, then layer
// the pure-TS ergonomic DSL + config-surface toggle on top.

import {
  createRequire,
} from "node:module";

const require = createRequire(import.meta.url);
const native = require("./index.js");

// Re-export every symbol the auto-generated loader yields so
// `import { Lunaris } from "lunaris"` hits the napi-rs class directly.
export const Lunaris = native.Lunaris;
export const GraphPipelineHandle = native.GraphPipelineHandle;
export const ConsolidatorPipelineHandle = native.ConsolidatorPipelineHandle;
export const openHandle = native.openHandle;
export const recallSimpleExecute = native.recallSimpleExecute;
export const conformanceFixtureEpisodes = native.conformanceFixtureEpisodes;
export const scanKvPrefix = native.scanKvPrefix;
export const getGraphPipeline = native.getGraphPipeline;
export const getConsolidatorPipeline = native.getConsolidatorPipeline;
export const graphPipelineEnable = native.graphPipelineEnable;
export const graphPipelineDisable = native.graphPipelineDisable;
export const graphPipelineIsEnabled = native.graphPipelineIsEnabled;
export const consolidatorPipelineEnable = native.consolidatorPipelineEnable;
export const consolidatorPipelineDisable = native.consolidatorPipelineDisable;
export const consolidatorPipelineIsEnabled = native.consolidatorPipelineIsEnabled;
export const fromEnv = native.fromEnv;
export const fromEnvValue = native.fromEnvValue;
export const fromConfig = native.fromConfig;
export const __version__ = "0.1.1";

// Plan 10-03 + 11-03 — expose the Phase 10 conversational + Phase 11
// documentary recipe wrappers flat at the crate root. napi-rs 3.x's
// proc-macro registry surfaces every `#[napi]` class as a top-level
// identifier in the compiled `.node` (see 11-02b Known Limitations —
// `import { X } from 'lunaris/conversational'` is NOT supported);
// these explicit re-exports give ESM callers the same crate-root flat
// imports the auto-generated CJS `index.js` emits for Phase 8 types.
export const ChatAgentMemory = native.ChatAgentMemory;
export const MultiTurnConversation = native.MultiTurnConversation;
export const SlackArchive = native.SlackArchive;
export const SlackArchiveQuery = native.SlackArchiveQuery;
export const EmailThreading = native.EmailThreading;
export const MeetingNotesMemory = native.MeetingNotesMemory;
export const MeetingNotesQuery = native.MeetingNotesQuery;
export const DocumentKnowledgeBase = native.DocumentKnowledgeBase;
export const ResearchPaperCorpus = native.ResearchPaperCorpus;
export const CodeRepoMemory = native.CodeRepoMemory;
export const TimelineReconstruction = native.TimelineReconstruction;
export const CustomerSupportHistory = native.CustomerSupportHistory;

/** napi-rs maps `Error(GenericFailure)` to a plain JS `Error` with
 * `"CODE: message"` format. `LunarisError` is an alias on the plain
 * `Error` constructor so `instanceof Error` and `err instanceof LunarisError`
 * both hit, and `err.message.startsWith("STORAGE:")` works. */
export const LunarisError = Error;

// =============================================================
// Pipeline-handle extension wrappers — layer `.enable()` / `.disable()` /
// `.isEnabled()` / `.toggle(on)` on top of the codegen-single toggle surface.
// Installed on `handle.graphPipeline` and `handle.consolidatorPipeline` by the
// `open()` wrapper below.
// =============================================================

export class GraphPipelineHandleExt {
  constructor(rust) {
    this._inner = rust;
  }
  enable() {
    graphPipelineEnable(this._inner);
  }
  disable() {
    graphPipelineDisable(this._inner);
  }
  isEnabled() {
    return graphPipelineIsEnabled(this._inner);
  }
  toggle(on) {
    if (on) this.enable();
    else this.disable();
  }
}

export class ConsolidatorPipelineHandleExt {
  constructor(rust) {
    this._inner = rust;
  }
  enable() {
    consolidatorPipelineEnable(this._inner);
  }
  disable() {
    consolidatorPipelineDisable(this._inner);
  }
  isEnabled() {
    return consolidatorPipelineIsEnabled(this._inner);
  }
  toggle(on) {
    if (on) this.enable();
    else this.disable();
  }
}

// =============================================================
// TS-side retrieve DSL — mirrors python/lunaris/dsl.py structure.
// =============================================================

class _OpNode {
  constructor(op, args = [], children = []) {
    this.op = op;
    this.args = args;
    this.children = children;
  }
}

class _Composable {
  and(other) {
    return RetrievalBuilder._fromNode(
      new _OpNode("and", [], [this._node, other._node]),
    );
  }
  fuseRrf(k) {
    return RetrievalBuilder._fromNode(
      new _OpNode("fuse_rrf", [Number(k)], [this._node]),
    );
  }
  top(n) {
    return RetrievalBuilder._fromNode(
      new _OpNode("top", [Number(n)], [this._node]),
    );
  }
  asOf(wallMs) {
    const ms = typeof wallMs === "bigint" ? Number(wallMs) : Number(wallMs);
    return RetrievalBuilder._fromNode(
      new _OpNode("as_of", [ms], [this._node]),
    );
  }
  filter(pred) {
    let s;
    if (typeof pred === "string") {
      s = pred;
    } else if (pred && typeof pred === "object") {
      s = Object.entries(pred)
        .map(([k, v]) => `${k} = '${v}'`)
        .join(" AND ");
    } else {
      throw new TypeError("filter() requires a string predicate or an object of equalities");
    }
    return RetrievalBuilder._fromNode(
      new _OpNode("filter", [s], [this._node]),
    );
  }
  filterStr(s) {
    return RetrievalBuilder._fromNode(
      new _OpNode("filter", [String(s)], [this._node]),
    );
  }
}

export class Vector extends _Composable {
  constructor(index, k) {
    super();
    this._node = new _OpNode("vector", [String(index), Number(k)]);
  }
  static new(index, k) {
    return new Vector(index, k);
  }
}

export class Keyword extends _Composable {
  constructor(index, k) {
    super();
    this._node = new _OpNode("keyword", [String(index), Number(k)]);
  }
  static bm25(index, k) {
    return new Keyword(index, k);
  }
}

export class Graph extends _Composable {
  constructor(entityIds, hops = 2) {
    super();
    this._node = new _OpNode("graph", [Array.from(entityIds), Number(hops)]);
  }
  static anchored(entityIds, hops = 2) {
    return new Graph(entityIds, hops);
  }
}

export class RetrievalBuilder extends _Composable {
  constructor(handle) {
    super();
    // Default root is Vector("chunks", 30) — matches the Rust
    // RetrievalBuilder::new default (crates/lunaris-retrieve/src/builder.rs:82).
    this._node = new _OpNode("vector", ["chunks", 30]);
    this._handle = handle ?? null;
  }

  static _fromNode(node) {
    const rb = new RetrievalBuilder();
    rb._node = node;
    return rb;
  }

  bind(handle) {
    this._handle = handle;
    return this;
  }

  async execute() {
    if (this._handle === null) {
      throw new Error(
        "RetrievalBuilder.execute() needs a handle; use handle.recall() or builder.bind(handle) first",
      );
    }
    const plan = _collapsePlan(this._node);
    return recallSimpleExecute(this._handle, plan);
  }
}

function _collapsePlan(root) {
  const plan = { query: "", k: 5, index: "chunks" };

  function visit(n) {
    if (n.op === "vector" || n.op === "keyword") {
      plan.index = n.args[0];
      plan.k = Number(n.args[1]);
    } else if (n.op === "graph") {
      // No-op in the minimal FFI — a follow-up plan wires the real graph
      // branch. Plan 08-03 intentionally lossy per <key_constraints>.
    } else if (n.op === "and") {
      // Composition encoded via children; FFI takes the most recent
      // vector/keyword spec.
    } else if (n.op === "fuse_rrf") {
      // No explicit field in the minimal FFI — collapsed away.
    } else if (n.op === "top") {
      plan.k = Number(n.args[0]);
    } else if (n.op === "filter") {
      plan.filter = String(n.args[0]);
    } else if (n.op === "as_of") {
      plan.as_of_ms = Number(n.args[0]);
    }
    for (const child of n.children) visit(child);
  }

  visit(root);
  return plan;
}

// =============================================================
// Config-surface open() wrapper — walks `opts.graphPipeline` / `.consolidatorPipeline`
// AFTER construction (config surface — last wins vs env, loses to code).
// =============================================================

/** Open a Lunaris handle and install the `.graphPipeline` / `.consolidatorPipeline`
 * accessors + optional config-surface toggle resolution. */
export async function open(url, opts) {
  // Defer to the CJS loader's open() so both entry points share identical
  // behaviour. We can't call `lunaris.open` from here because the CJS
  // loader re-exports its own `open` on the same property we're aliasing
  // to; just call the openHandle + attach sequence inline.
  const handle = await openHandle(url);
  _attachPipelineAccessors(handle);
  if (opts && typeof opts === "object") {
    if (opts.graphPipeline && opts.graphPipeline.enabled) {
      handle.graphPipeline.enable();
    }
    if (opts.consolidatorPipeline && opts.consolidatorPipeline.enabled) {
      handle.consolidatorPipeline.enable();
    }
  }
  return handle;
}

function _attachPipelineAccessors(handle) {
  Object.defineProperty(handle, "graphPipeline", {
    configurable: true,
    enumerable: true,
    get() {
      return new GraphPipelineHandleExt(getGraphPipeline(handle));
    },
  });
  Object.defineProperty(handle, "consolidatorPipeline", {
    configurable: true,
    enumerable: true,
    get() {
      return new ConsolidatorPipelineHandleExt(getConsolidatorPipeline(handle));
    },
  });
}
