// Lunaris — CommonJS entry point for `@pilotspace/lunaris` (package `main`).
//
// ## File roles in this directory
//
//   index.js / index.d.ts   GENERATED by `napi build`. Raw binding surface.
//                           Never hand-edit; any build overwrites them.
//   lunaris.cjs   (this)    hand-written CJS entry — package `main`
//   index.mjs               hand-written ESM entry — package `module`
//   lunaris.d.ts            hand-written declarations — package `types`
//
// ## Why the public entry is not index.js
//
// It used to be, and `napi build` emits over that name — so the package's
// `main` and `types` were the RAW native surface while the ergonomic layer
// (Vector / Keyword / Graph / RetrievalBuilder / open) lived only in the
// hand-written `index.mjs`. Two consequences shipped for four minor
// versions:
//
//   * `require("@pilotspace/lunaris").RetrievalBuilder` was the native
//     class, which has no `.bind()` and no `.execute()` — the documented
//     chain was a TypeError for every CJS consumer;
//   * `index.d.ts` declared neither `open` nor `RetrievalBuilder.bind` /
//     `.execute`, so the README quickstart did not type-check.
//
// Passing `--js` / `--dts` to move the generated output would not have been
// enough: `.github/workflows/{conformance-bindings,ts-prebuild}.yml` invoke
// `npx napi build …` directly rather than `npm run build`, so the flags
// would be absent exactly where it matters most — including the publish
// job. Letting the generator keep its default names and moving the PUBLIC
// entry instead makes the collision impossible to reintroduce.
//
// ## Why the implementation lives here and not in index.mjs
//
// `index.mjs` is a thin re-export of this module. One implementation, so
// ESM and CJS cannot drift: `require("…").RetrievalBuilder ===
// (await import("…")).RetrievalBuilder`, pinned by
// `__test__/readme_quickstart.spec.mts`.

const native = require("./index.js");

// -----------------------------------------------------------------------
// Raw generated surface, passed through unchanged.
// -----------------------------------------------------------------------
// Spread rather than enumerate: a new `#[napi]` item reaches consumers as
// soon as the binding is rebuilt, with no edit here.
Object.assign(module.exports, native);

/** napi-rs maps `Error(GenericFailure)` to a plain JS `Error` with
 * `"CODE: message"` format. `LunarisError` is an alias on the plain
 * `Error` constructor so `instanceof Error` and `err instanceof LunarisError`
 * both hit, and `err.message.startsWith("STORAGE:")` works. */
module.exports.LunarisError = Error;

module.exports.__version__ = require("./package.json").version;

// Patch Lunaris.prototype.scoped so callers write `handle.scoped(scope)` in
// the idiomatic ergonomic form rather than the free-function form.
if (native.Lunaris && native.lunarisScoped) {
  native.Lunaris.prototype.scoped = function (scope) {
    return native.lunarisScoped(this, scope);
  };
}

// =============================================================
// Pipeline-handle extension wrappers — layer `.enable()` / `.disable()` /
// `.isEnabled()` / `.toggle(on)` on top of the codegen-single toggle surface.
// Installed on `handle.graphPipeline` and `handle.consolidatorPipeline` by the
// `open()` wrapper below.
// =============================================================

class GraphPipelineHandleExt {
  constructor(rust) {
    this._inner = rust;
  }
  enable() {
    native.graphPipelineEnable(this._inner);
  }
  disable() {
    native.graphPipelineDisable(this._inner);
  }
  isEnabled() {
    return native.graphPipelineIsEnabled(this._inner);
  }
  toggle(on) {
    if (on) this.enable();
    else this.disable();
  }
}

class ConsolidatorPipelineHandleExt {
  constructor(rust) {
    this._inner = rust;
  }
  enable() {
    native.consolidatorPipelineEnable(this._inner);
  }
  disable() {
    native.consolidatorPipelineDisable(this._inner);
  }
  isEnabled() {
    return native.consolidatorPipelineIsEnabled(this._inner);
  }
  toggle(on) {
    if (on) this.enable();
    else this.disable();
  }
}

// =============================================================
// TS-side retrieve DSL — mirrors python/lunaris/dsl.py structure.
// =============================================================

class _OpNode {
  constructor(op, args = [], children = []) {
    this.op = op;
    this.args = args;
    this.children = children;
  }
}

/** Read `_handle` off a chained-from value. Vector / Keyword / Graph do not
 * define one; a bound `RetrievalBuilder` does, and the chain must carry it
 * or `.execute()` throws "needs a handle" halfway down the README sample. */
function _inheritHandle(src) {
  return src._handle ?? null;
}

class _Composable {
  and(other) {
    return RetrievalBuilder._fromNode(
      new _OpNode("and", [], [this._node, other._node]),
      _inheritHandle(this),
    );
  }
  fuseRrf(k) {
    return RetrievalBuilder._fromNode(
      new _OpNode("fuse_rrf", [Number(k)], [this._node]),
      _inheritHandle(this),
    );
  }
  top(n) {
    return RetrievalBuilder._fromNode(
      new _OpNode("top", [Number(n)], [this._node]),
      _inheritHandle(this),
    );
  }
  /** Set the query text the plan searches for — the TS spelling of the Rust
   * terminal `builder.execute(Query::text(t))`. Without it the plan searches
   * for the empty string, which is what every `.execute()` did before
   * v0.7.1: the DSL had no way to express a text query at all. */
  query(text) {
    return RetrievalBuilder._fromNode(
      new _OpNode("query", [String(text)], [this._node]),
      _inheritHandle(this),
    );
  }
  asOf(wallMs) {
    const ms = typeof wallMs === "bigint" ? Number(wallMs) : Number(wallMs);
    return RetrievalBuilder._fromNode(
      new _OpNode("as_of", [ms], [this._node]),
      _inheritHandle(this),
    );
  }
  filter(pred) {
    let s;
    if (typeof pred === "string") {
      s = pred;
    } else if (pred && typeof pred === "object") {
      s = Object.entries(pred)
        .map(([k, v]) => `${k} = '${v}'`)
        .join(" AND ");
    } else {
      throw new TypeError("filter() requires a string predicate or an object of equalities");
    }
    return RetrievalBuilder._fromNode(
      new _OpNode("filter", [s], [this._node]),
      _inheritHandle(this),
    );
  }
  filterStr(s) {
    return RetrievalBuilder._fromNode(
      new _OpNode("filter", [String(s)], [this._node]),
      _inheritHandle(this),
    );
  }
}

class Vector extends _Composable {
  constructor(index, k) {
    super();
    this._node = new _OpNode("vector", [String(index), Number(k)]);
  }
  static new(index, k) {
    return new Vector(index, k);
  }
}

class Keyword extends _Composable {
  constructor(index, k) {
    super();
    this._node = new _OpNode("keyword", [String(index), Number(k)]);
  }
  static bm25(index, k) {
    return new Keyword(index, k);
  }
}

class Graph extends _Composable {
  constructor(entityIds, hops = 2) {
    super();
    this._node = new _OpNode("graph", [Array.from(entityIds), Number(hops)]);
  }
  static anchored(entityIds, hops = 2) {
    return new Graph(entityIds, hops);
  }
}

class RetrievalBuilder extends _Composable {
  constructor(handle) {
    super();
    // Default root is Vector("chunks", 30) — matches the Rust
    // RetrievalBuilder::new default (crates/lunaris-retrieve/src/builder.rs:82).
    this._node = new _OpNode("vector", ["chunks", 30]);
    this._handle = handle ?? null;
  }

  static _fromNode(node, handle) {
    const rb = new RetrievalBuilder();
    rb._node = node;
    rb._handle = handle ?? null;
    return rb;
  }

  bind(handle) {
    this._handle = handle;
    return this;
  }

  async execute() {
    if (this._handle === null) {
      throw new Error(
        "RetrievalBuilder.execute() needs a handle; use handle.recall() or builder.bind(handle) first",
      );
    }
    return native.recallSimpleExecute(this._handle, _collapsePlan(this._node));
  }
}

/** Marshal the operator tree into the plan object the `recallSimpleExecute`
 * FFI executes. Exported under an underscore for the parity tests; not part
 * of the supported surface.
 *
 * The name is historical — it no longer collapses. F14 replaced the flat
 * `{index, k}` FFI with a `{root: <operator tree>}` one, so the tree a caller
 * composes is the tree the engine builds. `lunaris_retrieve::plan`
 * (Rust) is the single parser both SDKs marshal into.
 *
 * Twin of `python/lunaris/dsl.py::_collapse_plan` — keep the two in step; a
 * divergence here is an SDK parity bug.
 *
 * `query` / `asOf` / `filter` stay envelope-level rather than becoming tree
 * nodes, because they are builder state on the Rust side too: one query text,
 * one as-of witness and one filter narrow the whole plan. That is why setting
 * any of them twice with different values throws — the tree has branches, the
 * envelope does not, and picking one of the two silently would run a query
 * the caller did not write.
 */
function _collapsePlan(root) {
  const envelope = { query: "" };

  function setEnvelope(key, value, op) {
    const already = Object.prototype.hasOwnProperty.call(envelope, key);
    const conflicts =
      key === "query" ? envelope.query !== "" && envelope.query !== value : already && envelope[key] !== value;
    if (conflicts) {
      throw new Error(
        `this plan sets .${op}() twice with different values ` +
          `(${JSON.stringify(envelope[key])} and ${JSON.stringify(value)}), but the ` +
          `plan carries ONE ${key}: it narrows every branch at once. Split the ` +
          `plan, or apply .${op}() once at the top.`,
      );
    }
    envelope[key] = value;
  }

  function onlyChild(n) {
    if (n.children.length !== 1) {
      throw new Error(`\`${n.op}\` wraps exactly one plan, got ${n.children.length}`);
    }
    return n.children[0];
  }

  function build(n) {
    if (n.op === "query") {
      setEnvelope("query", String(n.args[0]), "query");
      return build(onlyChild(n));
    }
    if (n.op === "as_of") {
      setEnvelope("as_of_ms", Number(n.args[0]), "asOf");
      return build(onlyChild(n));
    }
    if (n.op === "filter") {
      setEnvelope("filter", String(n.args[0]), "filter");
      return build(onlyChild(n));
    }
    if (n.op === "vector" || n.op === "keyword") {
      return { op: n.op, index: String(n.args[0]), k: Number(n.args[1]) };
    }
    if (n.op === "graph") {
      return {
        op: "graph",
        seeds: n.args[0].map(_marshalSeed),
        hops: Number(n.args[1]),
      };
    }
    if (n.op === "and") {
      if (n.children.length !== 2) {
        throw new Error(`\`and\` joins exactly two plans, got ${n.children.length}`);
      }
      return { op: "and", left: build(n.children[0]), right: build(n.children[1]) };
    }
    if (n.op === "fuse_rrf") {
      return { op: "fuse_rrf", k: Number(n.args[0]), child: build(onlyChild(n)) };
    }
    if (n.op === "top") {
      return { op: "top", n: Number(n.args[0]), child: build(onlyChild(n)) };
    }
    throw new Error(
      `the TypeScript SDK has no marshalling for operator \`${n.op}\`, so this ` +
        `plan cannot be sent to the engine as written. Drive the full operator ` +
        `tree from the Rust API, or add an arm here and the matching one in ` +
        `\`lunaris_retrieve::plan\`.`,
    );
  }

  envelope.root = build(root);
  return envelope;
}

/** Render one graph anchor into the seed shape the engine accepts.
 *
 * A seed is an entity IDENTITY, and the engine derives that identity from
 * `(name, type)` — the same "Alice" is a different anchor as a Person than as
 * a Place. So a bare `"alice"` is rejected rather than paired with a guessed
 * type: guessing yields a valid-looking EntityId that matches nothing, and a
 * traversal anchored on nothing returns an empty result that is
 * indistinguishable from "no such relationship exists".
 */
function _marshalSeed(seed, index) {
  if (Array.isArray(seed) && seed.length === 2) {
    return { name: String(seed[0]), type: String(seed[1]) };
  }
  if (seed !== null && typeof seed === "object") {
    if ("name" in seed && "type" in seed) {
      const out = { name: String(seed.name), type: String(seed.type) };
      if ("confidence" in seed) out.confidence = Number(seed.confidence);
      return out;
    }
    throw new Error(
      `graph seed ${index} is an object without both 'name' and 'type': ${JSON.stringify(seed)}`,
    );
  }
  if (typeof seed === "string" && /^[0-9a-f]{32}$/i.test(seed)) return seed;
  throw new Error(
    `graph seed ${index} (${JSON.stringify(seed)}) is neither a 32-char hex ` +
      `EntityId nor a (name, type) pair. Pass Graph.anchored([{ name: 'Alice', ` +
      `type: 'Person' }], 2), an ['Alice', 'Person'] pair, or the hex id the ` +
      `engine emitted. A bare name would need a guessed entity type, and the ` +
      `wrong type anchors the traversal on an entity that does not exist — ` +
      `which returns empty, exactly like a real absence of edges.`,
  );
}

// The generated `Lunaris.recall()` returns the codegen-frozen native builder,
// whose every method throws "Plan 08-03 wires the body". Rebind it to the
// working builder, pre-bound to this handle — the same shim
// `python/lunaris/dsl.py::_attach_recall_shim` installs, so
// `handle.recall().query(…).top(n).execute()` reads identically in both SDKs.
if (native.Lunaris) {
  native.Lunaris.prototype.recall = function () {
    return new RetrievalBuilder(this);
  };
}

// =============================================================
// Config-surface open() wrapper — walks `opts.graphPipeline` /
// `.consolidatorPipeline` AFTER construction (config surface — last wins vs
// env, loses to code).
// =============================================================

function _attachPipelineAccessors(handle) {
  Object.defineProperty(handle, "graphPipeline", {
    configurable: true,
    enumerable: true,
    get() {
      return new GraphPipelineHandleExt(native.getGraphPipeline(handle));
    },
  });
  Object.defineProperty(handle, "consolidatorPipeline", {
    configurable: true,
    enumerable: true,
    get() {
      return new ConsolidatorPipelineHandleExt(native.getConsolidatorPipeline(handle));
    },
  });
}

/** Open a Lunaris handle and install the `.graphPipeline` /
 * `.consolidatorPipeline` accessors + optional config-surface toggle
 * resolution. */
async function open(url, opts) {
  const handle = await native.openHandle(url);
  _attachPipelineAccessors(handle);
  if (opts && typeof opts === "object") {
    if (opts.graphPipeline && opts.graphPipeline.enabled) {
      handle.graphPipeline.enable();
    }
    if (opts.consolidatorPipeline && opts.consolidatorPipeline.enabled) {
      handle.consolidatorPipeline.enable();
    }
  }
  return handle;
}

// -----------------------------------------------------------------------
// Ergonomic overrides — these SHADOW the same-named generated exports.
// -----------------------------------------------------------------------
module.exports.GraphPipelineHandleExt = GraphPipelineHandleExt;
module.exports.ConsolidatorPipelineHandleExt = ConsolidatorPipelineHandleExt;
module.exports.Vector = Vector;
module.exports.Keyword = Keyword;
module.exports.Graph = Graph;
module.exports.RetrievalBuilder = RetrievalBuilder;
module.exports.open = open;
module.exports._collapsePlan = _collapsePlan;
