//! `lunaris-embed-native` — pure-Rust ModernBERT FP16 embedder built on
//! `candle-transformers::models::modernbert`, purpose-built for
//! [`ibm-granite/granite-embedding-311m-multilingual-r2`].
//!
//! ## Why a new crate (not a feature on `lunaris-embed`)
//!
//! `lunaris-embed` is the ONNX/fastembed/candle-gemma trio that ships
//! EmbeddingGemma 300M. This crate hosts the v0.4 milestone's *replacement*
//! plan: a single candle-native backend serving granite-311m-r2 + the
//! companion reranker. Keeping the two crates separate lets us:
//!
//! - swap embedders behind the `Embedder` trait without touching the
//!   existing crate's feature matrix,
//! - run a numerical-equivalence gate (≤0.5% mean cosine drift vs HF
//!   `sentence-transformers`) without coupling to fastembed's ORT version,
//! - quantize / port the reranker / delete fastembed in follow-up phases
//!   without dragging the rest of the workspace.
//!
//! ## Architecture (FP16 path)
//!
//! ```text
//! NativeEmbedder
//!   └─ Inner = Arc<{ tokenizer, model: ModernBert, device, scratch_mutex }>
//!       ├─ tokenizer    : `tokenizers::Tokenizer` (loaded from `tokenizer.json`)
//!       └─ model        : candle_transformers::models::modernbert::ModernBert
//!                         (the FP32-computed forward pass — fp16 weights are
//!                          cast to fp32 on load to hit the 0.5% drift gate)
//! ```
//!
//! `NativeEmbedder::embed_batch` runs inside `tokio::task::spawn_blocking`;
//! the internal `parking_lot::Mutex<Tensor>` scratch (if used) is acquired
//! INSIDE the blocking closure — never across `.await` (CLAUDE.md lock
//! discipline).
//!
//! ## Numerical-equivalence gate
//!
//! `tests/numerical_equivalence.rs` (feature `embedder-it`) runs
//! `NativeEmbedder` against a 100-prompt panel (35 EN + 35 VI + 30 code) and
//! asserts mean cosine drift ≤ 0.005 and max ≤ 0.02 against
//! `sentence-transformers/SentenceTransformer("ibm-granite/granite-embedding-311m-multilingual-r2")`.
//! The reference fixture is generated by
//! `scripts/spike-generate-reference-embeddings.py` and committed under
//! `tests/fixtures/reference_embeddings.json`.
//!
//! ## Out of scope (follow-up spawns)
//!
//! - Q4 / quantized path
//! - Reranker port
//! - Backend deletions (`lunaris-embed`, candle-gemma, ollama)
//!
//! [`ibm-granite/granite-embedding-311m-multilingual-r2`]:
//! https://huggingface.co/ibm-granite/granite-embedding-311m-multilingual-r2

#![deny(rust_2018_idioms, unreachable_pub)]
#![forbid(unsafe_code)]

pub mod config;
pub mod embedder;
pub mod modernbert;
pub mod tokenizer;

pub use config::ModernBertConfig;
pub use embedder::{NativeEmbedder, NativeEmbedderError, NativeEmbedderOpts};

/// Output dimensionality of `granite-embedding-311m-multilingual-r2`.
///
/// 768-d unit vectors, matching the Lunaris default storage schema
/// (Moon `FT.SEARCH` 768-d HNSW index + Postgres `vector(768)`).
pub const GRANITE_R2_DIM: usize = 768;
