// W0.5 + W0.6 — the README TypeScript quickstart, exercised from the
// consumer's side of the API.
//
// Four things can be wrong independently, so there are four tests:
//
//  1. DRIFT   — the type-check fixture must still be the README's code block.
//  2. ESM     — `import { open, RetrievalBuilder } from "…"` must yield a
//               builder with `.bind()`, `.query()`, `.top()`, `.execute()`,
//               and the chain must keep its handle (a `_fromNode` that drops
//               `_handle` turns the README chain into a thrown Error).
//  3. CJS     — `require("../index.js")` must hand back the SAME wrapped
//               classes. Before the fix it re-exported the RAW native
//               `RetrievalBuilder`, so `.bind` was `undefined` and the
//               documented chain was a live TypeError for every CJS consumer.
//  4. LIVE    — against a real Moon, the documented chain returns hits for a
//               real query, with a stub OpenAI-compatible embedder standing
//               in for llama.cpp (deterministic, no GGUF, no Metal context).
//
// The type-level half lives in `npm run typecheck`
// (tsc --noEmit -p tsconfig.readme.json) — a runtime test cannot see a wrong
// `index.d.ts`.

import { createRequire } from "node:module";
import { createHash } from "node:crypto";
import { execFile, execFileSync } from "node:child_process";
import { promisify } from "node:util";
import fs from "node:fs";
import http from "node:http";
import path from "node:path";
import url from "node:url";

import { describe, expect, test } from "vitest";

const execFileAsync = promisify(execFile);

const HERE = path.dirname(url.fileURLToPath(import.meta.url));
const CRATE = path.resolve(HERE, "..");
const REPO = path.resolve(CRATE, "..", "..");

// Resolve the entry points from package.json rather than hardcoding file
// names — a consumer only ever sees `main` / `module` / `types`, and this
// suite must fail if those point somewhere broken.
const PKG = JSON.parse(fs.readFileSync(path.join(CRATE, "package.json"), "utf8"));
const CJS_ENTRY = path.join(CRATE, PKG.exports["."].require);
const ESM_ENTRY = path.join(CRATE, PKG.exports["."].import);

const esm = await import(url.pathToFileURL(ESM_ENTRY).href);

// ---------------------------------------------------------------------------
// 1. The fixture must not drift from the README.
// ---------------------------------------------------------------------------

function readmeTsBlock(): string {
  const md = fs.readFileSync(path.join(REPO, "README.md"), "utf8");
  const m = md.match(/```ts\n([\s\S]*?)```/);
  if (!m) throw new Error("no ```ts block found in README.md");
  return m[1];
}

function fixtureBody(): string {
  const src = fs.readFileSync(
    path.join(HERE, "readme_quickstart.ts"),
    "utf8",
  );
  const marker = "// --- BEGIN-README ---\n";
  const i = src.indexOf(marker);
  if (i < 0) throw new Error("readme_quickstart.ts lost its BEGIN-README marker");
  return src.slice(i + marker.length);
}

describe("README TypeScript quickstart", () => {
  test("the type-check fixture is the README block verbatim", () => {
    expect(fixtureBody()).toBe(readmeTsBlock());
  });

  test("`types` points at declarations that cover the ergonomic layer", () => {
    const dts = fs.readFileSync(path.join(CRATE, PKG.types), "utf8");
    // `npm run typecheck` is the real gate; this catches the specific
    // regression of re-pointing `types` at the napi-generated file, which
    // declares none of these.
    expect(dts).toContain("export declare function open(");
    expect(dts).toMatch(/bind\(handle/);
    expect(dts).toMatch(/execute\(\)/);
    expect(dts).toMatch(/query\(text/);
    expect(dts).not.toMatch(/^\/\* auto-generated by NAPI-RS \*\//m);
  });

  // -------------------------------------------------------------------------
  // 2. ESM — the documented import yields a working builder.
  // -------------------------------------------------------------------------

  test("ESM: the documented chain builds without losing its handle", () => {
    const { RetrievalBuilder } = esm;
    const handle = { __fake: true };
    const chained = new RetrievalBuilder()
      .bind(handle)
      .query("what does Alice like?")
      .top(5);
    expect(chained).toBeInstanceOf(RetrievalBuilder);
    expect(chained._handle).toBe(handle);
  });

  test("ESM: .query(text) reaches the collapsed plan", () => {
    const { RetrievalBuilder, Vector, _collapsePlan } = esm;
    const plan = _collapsePlan(
      new RetrievalBuilder().query("chocolate").top(3)._node,
    );
    expect(plan.query).toBe("chocolate");
    expect(plan.k).toBe(3);

    // `.top(n)` is the OUTER operator; the leaf `k` must not overwrite it.
    expect(_collapsePlan(Vector.new("chunks", 30).top(5)._node).k).toBe(5);

    // Composes with every other combinator, in any order.
    const full = _collapsePlan(
      Vector.new("chunks", 30)
        .query("chocolate")
        .filter({ source: "quickstart" })
        .asOf(1_000_000)
        .top(4)._node,
    );
    expect(full).toMatchObject({
      query: "chocolate",
      index: "chunks",
      k: 4,
      filter: "source = 'quickstart'",
      as_of_ms: 1_000_000,
    });
  });

  // Twin of `crates/lunaris-py/tests/test_query_dsl.py`'s three refusal tests.
  // The collapsed plan holds ONE index and ONE k, so a plan that names more
  // than one leg — or a leg the FFI has no field for — used to become a
  // different query and return its results as if they answered the original.
  test("ESM: a second retrieval leg is refused, not silently dropped", () => {
    const { Vector, Keyword, _collapsePlan } = esm;
    // Measured before the refusal: this collapsed to {index: "facts", k: 5},
    // and flipping the operands searched "chunks" instead — the index was
    // decided by source order.
    const plan = Vector.new("chunks", 10)
      .and(Keyword.bm25("facts", 20))
      .fuseRrf(60)
      .top(5);
    expect(() => _collapsePlan(plan._node)).toThrow(/2 retrieval legs/);
    // Both legs must be named; an error mentioning one leaves the reader
    // guessing which half of their plan was the problem.
    expect(() => _collapsePlan(plan._node)).toThrow(/chunks/);
    expect(() => _collapsePlan(plan._node)).toThrow(/facts/);
  });

  test("ESM: an unsupported operator is refused, not silently dropped", () => {
    const { Vector, Graph, _collapsePlan } = esm;
    const plan = Vector.new("chunks", 30).and(Graph.anchored(["alice"], 2)).top(5);
    expect(() => _collapsePlan(plan._node)).toThrow(/graph traversal/);
  });

  test("ESM: a no-op operator is not an error", () => {
    // The rule is "refuse what would change the plan", not "refuse anything
    // the FFI lacks a field for". fuseRrf over a single leg fuses nothing.
    const { Vector, _collapsePlan } = esm;
    const plan = _collapsePlan(Vector.new("chunks", 30).fuseRrf(60).top(5)._node);
    expect(plan).toMatchObject({ index: "chunks", k: 5 });
  });

  // -------------------------------------------------------------------------
  // 3. CJS — same wrapped classes, or the documented chain is a TypeError.
  // -------------------------------------------------------------------------

  test("CJS: require() exports the wrapped classes, not the raw native ones", () => {
    const require_ = createRequire(import.meta.url);
    const cjs = require_(CJS_ENTRY);
    for (const name of ["Vector", "Keyword", "Graph", "RetrievalBuilder", "open"]) {
      expect(cjs[name], `${PKG.main} is missing ${name}`).toBeDefined();
    }
    const proto = cjs.RetrievalBuilder.prototype;
    for (const m of ["bind", "query", "top", "and", "fuseRrf", "filter", "asOf", "execute"]) {
      expect(typeof proto[m], `CJS RetrievalBuilder.${m}`).toBe("function");
    }
    // The exact call a CJS consumer copies out of the README.
    const handle = { __fake: true };
    const chained = new cjs.RetrievalBuilder().bind(handle).query("x").top(5);
    expect(chained._handle).toBe(handle);
  });

  // Run in a REAL node process: vitest's transform pipeline gives the ESM
  // and CJS graphs separate instances of index.js, so an in-suite identity
  // check would fail for a reason that has nothing to do with the package.
  test("CJS and ESM hand back the identical class objects", () => {
    const cjsPath = CJS_ENTRY;
    const esmUrl = url.pathToFileURL(ESM_ENTRY).href;
    const probe = `
      import { createRequire } from "node:module";
      const req = createRequire(${JSON.stringify(cjsPath)});
      const cjs = req(${JSON.stringify(cjsPath)});
      const esm = await import(${JSON.stringify(esmUrl)});
      for (const n of ["RetrievalBuilder", "Vector", "Keyword", "Graph", "open"]) {
        if (cjs[n] !== esm[n]) { console.error("MISMATCH: " + n); process.exit(1); }
      }
      // The documented chain, run from CJS.
      const h = { __fake: true };
      const b = new cjs.RetrievalBuilder().bind(h).query("x").top(5);
      if (b._handle !== h) { console.error("CJS chain lost its handle"); process.exit(1); }
      console.log("OK");
    `;
    const out = execFileSync(process.execPath, ["--input-type=module", "-e", probe], {
      encoding: "utf8",
      cwd: CRATE,
    });
    expect(out.trim()).toBe("OK");
  });
});

// ---------------------------------------------------------------------------
// 4. LIVE — real Moon + stub embedder. Skips loudly when either is absent.
// ---------------------------------------------------------------------------

const MOON_URL = process.env.LUNARIS_MOON_URL ?? "";
const DIM = 768; // lunaris_embed_remote::openai::DEFAULT_DIM

function embed(text: string): number[] {
  const vec = new Array<number>(DIM).fill(0);
  for (const token of text.toLowerCase().split(/[^a-z0-9]+/).filter(Boolean)) {
    const h = createHash("sha256").update(token).digest();
    vec[h.readUInt32BE(0) % DIM] += 1;
  }
  const norm = Math.sqrt(vec.reduce((a, v) => a + v * v, 0));
  if (norm === 0) vec[0] = 1;
  else for (let i = 0; i < DIM; i++) vec[i] /= norm;
  return vec;
}

/**
 * Start a stub OpenAI-compatible `/v1/embeddings` server, run `fn` with its
 * URL, then shut it down. `seen` records every text the engine asked to
 * embed, which is how we prove the query crossed the FFI.
 */
async function withStubEmbedder<T>(
  fn: (baseUrl: string, seen: string[]) => Promise<T>,
): Promise<T> {
  const seen: string[] = [];
  const srv = http.createServer((req, res) => {
    const chunks: Buffer[] = [];
    req.on("data", (c) => chunks.push(c));
    req.on("end", () => {
      const body = JSON.parse(Buffer.concat(chunks).toString() || "{}");
      const inputs: string[] = Array.isArray(body.input) ? body.input : [body.input];
      seen.push(...inputs);
      const payload = JSON.stringify({
        object: "list",
        model: body.model ?? "stub",
        data: inputs.map((t, i) => ({ object: "embedding", index: i, embedding: embed(t) })),
      });
      res.writeHead(200, { "content-type": "application/json" });
      res.end(payload);
    });
  });
  await new Promise<void>((resolve) => srv.listen(0, "127.0.0.1", resolve));
  const { port } = srv.address() as { port: number };
  try {
    return await fn(`http://127.0.0.1:${port}`, seen);
  } finally {
    await new Promise<void>((resolve) => srv.close(() => resolve()));
  }
}

function episode(content: string): Record<string, unknown> {
  // ULID-shaped id; the binding parses it, it need not be monotonic here.
  const alphabet = "0123456789ABCDEFGHJKMNPQRSTVWXYZ";
  let id = "";
  for (let i = 0; i < 26; i++) id += alphabet[Math.floor(Math.random() * 32)];
  return {
    id,
    scope: "_dev_",
    source: "quickstart",
    content,
    t_ref: null,
    bt: {
      valid: [{ wall_ms: 0, counter: 0, node_id: 0 }, null],
      sys: [{ wall_ms: 0, counter: 0, node_id: 0 }, null],
    },
    metadata: {},
  };
}

describe.skipIf(!MOON_URL)("README TypeScript quickstart — live", () => {
  test("the documented chain returns real hits for a real query", async () => {
    await withStubEmbedder(async (stubUrl, seen) => {
      // The engine must run in a REAL process, not a vitest worker thread:
      // `process.env` inside a worker is a per-thread JS copy and never
      // reaches the native `std::env::var`, so an in-suite version of this
      // test passed while silently using the zero-vector NoopEmbedder.
      const esmUrl = url.pathToFileURL(ESM_ENTRY).href;
      const probe = `
        const { open, RetrievalBuilder } = await import(${JSON.stringify(esmUrl)});
        const handle = await open(process.env.PROBE_MOON_URL);
        const mk = (content) => {
          const A = "0123456789ABCDEFGHJKMNPQRSTVWXYZ";
          const enc = (v, w) => { let o = ""; for (let i = 0; i < w; i++) { o = A[v % 32] + o; v = Math.floor(v / 32); } return o; };
          return {
            id: enc(Date.now(), 10) + enc(Math.floor(Math.random() * 2 ** 40), 8) + enc(Math.floor(Math.random() * 2 ** 40), 8),
            scope: "_dev_", source: "quickstart", content, t_ref: null,
            bt: { valid: [{ wall_ms: 0, counter: 0, node_id: 0 }, null],
                  sys:   [{ wall_ms: 0, counter: 0, node_id: 0 }, null] },
            metadata: {},
          };
        };
        await handle.ingest(mk("Alice loves chocolate."));
        await handle.ingest(mk("Bob repairs bicycles."));
        const hits = await new RetrievalBuilder()
          .bind(handle)
          .query("chocolate")
          .top(5)
          .execute();
        console.log(JSON.stringify(hits.map((h) => h.text)));
      `;
      // execFileASYNC, not Sync: the stub embedder server runs on this
      // thread's event loop, and a synchronous spawn would block it — the
      // child's very first /v1/embeddings request would hang until timeout.
      const { stdout: out } = await execFileAsync(
        process.execPath,
        ["--input-type=module", "-e", probe],
        {
          encoding: "utf8",
          cwd: CRATE,
          env: {
            ...process.env,
            PROBE_MOON_URL: MOON_URL,
            LUNARIS_EMBEDDER_OPENAI_URL: stubUrl,
          },
        },
      );

      if (seen.length === 0) {
        // The binding was built without `embed-remote`, so there is no way
        // to drive a deterministic embedder here. Say so rather than
        // asserting on zero-vector results.
        throw new Error(
          "the stub embedder was never called — rebuild the binding with " +
            "`napi build --platform --no-default-features --features embed-remote` " +
            "(or run this suite against a llama.cpp build and drop the assertion)",
        );
      }

      const texts: string[] = JSON.parse(out.trim().split("\n").pop()!);
      expect(texts.length).toBeGreaterThan(0);
      expect(texts[0].toLowerCase()).toContain("chocolate");
      // The spy proves the query text crossed the FFI into the engine.
      expect(seen).toContain("chocolate");
    });
  });
});
