// @generated by lunaris-codegen — do not edit
//
// Phase 8 Plan 08-01 (BIND-GEN-01..03). napi-rs 3.x wrapper surface emitted
// from `crates/lunaris-codegen/annotations/surface.toml`. Regenerate with
// `cargo run -p lunaris-codegen -- --emit ts`.

// allow(deprecated): generated bindings mirror the annotated Rust surface
// verbatim, including methods the Rust layer has deprecated for native
// callers (e.g. engine-level `Lunaris::forget`). SDK-facing deprecation
// messaging is handled in the Python/TS layer, not by rustc lints here.
#![allow(deprecated)]

use napi_derive::napi;
use std::sync::Arc;

use super::errors::napi_err;
use super::js_value::from_js;

/// High-level memory-engine handle. Opens a storage backend by URL and drives ingest, recall, forget, and snapshot.
#[napi]
pub struct Lunaris {
    #[allow(dead_code)]
    pub(crate) inner: Arc<::lunaris::Lunaris>,
}

#[napi]
impl Lunaris {
    /// Production constructor. Routes `url` through the scheme dispatcher to pick a StoragePort backend.
    #[napi(factory)]
    pub async fn open(url: String) -> napi::Result<Self> {
        let inner = ::lunaris::Lunaris::open(&url).await.map_err(napi_err)?;
        Ok(Self { inner: Arc::new(inner) })
    }

    /// Ingest one Episode through the hot path (graph-OFF default) or the graph-extraction path (toggle ON).
    #[napi]
    pub async fn ingest(&self, episode: serde_json::Value) -> napi::Result<String> {
        let episode_owned: ::lunaris::Episode = from_js(episode.clone()).map_err(napi_err)?;
        let out = self.inner.ingest(episode_owned).await.map_err(napi_err)?;
        Ok(out.to_string())
    }

    /// Build a RetrievalBuilder bound to this handle's storage / keyword / embedder / clock.
    #[napi]
    pub fn recall(&self) -> napi::Result<RetrievalBuilder> {
        let out = self.inner.recall();
        Ok(RetrievalBuilder { inner: Arc::new(out) })
    }

    /// Single-entry-point erasure API (OPS-01/02/03/04). Soft-delete default; hard mode requires a confirmation token.
    #[napi]
    pub async fn forget(&self, req: serde_json::Value) -> napi::Result<serde_json::Value> {
        let req_owned: ::lunaris::forget::ForgetRequest = from_js(req.clone()).map_err(napi_err)?;
        let out = self.inner.forget(req_owned).await.map_err(napi_err)?;
        serde_json::to_value(&out).map_err(napi_err)
    }

    /// Which embedder backend this process resolved: "llamacpp", "openai-remote", "ollama-remote", "noop", or "unresolved". A "noop" backend produces zero vectors, so recall silently degrades to keyword-only while still returning results.
    #[napi]
    pub fn embedder_backend(&self) -> napi::Result<String> {
        let out = self.inner.embedder_backend();
        Ok(out)
    }

    /// Returns the current monotonic LSN — a cheap consistent snapshot marker. Implemented as no-op atomic_write(&[]).
    #[napi]
    pub async fn snapshot(&self) -> napi::Result<String> {
        let out = self.inner.snapshot().await.map_err(napi_err)?;
        Ok(out.to_string())
    }
}

/// Vector-search DSL operator; root-level constructor for kNN retrieval.
#[napi]
pub struct Vector {
    #[allow(dead_code)]
    pub(crate) inner: Arc<::lunaris::Vector>,
}

#[napi]
impl Vector {
    /// Construct a Vector retriever over `index` with top-k fan-out.
    #[napi(factory)]
    pub fn new(index: String, k: u32) -> Self {
        let inner = ::lunaris::Vector::new(&index, k as usize);
        Self { inner: Arc::new(inner) }
    }
}

/// Keyword / BM25 DSL operator; root-level constructor for lexical retrieval.
#[napi]
pub struct Keyword {
    #[allow(dead_code)]
    pub(crate) inner: Arc<::lunaris::Keyword>,
}

#[napi]
impl Keyword {
    /// Construct a BM25 keyword retriever over `index` with top-k fan-out.
    #[napi(factory)]
    pub fn bm25(index: String, k: u32) -> Self {
        let inner = ::lunaris::Keyword::bm25(&index, k as usize);
        Self { inner: Arc::new(inner) }
    }
}

/// Graph-traversal DSL operator; anchors on a set of entity ids and expands N hops.
#[napi]
pub struct Graph {
    #[allow(dead_code)]
    pub(crate) inner: Arc<::lunaris::Graph>,
}

#[napi]
impl Graph {
    /// Anchor on `entity_ids` and traverse up to `hops` edges out in the Lunaris graph.
    #[napi(factory)]
    pub fn anchored(entity_ids: Vec<serde_json::Value>, hops: u32) -> napi::Result<Self> {
        let entity_ids_owned: Vec<::lunaris::EntityId> =
            from_js(serde_json::Value::Array(entity_ids.clone())).map_err(napi_err)?;
        let inner = ::lunaris::Graph::anchored(
            entity_ids_owned.into_iter().map(|e| (e, 1.0_f32)).collect(),
            hops as usize,
        );
        Ok(Self { inner: Arc::new(inner) })
    }
}

/// Chainable retrieval plan builder. Terminal .execute() runs the plan through the hydrate stage.
#[napi]
pub struct RetrievalBuilder {
    #[allow(dead_code)]
    pub(crate) inner: Arc<::lunaris::RetrievalBuilder>,
}

#[napi]
impl RetrievalBuilder {
    /// Compose `other` in parallel with the current plan; unions the result set.
    #[napi]
    pub fn and(&self, other: serde_json::Value) -> napi::Result<RetrievalBuilder> {
        // Owned-self builder methods return a new wrapper; Plan 08-03 wires the body.
        let _ = other;
        Err(napi::Error::from_reason("Plan 08-03 wires the body"))
    }

    /// Fuse two parallel branches via reciprocal-rank fusion (client-side or Moon-native depending on capabilities).
    #[napi]
    pub fn fuse_rrf(&self, k: u32) -> napi::Result<RetrievalBuilder> {
        // Owned-self builder methods return a new wrapper; Plan 08-03 wires the body.
        let _ = k;
        Err(napi::Error::from_reason("Plan 08-03 wires the body"))
    }

    /// Keep only the top `n` hits after fusion.
    #[napi]
    pub fn top(&self, n: u32) -> napi::Result<RetrievalBuilder> {
        // Owned-self builder methods return a new wrapper; Plan 08-03 wires the body.
        let _ = n;
        Err(napi::Error::from_reason("Plan 08-03 wires the body"))
    }

    /// Attach a filter predicate (parsed via filter_str) to the query; fails on a malformed predicate string.
    #[napi]
    pub fn filter(&self, pred: String) -> napi::Result<RetrievalBuilder> {
        // Owned-self builder methods return a new wrapper; Plan 08-03 wires the body.
        let _ = &pred;
        Err(napi::Error::from_reason("Plan 08-03 wires the body"))
    }

    /// Pin the query to an as-of-HLC time-travel view (SQL:2011 bi-temporal read).
    #[napi]
    pub fn as_of(&self, hlc: serde_json::Value) -> napi::Result<RetrievalBuilder> {
        // Owned-self builder methods return a new wrapper; Plan 08-03 wires the body.
        let _ = hlc;
        Err(napi::Error::from_reason("Plan 08-03 wires the body"))
    }
}

/// Runtime toggle for the graph-extraction pipeline (default OFF per blueprint §5.2). The toggle method is the canonical single-item entry in the binding surface.
#[napi]
pub struct GraphPipelineHandle {
    #[allow(dead_code)]
    pub(crate) inner: Arc<::lunaris::GraphPipelineHandle>,
}

#[napi]
impl GraphPipelineHandle {
    /// Flip the pipeline ON or OFF. Idempotent. Emits `tracing::info!` only on real state transitions (D-12).
    #[napi]
    pub fn toggle(&self, on: bool) -> napi::Result<()> {
        if on {
            self.inner.enable();
        } else {
            self.inner.disable();
        }
        Ok(())
    }
}

/// Runtime toggle for the ACT-R consolidator worker (default OFF per blueprint §5.1). Mirrors GraphPipelineHandle's single-item toggle surface.
#[napi]
pub struct ConsolidatorPipelineHandle {
    #[allow(dead_code)]
    pub(crate) inner: Arc<::lunaris::ConsolidatorPipelineHandle>,
}

#[napi]
impl ConsolidatorPipelineHandle {
    /// Flip the pipeline ON or OFF. Idempotent. Emits `tracing::info!` only on real state transitions (D-12).
    #[napi]
    pub fn toggle(&self, on: bool) -> napi::Result<()> {
        if on {
            self.inner.enable();
        } else {
            self.inner.disable();
        }
        Ok(())
    }
}

/// Conversational wrapper exposing a `remember` / `recall` pair over a per-user `MessageStream + WorkingMemory` pair.
#[napi]
pub struct ChatAgentMemory {
    #[allow(dead_code)]
    pub(crate) inner: Arc<::lunaris_recipes::conversational::ChatAgentMemory>,
}

#[napi]
impl ChatAgentMemory {
    /// Construct a ChatAgentMemory bound to `user_id`.
    #[napi(factory)]
    pub fn new(lunaris: &Lunaris, scope: String, user_id: String) -> napi::Result<Self> {
        let lunaris_owned: ::std::sync::Arc<::lunaris::Lunaris> = lunaris.inner.clone();
        let scope_owned: ::lunaris_core::scope::Scope = ::lunaris_core::scope::Scope::new(&scope)
            .map_err(|e| {
            crate::errors::napi_err_with_code("VALIDATE", format!("scope: {e}"))
        })?;
        let inner = ::lunaris_recipes::conversational::ChatAgentMemory::new(
            lunaris_owned,
            scope_owned,
            &user_id,
        );
        Ok(Self { inner: Arc::new(inner) })
    }

    /// Record a single conversational turn.
    #[napi]
    pub async fn remember(&self, turn: String) -> napi::Result<String> {
        let out = self.inner.remember(&turn).await.map_err(napi_err)?;
        Ok(out.to_string())
    }

    /// Recall turns matching `query`.
    #[napi]
    pub async fn recall(&self, query: String) -> napi::Result<Vec<serde_json::Value>> {
        let out = self.inner.recall(&query).await.map_err(napi_err)?;
        out.iter()
            .map(|v| serde_json::to_value(v).map_err(napi_err))
            .collect::<napi::Result<Vec<_>>>()
    }
}

/// Cross-session conversational wrapper with a per-user scoped `.consolidate()` cross-session promotion pass.
#[napi]
pub struct MultiTurnConversation {
    #[allow(dead_code)]
    pub(crate) inner: Arc<::lunaris_recipes::conversational::MultiTurnConversation>,
}

#[napi]
impl MultiTurnConversation {
    /// Construct bound to `user_id`.
    #[napi(factory)]
    pub fn new(lunaris: &Lunaris, scope: String, user_id: String) -> napi::Result<Self> {
        let lunaris_owned: ::std::sync::Arc<::lunaris::Lunaris> = lunaris.inner.clone();
        let scope_owned: ::lunaris_core::scope::Scope = ::lunaris_core::scope::Scope::new(&scope)
            .map_err(|e| {
            crate::errors::napi_err_with_code("VALIDATE", format!("scope: {e}"))
        })?;
        let inner = ::lunaris_recipes::conversational::MultiTurnConversation::new(
            lunaris_owned,
            scope_owned,
            &user_id,
        );
        Ok(Self { inner: Arc::new(inner) })
    }

    /// Record a turn for `thread_id` (session id).
    #[napi]
    pub async fn remember(&self, turn: String, thread_id: String) -> napi::Result<String> {
        let out = self.inner.remember(&turn, &thread_id).await.map_err(napi_err)?;
        Ok(out.to_string())
    }

    /// Recall turns matching `query` across all sessions.
    #[napi]
    pub async fn recall(&self, query: String) -> napi::Result<Vec<serde_json::Value>> {
        let out = self.inner.recall(&query).await.map_err(napi_err)?;
        out.iter()
            .map(|v| serde_json::to_value(v).map_err(napi_err))
            .collect::<napi::Result<Vec<_>>>()
    }

    /// Run one scope-filtered consolidation pass (Phase 9.1 cross-user isolation).
    #[napi]
    pub async fn consolidate(&self) -> napi::Result<serde_json::Value> {
        let out = self.inner.consolidate().await.map_err(napi_err)?;
        serde_json::to_value(&out).map_err(napi_err)
    }
}

/// Slack archive wrapper. Holds a root MessageStream scoped at `slack:archive/`.
#[napi]
pub struct SlackArchive {
    #[allow(dead_code)]
    pub(crate) inner: Arc<::lunaris_recipes::conversational::SlackArchive>,
}

#[napi]
impl SlackArchive {
    /// Construct a root archive handle.
    #[napi(factory)]
    pub fn new(lunaris: &Lunaris, scope: String) -> napi::Result<Self> {
        let lunaris_owned: ::std::sync::Arc<::lunaris::Lunaris> = lunaris.inner.clone();
        let scope_owned: ::lunaris_core::scope::Scope = ::lunaris_core::scope::Scope::new(&scope)
            .map_err(|e| {
            crate::errors::napi_err_with_code("VALIDATE", format!("scope: {e}"))
        })?;
        let inner =
            ::lunaris_recipes::conversational::SlackArchive::new(lunaris_owned, scope_owned);
        Ok(Self { inner: Arc::new(inner) })
    }

    /// Ingest one message into `channel` authored by `participant_id`.
    #[napi]
    pub async fn ingest_channel(
        &self,
        channel: String,
        participant_id: String,
        message: String,
    ) -> napi::Result<String> {
        let out = self
            .inner
            .ingest_channel(&channel, &participant_id, &message)
            .await
            .map_err(napi_err)?;
        Ok(out.to_string())
    }

    /// Recall across the whole archive.
    #[napi]
    pub async fn recall(&self, query: String) -> napi::Result<Vec<serde_json::Value>> {
        let out = self.inner.recall(&query).await.map_err(napi_err)?;
        out.iter()
            .map(|v| serde_json::to_value(v).map_err(napi_err))
            .collect::<napi::Result<Vec<_>>>()
    }

    /// Narrow to one channel. Returns a SlackArchiveQuery.
    #[napi]
    pub fn channel(&self, id: String) -> napi::Result<SlackArchiveQuery> {
        let out = self.inner.channel(&id);
        Ok(SlackArchiveQuery { inner: Arc::new(out) })
    }

    /// Narrow to one user. Returns a SlackArchiveQuery.
    #[napi]
    pub fn user(&self, id: String) -> napi::Result<SlackArchiveQuery> {
        let out = self.inner.user(&id);
        Ok(SlackArchiveQuery { inner: Arc::new(out) })
    }
}

/// Narrowed query builder returned by SlackArchive::channel / SlackArchive::user.
#[napi]
pub struct SlackArchiveQuery {
    #[allow(dead_code)]
    pub(crate) inner: Arc<::lunaris_recipes::conversational::SlackArchiveQuery>,
}

#[napi]
impl SlackArchiveQuery {
    /// Add a `user` narrow on top of a `.channel(...)` narrow.
    #[napi]
    pub fn with_user(&self, id: String) -> napi::Result<SlackArchiveQuery> {
        let out = self.inner.as_ref().clone().with_user(&id);
        Ok(SlackArchiveQuery { inner: Arc::new(out) })
    }

    /// Execute the narrowed recall.
    #[napi]
    pub async fn recall(&self, query: String) -> napi::Result<Vec<serde_json::Value>> {
        let out = self.inner.recall(&query).await.map_err(napi_err)?;
        out.iter()
            .map(|v| serde_json::to_value(v).map_err(napi_err))
            .collect::<napi::Result<Vec<_>>>()
    }
}

/// Thread-scoped email wrapper with an opt-in graph-pipeline builder.
#[napi]
pub struct EmailThreading {
    #[allow(dead_code)]
    pub(crate) inner: Arc<::lunaris_recipes::conversational::EmailThreading>,
}

#[napi]
impl EmailThreading {
    /// Construct a new email-archive handle rooted at `email:thread/`.
    #[napi(factory)]
    pub fn new(lunaris: &Lunaris, scope: String) -> napi::Result<Self> {
        let lunaris_owned: ::std::sync::Arc<::lunaris::Lunaris> = lunaris.inner.clone();
        let scope_owned: ::lunaris_core::scope::Scope = ::lunaris_core::scope::Scope::new(&scope)
            .map_err(|e| {
            crate::errors::napi_err_with_code("VALIDATE", format!("scope: {e}"))
        })?;
        let inner =
            ::lunaris_recipes::conversational::EmailThreading::new(lunaris_owned, scope_owned);
        Ok(Self { inner: Arc::new(inner) })
    }

    /// Ingest one email into `root_id`'s thread, authored by `from`.
    #[napi]
    pub async fn ingest(
        &self,
        root_id: String,
        from: String,
        body: String,
    ) -> napi::Result<String> {
        let out = self.inner.ingest(&root_id, &from, &body).await.map_err(napi_err)?;
        Ok(out.to_string())
    }

    /// Narrow to one thread `root_id`. Returns a new EmailThreading.
    #[napi]
    pub fn thread(&self, root_id: String) -> napi::Result<Self> {
        let out = self.inner.thread(&root_id);
        Ok(Self { inner: Arc::new(out) })
    }

    /// Recall across the current scope.
    #[napi]
    pub async fn recall(&self, query: String) -> napi::Result<Vec<serde_json::Value>> {
        let out = self.inner.recall(&query).await.map_err(napi_err)?;
        out.iter()
            .map(|v| serde_json::to_value(v).map_err(napi_err))
            .collect::<napi::Result<Vec<_>>>()
    }

    /// Opt-in the v0.1.0 graph pipeline (blueprint §5.2 graph-default-off preserved when enable=false).
    #[napi]
    pub fn with_graph_pipeline(&self, enable: bool) -> napi::Result<EmailThreading> {
        let out = self.inner.as_ref().clone().with_graph_pipeline(enable);
        Ok(EmailThreading { inner: Arc::new(out) })
    }
}

/// Meeting-notes wrapper with heading-scoped ingest and an opt-in graph-pipeline builder.
#[napi]
pub struct MeetingNotesMemory {
    #[allow(dead_code)]
    pub(crate) inner: Arc<::lunaris_recipes::conversational::MeetingNotesMemory>,
}

#[napi]
impl MeetingNotesMemory {
    /// Construct bound to `meeting:notes/`.
    #[napi(factory)]
    pub fn new(lunaris: &Lunaris, scope: String) -> napi::Result<Self> {
        let lunaris_owned: ::std::sync::Arc<::lunaris::Lunaris> = lunaris.inner.clone();
        let scope_owned: ::lunaris_core::scope::Scope = ::lunaris_core::scope::Scope::new(&scope)
            .map_err(|e| {
            crate::errors::napi_err_with_code("VALIDATE", format!("scope: {e}"))
        })?;
        let inner =
            ::lunaris_recipes::conversational::MeetingNotesMemory::new(lunaris_owned, scope_owned);
        Ok(Self { inner: Arc::new(inner) })
    }

    /// Record one note under `heading` (thread_id) with `body` content.
    #[napi]
    pub async fn note(&self, heading: String, body: String) -> napi::Result<String> {
        let out = self.inner.note(&heading, &body).await.map_err(napi_err)?;
        Ok(out.to_string())
    }

    /// Recall across the meeting corpus.
    #[napi]
    pub async fn recall(&self, query: String) -> napi::Result<Vec<serde_json::Value>> {
        let out = self.inner.recall(&query).await.map_err(napi_err)?;
        out.iter()
            .map(|v| serde_json::to_value(v).map_err(napi_err))
            .collect::<napi::Result<Vec<_>>>()
    }

    /// Narrow to notes attributed to `attendees`. Returns a MeetingNotesQuery.
    #[napi]
    pub fn attendees(&self, attendees: serde_json::Value) -> napi::Result<MeetingNotesQuery> {
        let attendees_owned: Vec<String> = from_js(attendees.clone()).map_err(napi_err)?;
        let out = self.inner.attendees(attendees_owned);
        Ok(MeetingNotesQuery { inner: Arc::new(out) })
    }

    /// Opt-in the v0.1.0 graph pipeline (blueprint §5.2).
    #[napi]
    pub fn with_graph_pipeline(&self, enable: bool) -> napi::Result<MeetingNotesMemory> {
        let out = self.inner.as_ref().clone().with_graph_pipeline(enable);
        Ok(MeetingNotesMemory { inner: Arc::new(out) })
    }
}

/// Narrowed query builder returned by MeetingNotesMemory::attendees.
#[napi]
pub struct MeetingNotesQuery {
    #[allow(dead_code)]
    pub(crate) inner: Arc<::lunaris_recipes::conversational::MeetingNotesQuery>,
}

#[napi]
impl MeetingNotesQuery {
    /// Execute the narrowed recall (per-attendee Filter::Eq And).
    #[napi]
    pub async fn recall(&self, query: String) -> napi::Result<Vec<serde_json::Value>> {
        let out = self.inner.recall(&query).await.map_err(napi_err)?;
        out.iter()
            .map(|v| serde_json::to_value(v).map_err(napi_err))
            .collect::<napi::Result<Vec<_>>>()
    }
}

/// Documentary knowledge-base wrapper. Owns a DocumentCorpus bound to a single `source_prefix`.
#[napi]
pub struct DocumentKnowledgeBase {
    #[allow(dead_code)]
    pub(crate) inner: Arc<::lunaris_recipes::documentary::DocumentKnowledgeBase>,
}

#[napi]
impl DocumentKnowledgeBase {
    /// Construct a knowledge base bound to `source_prefix`.
    #[napi(factory)]
    pub fn new(lunaris: &Lunaris, scope: String, source_prefix: String) -> napi::Result<Self> {
        let lunaris_owned: ::std::sync::Arc<::lunaris::Lunaris> = lunaris.inner.clone();
        let scope_owned: ::lunaris_core::scope::Scope = ::lunaris_core::scope::Scope::new(&scope)
            .map_err(|e| {
            crate::errors::napi_err_with_code("VALIDATE", format!("scope: {e}"))
        })?;
        let inner = ::lunaris_recipes::documentary::DocumentKnowledgeBase::new(
            lunaris_owned,
            scope_owned,
            &source_prefix,
        );
        Ok(Self { inner: Arc::new(inner) })
    }

    /// Ingest chunked `(content, metadata)` pairs.
    #[napi]
    pub async fn ingest(&self, chunks: serde_json::Value) -> napi::Result<()> {
        let chunks_owned: Vec<(String, serde_json::Map<String, serde_json::Value>)> =
            from_js(chunks.clone()).map_err(napi_err)?;
        self.inner.ingest(chunks_owned).await.map_err(napi_err)?;
        Ok(())
    }

    /// Add an equality filter on a metadata field.
    #[napi]
    pub fn filter(
        &self,
        field: String,
        value: serde_json::Value,
    ) -> napi::Result<DocumentKnowledgeBase> {
        let value_owned: serde_json::Value = from_js(value.clone()).map_err(napi_err)?;
        let out = self.inner.as_ref().clone().filter(&field, value_owned);
        Ok(DocumentKnowledgeBase { inner: Arc::new(out) })
    }

    /// Cap output at `k` hits.
    #[napi]
    pub fn top(&self, k: u32) -> napi::Result<DocumentKnowledgeBase> {
        let out = self.inner.as_ref().clone().top(k as usize);
        Ok(DocumentKnowledgeBase { inner: Arc::new(out) })
    }

    /// Execute the fused Vector + Keyword RRF recall.
    #[napi]
    pub async fn search(&self, query: String) -> napi::Result<Vec<serde_json::Value>> {
        let cloned = self.inner.as_ref().clone();
        let out = cloned.search(&query).await.map_err(napi_err)?;
        out.iter()
            .map(|v| serde_json::to_value(v).map_err(napi_err))
            .collect::<napi::Result<Vec<_>>>()
    }
}

/// Research-paper corpus wrapper with opt-in citation graph.
#[napi]
pub struct ResearchPaperCorpus {
    #[allow(dead_code)]
    pub(crate) inner: Arc<::lunaris_recipes::documentary::ResearchPaperCorpus>,
}

#[napi]
impl ResearchPaperCorpus {
    /// Construct bound to `source_prefix`.
    #[napi(factory)]
    pub fn new(lunaris: &Lunaris, scope: String, source_prefix: String) -> napi::Result<Self> {
        let lunaris_owned: ::std::sync::Arc<::lunaris::Lunaris> = lunaris.inner.clone();
        let scope_owned: ::lunaris_core::scope::Scope = ::lunaris_core::scope::Scope::new(&scope)
            .map_err(|e| {
            crate::errors::napi_err_with_code("VALIDATE", format!("scope: {e}"))
        })?;
        let inner = ::lunaris_recipes::documentary::ResearchPaperCorpus::new(
            lunaris_owned,
            scope_owned,
            &source_prefix,
        );
        Ok(Self { inner: Arc::new(inner) })
    }

    /// Opt-in the citation graph (blueprint §5.2 graph-default-off).
    #[napi]
    pub fn with_graph_pipeline(&self, on: bool) -> napi::Result<ResearchPaperCorpus> {
        let out = self.inner.as_ref().clone().with_graph_pipeline(on);
        Ok(ResearchPaperCorpus { inner: Arc::new(out) })
    }

    /// Ingest chunked `(content, metadata)` pairs.
    #[napi]
    pub async fn ingest(&self, chunks: serde_json::Value) -> napi::Result<()> {
        let chunks_owned: Vec<(String, serde_json::Map<String, serde_json::Value>)> =
            from_js(chunks.clone()).map_err(napi_err)?;
        self.inner.ingest(chunks_owned).await.map_err(napi_err)?;
        Ok(())
    }

    /// Execute the RRF-fused recall.
    #[napi]
    pub async fn search(&self, query: String) -> napi::Result<Vec<serde_json::Value>> {
        let cloned = self.inner.as_ref().clone();
        let out = cloned.search(&query).await.map_err(napi_err)?;
        out.iter()
            .map(|v| serde_json::to_value(v).map_err(napi_err))
            .collect::<napi::Result<Vec<_>>>()
    }
}

/// Code-repository memory wrapper. Stores commit SHA in Episode metadata and recalls point-in-time function bodies.
#[napi]
pub struct CodeRepoMemory {
    #[allow(dead_code)]
    pub(crate) inner: Arc<::lunaris_recipes::documentary::CodeRepoMemory>,
}

#[napi]
impl CodeRepoMemory {
    /// Construct bound to `repo_prefix`.
    #[napi(factory)]
    pub fn new(lunaris: &Lunaris, scope: String, repo_prefix: String) -> napi::Result<Self> {
        let lunaris_owned: ::std::sync::Arc<::lunaris::Lunaris> = lunaris.inner.clone();
        let scope_owned: ::lunaris_core::scope::Scope = ::lunaris_core::scope::Scope::new(&scope)
            .map_err(|e| {
            crate::errors::napi_err_with_code("VALIDATE", format!("scope: {e}"))
        })?;
        let inner = ::lunaris_recipes::documentary::CodeRepoMemory::new(
            lunaris_owned,
            scope_owned,
            &repo_prefix,
        );
        Ok(Self { inner: Arc::new(inner) })
    }

    /// Ingest one commit as a batch of `(function_body, metadata)` chunks.
    #[napi]
    pub async fn ingest_commit(
        &self,
        commit_sha: String,
        committer_date_unix_ms: serde_json::Value,
        chunks: serde_json::Value,
    ) -> napi::Result<()> {
        let committer_date_unix_ms_owned: i64 =
            from_js(committer_date_unix_ms.clone()).map_err(napi_err)?;
        let chunks_owned: Vec<(String, serde_json::Map<String, serde_json::Value>)> =
            from_js(chunks.clone()).map_err(napi_err)?;
        self.inner
            .ingest_commit(&commit_sha, committer_date_unix_ms_owned, chunks_owned)
            .await
            .map_err(napi_err)?;
        Ok(())
    }

    /// Recall at point-in-time `as_of`.
    #[napi]
    pub async fn recall(
        &self,
        query: String,
        as_of: serde_json::Value,
    ) -> napi::Result<Vec<serde_json::Value>> {
        let as_of_owned: ::lunaris::Hlc = from_js(as_of.clone()).map_err(napi_err)?;
        let out = self.inner.recall(&query, as_of_owned).await.map_err(napi_err)?;
        out.iter()
            .map(|v| serde_json::to_value(v).map_err(napi_err))
            .collect::<napi::Result<Vec<_>>>()
    }
}

/// Timeline-reconstruction wrapper. Two-call composition of DocumentCorpus + TemporalQuery<Documents>.
#[napi]
pub struct TimelineReconstruction {
    #[allow(dead_code)]
    pub(crate) inner: Arc<::lunaris_recipes::documentary::TimelineReconstruction>,
}

#[napi]
impl TimelineReconstruction {
    /// Construct bound to `source_prefix`.
    #[napi(factory)]
    pub fn new(lunaris: &Lunaris, scope: String, source_prefix: String) -> napi::Result<Self> {
        let lunaris_owned: ::std::sync::Arc<::lunaris::Lunaris> = lunaris.inner.clone();
        let scope_owned: ::lunaris_core::scope::Scope = ::lunaris_core::scope::Scope::new(&scope)
            .map_err(|e| {
            crate::errors::napi_err_with_code("VALIDATE", format!("scope: {e}"))
        })?;
        let inner = ::lunaris_recipes::documentary::TimelineReconstruction::new(
            lunaris_owned,
            scope_owned,
            &source_prefix,
        );
        Ok(Self { inner: Arc::new(inner) })
    }

    /// Ingest timeline events as chunked `(content, metadata)` pairs.
    #[napi]
    pub async fn ingest(&self, events: serde_json::Value) -> napi::Result<()> {
        let events_owned: Vec<(String, serde_json::Map<String, serde_json::Value>)> =
            from_js(events.clone()).map_err(napi_err)?;
        self.inner.ingest(events_owned).await.map_err(napi_err)?;
        Ok(())
    }

    /// Recall all events in `[lo, hi)` — lower-inclusive, upper-exclusive (11-01 boundary semantics).
    #[napi]
    pub async fn between(
        &self,
        query: String,
        lo: serde_json::Value,
        hi: serde_json::Value,
    ) -> napi::Result<Vec<serde_json::Value>> {
        let lo_owned: ::lunaris::Hlc = from_js(lo.clone()).map_err(napi_err)?;
        let hi_owned: ::lunaris::Hlc = from_js(hi.clone()).map_err(napi_err)?;
        let out = self.inner.between(&query, lo_owned, hi_owned).await.map_err(napi_err)?;
        out.iter()
            .map(|v| serde_json::to_value(v).map_err(napi_err))
            .collect::<napi::Result<Vec<_>>>()
    }

    /// Recall the snapshot at `ts`.
    #[napi]
    pub async fn as_of(
        &self,
        query: String,
        ts: serde_json::Value,
    ) -> napi::Result<Vec<serde_json::Value>> {
        let ts_owned: ::lunaris::Hlc = from_js(ts.clone()).map_err(napi_err)?;
        let out = self.inner.as_of(&query, ts_owned).await.map_err(napi_err)?;
        out.iter()
            .map(|v| serde_json::to_value(v).map_err(napi_err))
            .collect::<napi::Result<Vec<_>>>()
    }
}

/// Customer-support history wrapper. Owns both a tickets DocumentCorpus and a chats MessageStream.
#[napi]
pub struct CustomerSupportHistory {
    #[allow(dead_code)]
    pub(crate) inner: Arc<::lunaris_recipes::documentary::CustomerSupportHistory>,
}

#[napi]
impl CustomerSupportHistory {
    /// Construct with hard-coded source prefixes `ticket:` and `chat:`.
    #[napi(factory)]
    pub fn new(lunaris: &Lunaris, scope: String) -> napi::Result<Self> {
        let lunaris_owned: ::std::sync::Arc<::lunaris::Lunaris> = lunaris.inner.clone();
        let scope_owned: ::lunaris_core::scope::Scope = ::lunaris_core::scope::Scope::new(&scope)
            .map_err(|e| {
            crate::errors::napi_err_with_code("VALIDATE", format!("scope: {e}"))
        })?;
        let inner =
            ::lunaris_recipes::documentary::CustomerSupportHistory::new(lunaris_owned, scope_owned);
        Ok(Self { inner: Arc::new(inner) })
    }

    /// Opt-in the product/customer relationship graph (blueprint §5.2).
    #[napi]
    pub fn with_graph_pipeline(&self, on: bool) -> napi::Result<CustomerSupportHistory> {
        let out = self.inner.as_ref().clone().with_graph_pipeline(on);
        Ok(CustomerSupportHistory { inner: Arc::new(out) })
    }

    /// Ingest one ticket body. `ticket_id` is stamped into metadata.
    #[napi]
    pub async fn ingest_ticket(&self, ticket_id: String, body: String) -> napi::Result<()> {
        self.inner.ingest_ticket(&ticket_id, &body).await.map_err(napi_err)?;
        Ok(())
    }

    /// Ingest one chat-turn. `ticket_id/turn_idx` slug lands in the MessageStream thread_id.
    #[napi]
    pub async fn ingest_chat(
        &self,
        ticket_id: String,
        turn_idx: u32,
        participant: String,
        msg: String,
    ) -> napi::Result<String> {
        let out = self
            .inner
            .ingest_chat(&ticket_id, turn_idx as usize, &participant, &msg)
            .await
            .map_err(napi_err)?;
        Ok(out.to_string())
    }

    /// Recall from both buckets; RRF fusion happens within each primitive's own bucket.
    #[napi]
    pub async fn recall(&self, query: String) -> napi::Result<Vec<serde_json::Value>> {
        let out = self.inner.recall(&query).await.map_err(napi_err)?;
        out.iter()
            .map(|v| serde_json::to_value(v).map_err(napi_err))
            .collect::<napi::Result<Vec<_>>>()
    }
}
