// @generated by lunaris-codegen — do not edit
//
// Phase 8 Plan 08-01 (BIND-GEN-01..03). napi-rs 3.x wrapper surface emitted
// from `crates/lunaris-codegen/annotations/surface.toml`. Regenerate with
// `cargo run -p lunaris-codegen -- --emit ts`.

use napi_derive::napi;
use std::sync::Arc;

use super::errors::napi_err;

/// High-level memory-engine handle. Opens a storage backend by URL and drives ingest, recall, forget, and snapshot.
#[napi]
pub struct Lunaris {
    #[allow(dead_code)]
    pub(crate) inner: Arc<::lunaris::Lunaris>,
}

#[napi]
impl Lunaris {
    /// Production constructor. Routes `url` through the scheme dispatcher to pick a StoragePort backend.
    #[napi(factory)]
    pub async fn open(url: String) -> napi::Result<Self> {
        let inner = ::lunaris::Lunaris::open(&url).await.map_err(napi_err)?;
        Ok(Self { inner: Arc::new(inner) })
    }

    /// Ingest one Episode through the hot path (graph-OFF default) or the graph-extraction path (toggle ON).
    #[napi]
    pub async fn ingest(&self, episode: serde_json::Value) -> napi::Result<String> {
        let episode_owned: ::lunaris::Episode = serde_json::from_value(episode.clone()).map_err(napi_err)?;
        let out = self.inner.ingest(episode_owned).await.map_err(napi_err)?;
        Ok(out.to_string())
    }

    /// Build a RetrievalBuilder bound to this handle's storage / keyword / embedder / clock.
    #[napi]
    pub fn recall(&self) -> napi::Result<RetrievalBuilder> {
        let out = self.inner.recall();
        Ok(RetrievalBuilder { inner: Arc::new(out) })
    }

    /// Single-entry-point erasure API (OPS-01/02/03/04). Soft-delete default; hard mode requires a confirmation token.
    #[napi]
    pub async fn forget(&self, req: serde_json::Value) -> napi::Result<serde_json::Value> {
        let req_owned: ::lunaris::forget::ForgetRequest = serde_json::from_value(req.clone()).map_err(napi_err)?;
        let out = self.inner.forget(req_owned).await.map_err(napi_err)?;
        Ok(serde_json::to_value(&out).map_err(napi_err)?)
    }

    /// Returns the current monotonic LSN — a cheap consistent snapshot marker. Implemented as no-op atomic_write(&[]).
    #[napi]
    pub async fn snapshot(&self) -> napi::Result<String> {
        let out = self.inner.snapshot().await.map_err(napi_err)?;
        Ok(out.to_string())
    }

}

/// Vector-search DSL operator; root-level constructor for kNN retrieval.
#[napi]
pub struct Vector {
    #[allow(dead_code)]
    pub(crate) inner: Arc<::lunaris::Vector>,
}

#[napi]
impl Vector {
    /// Construct a Vector retriever over `index` with top-k fan-out.
    #[napi(factory)]
    pub fn new(index: String, k: u32) -> Self {
        let inner = ::lunaris::Vector::new(&index, k as usize);
        Self { inner: Arc::new(inner) }
    }

}

/// Keyword / BM25 DSL operator; root-level constructor for lexical retrieval.
#[napi]
pub struct Keyword {
    #[allow(dead_code)]
    pub(crate) inner: Arc<::lunaris::Keyword>,
}

#[napi]
impl Keyword {
    /// Construct a BM25 keyword retriever over `index` with top-k fan-out.
    #[napi(factory)]
    pub fn bm25(index: String, k: u32) -> Self {
        let inner = ::lunaris::Keyword::bm25(&index, k as usize);
        Self { inner: Arc::new(inner) }
    }

}

/// Graph-traversal DSL operator; anchors on a set of entity ids and expands N hops.
#[napi]
pub struct Graph {
    #[allow(dead_code)]
    pub(crate) inner: Arc<::lunaris::Graph>,
}

#[napi]
impl Graph {
    /// Anchor on `entity_ids` and traverse up to `hops` edges out in the Lunaris graph.
    #[napi(factory)]
    pub fn anchored(entity_ids: Vec<serde_json::Value>, hops: u32) -> Self {
        let entity_ids_owned: Vec<::lunaris::EntityId> = serde_json::from_value(serde_json::Value::Array(entity_ids.clone())).unwrap_or_else(|e| panic!("entity_ids: {e}"));
        let inner = ::lunaris::Graph::anchored(entity_ids_owned, hops as usize);
        Self { inner: Arc::new(inner) }
    }

}

/// Chainable retrieval plan builder. Terminal .execute() runs the plan through the hydrate stage.
#[napi]
pub struct RetrievalBuilder {
    #[allow(dead_code)]
    pub(crate) inner: Arc<::lunaris::RetrievalBuilder>,
}

#[napi]
impl RetrievalBuilder {
    /// Compose `other` in parallel with the current plan; unions the result set.
    #[napi]
    pub fn and(&self, other: serde_json::Value) -> napi::Result<RetrievalBuilder> {
        // Owned-self builder methods return a new wrapper; Plan 08-03 wires the body.
        let _ = (other);
        Err(napi::Error::from_reason("Plan 08-03 wires the body"))
    }

    /// Fuse two parallel branches via reciprocal-rank fusion (client-side or Moon-native depending on capabilities).
    #[napi]
    pub fn fuse_rrf(&self, k: u32) -> napi::Result<RetrievalBuilder> {
        // Owned-self builder methods return a new wrapper; Plan 08-03 wires the body.
        let _ = (k);
        Err(napi::Error::from_reason("Plan 08-03 wires the body"))
    }

    /// Keep only the top `n` hits after fusion.
    #[napi]
    pub fn top(&self, n: u32) -> napi::Result<RetrievalBuilder> {
        // Owned-self builder methods return a new wrapper; Plan 08-03 wires the body.
        let _ = (n);
        Err(napi::Error::from_reason("Plan 08-03 wires the body"))
    }

    /// Attach a filter predicate (parsed via filter_str) to the query; fails on a malformed predicate string.
    #[napi]
    pub fn filter(&self, pred: String) -> napi::Result<RetrievalBuilder> {
        // Owned-self builder methods return a new wrapper; Plan 08-03 wires the body.
        let _ = (&pred);
        Err(napi::Error::from_reason("Plan 08-03 wires the body"))
    }

    /// Pin the query to an as-of-HLC time-travel view (SQL:2011 bi-temporal read).
    #[napi]
    pub fn as_of(&self, hlc: serde_json::Value) -> napi::Result<RetrievalBuilder> {
        // Owned-self builder methods return a new wrapper; Plan 08-03 wires the body.
        let _ = (hlc);
        Err(napi::Error::from_reason("Plan 08-03 wires the body"))
    }

}

/// Runtime toggle for the graph-extraction pipeline (default OFF per blueprint §5.2). The toggle method is the canonical single-item entry in the binding surface.
#[napi]
pub struct GraphPipelineHandle {
    #[allow(dead_code)]
    pub(crate) inner: Arc<::lunaris::GraphPipelineHandle>,
}

#[napi]
impl GraphPipelineHandle {
    /// Flip the pipeline ON or OFF. Idempotent. Emits `tracing::info!` only on real state transitions (D-12).
    #[napi]
    pub fn toggle(&self, on: bool) -> napi::Result<()> {
        if on { self.inner.enable(); } else { self.inner.disable(); }
        Ok(())
    }

}

/// Runtime toggle for the ACT-R consolidator worker (default OFF per blueprint §5.1). Mirrors GraphPipelineHandle's single-item toggle surface.
#[napi]
pub struct ConsolidatorPipelineHandle {
    #[allow(dead_code)]
    pub(crate) inner: Arc<::lunaris::ConsolidatorPipelineHandle>,
}

#[napi]
impl ConsolidatorPipelineHandle {
    /// Flip the pipeline ON or OFF. Idempotent. Emits `tracing::info!` only on real state transitions (D-12).
    #[napi]
    pub fn toggle(&self, on: bool) -> napi::Result<()> {
        if on { self.inner.enable(); } else { self.inner.disable(); }
        Ok(())
    }

}

