//! napi-rs 3.x emitter.
//!
//! Converts a [`SurfaceIR`] into the two artefacts Plan 08-03 will land at
//! `crates/lunaris-ts/src/generated.rs` + `crates/lunaris-ts/generated.d.ts`
//! (Wave 3 host crate doesn't exist yet — Plan 08-01 commits the snapshots
//! at `crates/lunaris-codegen/snapshots/generated_ts.{rs,d.ts}` per revision
//! 2).
//!
//! napi-rs 3.x handles the `Promise<T>` conversion for async fns natively;
//! the emitter simply marks async methods with `#[napi]` and returns
//! `napi::Result<T>`. The `.d.ts` side mirrors the class / async shape.

use std::fmt::Write as _;

use crate::ir::{IrAsync, IrKind, IrMethod, IrParam, IrReceiver, IrTyRef, IrType, SurfaceIR};

const RUST_HEADER: &str = "\
// @generated by lunaris-codegen — do not edit
//
// Phase 8 Plan 08-01 (BIND-GEN-01..03). napi-rs 3.x wrapper surface emitted
// from `crates/lunaris-codegen/annotations/surface.toml`. Regenerate with
// `cargo run -p lunaris-codegen -- --emit ts`.
";

const DTS_HEADER: &str = "\
// @generated by lunaris-codegen — do not edit
//
// Phase 8 Plan 08-01 (BIND-GEN-01..03). TypeScript declarations mirroring
// the napi-rs bindings. Regenerate with
// `cargo run -p lunaris-codegen -- --emit ts`.
";

/// Paired emitter output: Rust glue (lands at `src/generated.rs`) plus the
/// `.d.ts` declarations (lands at `generated.d.ts` alongside the built
/// `.node` binary).
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct TsOutput {
    pub rust_glue: String,
    pub dts: String,
}

/// Emit napi-rs glue + matching `.d.ts` for the given [`SurfaceIR`].
pub fn emit_ts(ir: &SurfaceIR) -> TsOutput {
    let mut rust = String::new();
    let mut dts = String::new();
    rust.push_str(RUST_HEADER);
    rust.push('\n');
    rust.push_str("use napi_derive::napi;\n");
    rust.push_str("use std::sync::Arc;\n\n");

    dts.push_str(DTS_HEADER);
    dts.push('\n');

    for module in &ir.modules {
        for ty in &module.types {
            emit_ts_type_rust(&mut rust, ty);
            emit_ts_type_dts(&mut dts, ty);
        }
    }
    TsOutput { rust_glue: rust, dts }
}

fn emit_ts_type_rust(out: &mut String, ty: &IrType) {
    if let Some(doc) = &ty.doc {
        writeln!(out, "/// {doc}").unwrap();
    }
    writeln!(
        out,
        "#[napi]\npub struct {name} {{\n    #[allow(dead_code)]\n    pub(crate) inner: Arc<::lunaris::{name}>,\n}}",
        name = ty.name
    )
    .unwrap();
    out.push('\n');
    writeln!(out, "#[napi]\nimpl {name} {{", name = ty.name).unwrap();
    for m in &ty.methods {
        emit_ts_method_rust(out, &ty.name, m, ty.kind.clone());
    }
    writeln!(out, "}}\n").unwrap();
}

fn emit_ts_method_rust(out: &mut String, type_name: &str, m: &IrMethod, _kind: IrKind) {
    if let Some(doc) = &m.doc {
        writeln!(out, "    /// {doc}").unwrap();
    }
    match (m.is_async, m.receiver) {
        (IrAsync::Yes, IrReceiver::None) => {
            writeln!(out, "    #[napi(factory)]").unwrap();
            writeln!(
                out,
                "    pub async fn {name}({params}) -> napi::Result<Self> {{",
                name = m.name,
                params = format_params_rust(&m.params, /* with_self */ false)
            )
            .unwrap();
            writeln!(
                out,
                "        let inner = ::lunaris::{type_name}::{name}({call_args}).await.map_err(napi_err)?;",
                type_name = type_name,
                name = m.name,
                call_args = format_call_args(&m.params)
            )
            .unwrap();
            writeln!(out, "        Ok(Self {{ inner: Arc::new(inner) }})").unwrap();
            writeln!(out, "    }}").unwrap();
        }
        (IrAsync::Yes, IrReceiver::RefSelf) => {
            writeln!(out, "    #[napi]").unwrap();
            writeln!(
                out,
                "    pub async fn {name}(&self{params}) -> napi::Result<{ret}> {{",
                name = m.name,
                params = format_params_rust(&m.params, /* with_self */ true),
                ret = ts_return_ty_rust(&m.returns.ty)
            )
            .unwrap();
            writeln!(
                out,
                "        let out = self.inner.{name}({call_args}).await.map_err(napi_err)?;",
                name = m.name,
                call_args = format_call_args(&m.params)
            )
            .unwrap();
            writeln!(out, "        {ret}", ret = ts_return_expr_rust(&m.returns.ty)).unwrap();
            writeln!(out, "    }}").unwrap();
        }
        (IrAsync::No, IrReceiver::None) => {
            writeln!(out, "    #[napi(factory)]").unwrap();
            writeln!(
                out,
                "    pub fn {name}({params}) -> Self {{",
                name = m.name,
                params = format_params_rust(&m.params, /* with_self */ false)
            )
            .unwrap();
            writeln!(
                out,
                "        let inner = ::lunaris::{type_name}::{name}({call_args});",
                type_name = type_name,
                name = m.name,
                call_args = format_call_args(&m.params)
            )
            .unwrap();
            writeln!(out, "        Self {{ inner: Arc::new(inner) }}").unwrap();
            writeln!(out, "    }}").unwrap();
        }
        (IrAsync::No, IrReceiver::RefSelf) => {
            writeln!(out, "    #[napi]").unwrap();
            writeln!(
                out,
                "    pub fn {name}(&self{params}) -> napi::Result<{ret}> {{",
                name = m.name,
                params = format_params_rust(&m.params, /* with_self */ true),
                ret = ts_return_ty_rust(&m.returns.ty)
            )
            .unwrap();
            writeln!(
                out,
                "        let out = self.inner.{name}({call_args});",
                name = m.name,
                call_args = format_call_args(&m.params)
            )
            .unwrap();
            writeln!(out, "        {ret}", ret = ts_sync_return_expr_rust(&m.returns.ty)).unwrap();
            writeln!(out, "    }}").unwrap();
        }
        (IrAsync::No, IrReceiver::Owned) => {
            writeln!(out, "    #[napi]").unwrap();
            writeln!(
                out,
                "    pub fn {name}(&self{params}) -> napi::Result<{type_name}> {{",
                name = m.name,
                params = format_params_rust(&m.params, /* with_self */ true),
                type_name = type_name
            )
            .unwrap();
            writeln!(
                out,
                "        // Owned-self builder methods return a new wrapper; Plan 08-03 wires the body."
            )
            .unwrap();
            writeln!(out, "        let _ = ({unused});", unused = format_call_args(&m.params))
                .unwrap();
            writeln!(out, "        Err(napi::Error::from_reason(\"Plan 08-03 wires the body\"))")
                .unwrap();
            writeln!(out, "    }}").unwrap();
        }
        _ => {
            writeln!(
                out,
                "    // TODO: unsupported receiver/async combination for {}::{} — emitter stub.",
                type_name, m.name
            )
            .unwrap();
        }
    }
    out.push('\n');
}

fn emit_ts_type_dts(out: &mut String, ty: &IrType) {
    if let Some(doc) = &ty.doc {
        writeln!(out, "/** {doc} */").unwrap();
    }
    writeln!(out, "export class {} {{", ty.name).unwrap();
    for m in &ty.methods {
        emit_ts_method_dts(out, m);
    }
    writeln!(out, "}}\n").unwrap();
}

fn emit_ts_method_dts(out: &mut String, m: &IrMethod) {
    if let Some(doc) = &m.doc {
        writeln!(out, "  /** {doc} */").unwrap();
    }
    let is_static = matches!(m.receiver, IrReceiver::None);
    let prefix = if is_static { "  static " } else { "  " };
    let params = m
        .params
        .iter()
        .map(|p| format!("{}: {}", p.name, ts_param_ty_dts(&p.ty)))
        .collect::<Vec<_>>()
        .join(", ");
    let ret = match (&m.is_async, &m.returns.ty) {
        (IrAsync::Yes, _) => format!("Promise<{}>", ts_return_ty_dts(&m.returns.ty)),
        (IrAsync::No, ty) => ts_return_ty_dts(ty),
    };
    writeln!(out, "{prefix}{name}({params}): {ret};", name = m.name).unwrap();
}

fn format_params_rust(params: &[IrParam], _with_self: bool) -> String {
    let mut s = String::new();
    for p in params {
        s.push_str(", ");
        s.push_str(&p.name);
        s.push_str(": ");
        s.push_str(ts_param_ty_rust(&p.ty));
    }
    // If `_with_self` is false (static), trim the leading ", " — napi-rs
    // factory functions don't take `&self` but do take leading parameters.
    if !_with_self && s.starts_with(", ") {
        s = s[2..].to_string();
    }
    s
}

fn format_call_args(params: &[IrParam]) -> String {
    params
        .iter()
        .map(|p| match &p.ty {
            IrTyRef::Str => format!("&{}", p.name),
            IrTyRef::Json => {
                format!("serde_json::from_value({}.clone()).map_err(napi_err)?", p.name)
            }
            _ => p.name.clone(),
        })
        .collect::<Vec<_>>()
        .join(", ")
}

fn ts_param_ty_rust(ty: &IrTyRef) -> &'static str {
    match ty {
        IrTyRef::Unit => "()",
        IrTyRef::Str => "String",
        IrTyRef::Usize => "u32",
        IrTyRef::Bool => "bool",
        IrTyRef::Json => "serde_json::Value",
        IrTyRef::RefSelf => "&Self",
        IrTyRef::Named { .. } => "serde_json::Value",
        IrTyRef::Option { .. } => "Option<serde_json::Value>",
        IrTyRef::Vec { .. } => "Vec<serde_json::Value>",
    }
}

fn ts_param_ty_dts(ty: &IrTyRef) -> String {
    match ty {
        IrTyRef::Unit => "void".into(),
        IrTyRef::Str => "string".into(),
        IrTyRef::Usize => "number".into(),
        IrTyRef::Bool => "boolean".into(),
        IrTyRef::Json => "object".into(),
        IrTyRef::RefSelf => "this".into(),
        IrTyRef::Named { name } => name.clone(),
        IrTyRef::Option { inner } => format!("{} | null", ts_param_ty_dts(inner)),
        IrTyRef::Vec { inner } => format!("Array<{}>", ts_param_ty_dts(inner)),
    }
}

fn ts_return_ty_rust(ty: &IrTyRef) -> String {
    match ty {
        IrTyRef::Unit => "()".into(),
        IrTyRef::Named { name } if name == "Lsn" => "String".into(),
        IrTyRef::Named { .. } => "serde_json::Value".into(),
        IrTyRef::RefSelf => "Self".into(),
        _ => ts_param_ty_rust(ty).to_string(),
    }
}

fn ts_return_expr_rust(ty: &IrTyRef) -> String {
    match ty {
        IrTyRef::Unit => "let _ = out; Ok(())".into(),
        IrTyRef::Named { name } if name == "Lsn" => "Ok(out.to_string())".into(),
        _ => "Ok(serde_json::to_value(&out).map_err(napi_err)?)".into(),
    }
}

fn ts_sync_return_expr_rust(ty: &IrTyRef) -> String {
    match ty {
        IrTyRef::Unit => "let _ = out; Ok(())".into(),
        _ => "Ok(serde_json::to_value(&out).map_err(napi_err)?)".into(),
    }
}

fn ts_return_ty_dts(ty: &IrTyRef) -> String {
    match ty {
        IrTyRef::Unit => "void".into(),
        IrTyRef::Named { name } if name == "Lsn" => "string".into(),
        IrTyRef::Named { name } => name.clone(),
        IrTyRef::RefSelf => "this".into(),
        IrTyRef::Str => "string".into(),
        IrTyRef::Usize => "number".into(),
        IrTyRef::Bool => "boolean".into(),
        IrTyRef::Json => "object".into(),
        IrTyRef::Option { inner } => format!("{} | null", ts_return_ty_dts(inner)),
        IrTyRef::Vec { inner } => format!("Array<{}>", ts_return_ty_dts(inner)),
    }
}
