//! PyO3 0.26 emitter.
//!
//! Converts a [`SurfaceIR`] into a Rust source string that Plan 08-02 will
//! land at `crates/lunaris-py/src/generated.rs` (Wave 2 host crate doesn't
//! exist yet — Plan 08-01 commits the snapshot at
//! `crates/lunaris-codegen/snapshots/generated_py.rs` per revision 2).
//!
//! ## GIL discipline (CLAUDE.md)
//!
//! Every async Rust method maps to a wrapper that uses
//! `pyo3_async_runtimes::tokio::future_into_py`. The emitter places EVERY
//! `.await` inside the `future_into_py` closure — `tests/emitter_shape.rs`
//! grep-asserts the invariant (`py_emits_future_into_py`).
//!
//! ## Emission shape per type kind
//!
//! - `Opaque` → `#[pyclass(name = "...", unsendable)]` struct with
//!   `std::sync::Arc<::lunaris::Inner>`, `#[pymethods]` impl block.
//! - `Builder` → same shape, but builder-mutator methods are emitted as
//!   `#[pymethods]` that return `PyResult<Self>` (owned-self consuming).
//! - `Value` → pass-through JSON helper (not exercised in v0.1.1).
//!
//! ## Determinism
//!
//! The emitter iterates modules / types / methods in the order provided by
//! the IR. Given identical input the output is byte-identical — asserted by
//! the emit-determinism test.

use std::fmt::Write as _;

use crate::ir::{IrAsync, IrKind, IrMethod, IrParam, IrReceiver, IrTyRef, IrType, SurfaceIR};

const GENERATED_HEADER: &str = "\
// @generated by lunaris-codegen — do not edit
//
// Phase 8 Plan 08-01 (BIND-GEN-01..03). PyO3 0.26 wrapper surface emitted
// from `crates/lunaris-codegen/annotations/surface.toml`. Regenerate with
// `cargo run -p lunaris-codegen -- --emit py`.
//
// CLAUDE.md invariant: every `.await` in this file is wrapped in
// `pyo3_async_runtimes::tokio::future_into_py` — the GIL is released across
// every async boundary. The parity-check CI job
// (`.github/workflows/ci.yml::parity-check`) fails the PR on any drift from
// this snapshot.
";

/// Plan 11-02a D1(c) — legacy-mode detector. Returns `true` iff the IR is
/// the revision-1 single-`lunaris`-module shape with no per-module
/// `rust_crate_path` override. In that case the emitter produces the
/// byte-identical `register_generated` fn the committed snapshot pins;
/// otherwise the emitter switches to one `register_generated_{sanitized}`
/// fn per module (consumed by Plan 11-02b's host `lib.rs` rewiring).
fn is_legacy_single_module(ir: &SurfaceIR) -> bool {
    ir.modules.len() == 1
        && ir.modules[0].name == "lunaris"
        && ir.modules[0].rust_crate_path.is_none()
}

/// Sanitise a dotted module name into an identifier fragment — replaces
/// `.` with `_` so `lunaris_recipes.conversational` becomes
/// `lunaris_recipes_conversational`.
fn sanitize_module_name(name: &str) -> String {
    name.replace('.', "_")
}

/// Emit PyO3 wrapper code for the given [`SurfaceIR`].
pub fn emit_py(ir: &SurfaceIR) -> String {
    let mut out = String::new();
    out.push_str(GENERATED_HEADER);
    out.push('\n');
    out.push_str("use pyo3::prelude::*;\n");
    out.push_str("use pyo3::types::PyModule;\n");
    out.push_str("use std::sync::Arc;\n\n");

    let legacy = is_legacy_single_module(ir);
    for module in &ir.modules {
        let crate_path = module.rust_crate_path.as_deref().unwrap_or("::lunaris");
        for ty in &module.types {
            emit_py_type(&mut out, ty, crate_path);
        }
        if legacy {
            // Plan 08-02 Rule 1 deviation: emit `pub fn register_generated` instead
            // of a `#[pymodule] fn {module}` so the host crate's `src/lib.rs` can
            // `include!("generated.rs")` without colliding on the `PyInit_lunaris`
            // C-exported symbol. The host crate owns the canonical `#[pymodule]`
            // and calls `register_generated(py, m)?` from its body. `module.name`
            // is preserved in the doc comment for traceability.
            writeln!(
                out,
                "/// Registers every generated `#[pyclass]` on the host crate's `#[pymodule] fn {}`.",
                module.name
            )
            .unwrap();
            writeln!(
                out,
                "pub(crate) fn register_generated(_py: Python<'_>, m: &Bound<'_, PyModule>) -> PyResult<()> {{"
            )
            .unwrap();
            for ty in &module.types {
                writeln!(out, "    m.add_class::<Py{}>()?;", ty.name).unwrap();
            }
            writeln!(out, "    Ok(())\n}}").unwrap();
        } else {
            // Plan 11-02a D1(c) — per-module `register_generated_{suffix}`
            // scheme. Host `lib.rs` (Plan 11-02b) wires each fn against a
            // `PyModule::new_bound(py, "{module}")` submodule. Multiple
            // modules land side-by-side in this same generated file.
            let suffix = sanitize_module_name(&module.name);
            writeln!(
                out,
                "/// Registers every generated `#[pyclass]` for module `{}`.",
                module.name
            )
            .unwrap();
            writeln!(
                out,
                "pub(crate) fn register_generated_{suffix}(_py: Python<'_>, m: &Bound<'_, PyModule>) -> PyResult<()> {{"
            )
            .unwrap();
            for ty in &module.types {
                writeln!(out, "    m.add_class::<Py{}>()?;", ty.name).unwrap();
            }
            writeln!(out, "    Ok(())\n}}").unwrap();
        }
    }
    out
}

fn emit_py_type(out: &mut String, ty: &IrType, crate_path: &str) {
    if let Some(doc) = &ty.doc {
        writeln!(out, "/// {doc}").unwrap();
    }
    writeln!(
        out,
        "#[pyclass(name = \"{name}\", unsendable)]\npub struct Py{name} {{\n    #[allow(dead_code)]\n    pub(crate) inner: Arc<{crate_path}::{name}>,\n}}",
        name = ty.name,
        crate_path = crate_path
    )
    .unwrap();
    out.push('\n');
    writeln!(out, "#[pymethods]\nimpl Py{name} {{", name = ty.name).unwrap();
    for m in &ty.methods {
        emit_py_method(out, &ty.name, m, ty.kind.clone(), crate_path);
    }
    writeln!(out, "}}\n").unwrap();
}

fn emit_py_method(
    out: &mut String,
    type_name: &str,
    m: &IrMethod,
    _kind: IrKind,
    crate_path: &str,
) {
    if let Some(doc) = &m.doc {
        writeln!(out, "    /// {doc}").unwrap();
    }
    match (m.is_async, m.receiver) {
        // Static async constructor (e.g. `Lunaris::open`).
        (IrAsync::Yes, IrReceiver::None) => {
            writeln!(out, "    #[staticmethod]").unwrap();
            writeln!(
                out,
                "    fn {name}<'py>(py: Python<'py>{params}) -> PyResult<Bound<'py, PyAny>> {{",
                name = m.name,
                params = format_params(&m.params, /* leading_comma */ true)
            )
            .unwrap();
            writeln!(out, "        pyo3_async_runtimes::tokio::future_into_py(py, async move {{")
                .unwrap();
            writeln!(
                out,
                "            let inner = {crate_path}::{type_name}::{name}({call_args}).await.map_err(py_err)?;",
                crate_path = crate_path,
                type_name = type_name,
                name = m.name,
                call_args = format_call_args(&m.params)
            )
            .unwrap();
            writeln!(out, "            Ok(Py{type_name} {{ inner: Arc::new(inner) }})").unwrap();
            writeln!(out, "        }})").unwrap();
            writeln!(out, "    }}").unwrap();
        }
        // Async instance method (e.g. `Lunaris::ingest`, `Lunaris::snapshot`,
        // `Lunaris::forget`).
        //
        // Plan 08-02 Rule 1 fix — Send-safety: `pythonize::depythonize(&py_any)`
        // borrows a `&Bound<'_, PyAny>` which is `!Send`. Capturing such a
        // borrow inside the `async move { ... .await ... }` block sent to the
        // tokio runtime makes the future non-Send and fails to compile. Fix
        // is to eagerly run `depythonize` (with GIL still held, BEFORE the
        // async block) and move the owned typed value into the closure.
        (IrAsync::Yes, IrReceiver::RefSelf) => {
            writeln!(
                out,
                "    fn {name}<'py>(&self, py: Python<'py>{params}) -> PyResult<Bound<'py, PyAny>> {{",
                name = m.name,
                params = format_params(&m.params, /* leading_comma */ true)
            )
            .unwrap();
            writeln!(out, "        let inner = self.inner.clone();").unwrap();
            // Eager pythonize::depythonize for every Json / Named / Vec /
            // Option param so the future body can move the owned value.
            let mut owned_names: Vec<String> = Vec::with_capacity(m.params.len());
            for p in &m.params {
                let owned_name = format!("{}_owned", p.name);
                match &p.ty {
                    IrTyRef::Json | IrTyRef::Named { .. } | IrTyRef::Option { .. } | IrTyRef::Vec { .. } => {
                        // Plan 08-02 Rule 1: explicit type annotation so
                        // `depythonize` returns the correct owned type —
                        // generic Rust APIs like `forget(impl Into<ForgetRequest>)`
                        // won't infer a concrete type from the plain
                        // `let x = pythonize::depythonize(...)?;` shape.
                        writeln!(
                            out,
                            "        let {owned_name}: {ty} = pythonize::depythonize(&{param})?;",
                            owned_name = owned_name,
                            ty = rust_owned_ty(&p.ty),
                            param = p.name
                        )
                        .unwrap();
                        owned_names.push(owned_name);
                    }
                    // Plan 11-02a D3(a) — Handle: clone `.inner` from the
                    // wrapper class reference; no pythonize round-trip.
                    IrTyRef::Handle { name: handle_name } => {
                        writeln!(
                            out,
                            "        let {owned_name}: ::std::sync::Arc<::lunaris::{handle_name}> = {param}.inner.clone();",
                            owned_name = owned_name,
                            handle_name = handle_name,
                            param = p.name
                        )
                        .unwrap();
                        owned_names.push(owned_name);
                    }
                    IrTyRef::Str => {
                        // String is already owned (Python string → Rust
                        // String via PyO3's param conversion) so no
                        // depythonize step is needed.
                        owned_names.push(p.name.clone());
                    }
                    _ => owned_names.push(p.name.clone()),
                }
            }
            writeln!(out, "        pyo3_async_runtimes::tokio::future_into_py(py, async move {{")
                .unwrap();
            // Call-args: `&str` args still need a leading `&` at the call
            // site; owned typed values are passed by value.
            let call_args = m
                .params
                .iter()
                .zip(owned_names.iter())
                .map(|(p, owned)| match &p.ty {
                    IrTyRef::Str => format!("&{}", owned),
                    _ => owned.clone(),
                })
                .collect::<Vec<_>>()
                .join(", ");
            writeln!(
                out,
                "            let out = inner.{name}({call_args}).await.map_err(py_err)?;",
                name = m.name
            )
            .unwrap();
            writeln!(out, "            {ret}", ret = py_return_expr(&m.returns.ty)).unwrap();
            writeln!(out, "        }})").unwrap();
            writeln!(out, "    }}").unwrap();
        }
        // Sync static constructor (Vector::new, Keyword::bm25, Graph::anchored).
        //
        // Plan 08-02 Rule 1 fix: `Vec<T>` / `Named<T>` / `Option<T>` params
        // are depythonized before the call site so the Rust-side inherent
        // method signature sees the real owned typed value (e.g. Graph::anchored
        // takes `Vec<EntityId>`, not `&Bound<'_, PyAny>`).
        (IrAsync::No, IrReceiver::None) => {
            writeln!(out, "    #[staticmethod]").unwrap();
            writeln!(
                out,
                "    fn {name}({params}) -> PyResult<Self> {{",
                name = m.name,
                params = format_params(&m.params, /* leading_comma */ false)
            )
            .unwrap();
            // Pre-depythonize every non-primitive param, mirroring the
            // async ref_self branch.
            let mut owned_names: Vec<String> = Vec::with_capacity(m.params.len());
            for p in &m.params {
                let owned_name = format!("{}_owned", p.name);
                match &p.ty {
                    IrTyRef::Json | IrTyRef::Named { .. } | IrTyRef::Option { .. } | IrTyRef::Vec { .. } => {
                        writeln!(
                            out,
                            "        let {owned_name}: {ty} = pythonize::depythonize(&{param}).map_err(|e| pyo3::exceptions::PyValueError::new_err(format!(\"{param}: {{e}}\")))?;",
                            owned_name = owned_name,
                            ty = rust_owned_ty(&p.ty),
                            param = p.name
                        )
                        .unwrap();
                        owned_names.push(owned_name);
                    }
                    // Plan 11-02a D3(a) — Handle: clone `.inner` (Arc).
                    IrTyRef::Handle { name: handle_name } => {
                        writeln!(
                            out,
                            "        let {owned_name}: ::std::sync::Arc<::lunaris::{handle_name}> = {param}.inner.clone();",
                            owned_name = owned_name,
                            handle_name = handle_name,
                            param = p.name
                        )
                        .unwrap();
                        owned_names.push(owned_name);
                    }
                    _ => owned_names.push(p.name.clone()),
                }
            }
            let call_args = m
                .params
                .iter()
                .zip(owned_names.iter())
                .map(|(p, owned)| match &p.ty {
                    IrTyRef::Str => format!("&{}", owned),
                    _ => owned.clone(),
                })
                .collect::<Vec<_>>()
                .join(", ");
            writeln!(
                out,
                "        let inner = {crate_path}::{type_name}::{name}({call_args});",
                crate_path = crate_path,
                type_name = type_name,
                name = m.name
            )
            .unwrap();
            writeln!(out, "        Ok(Self {{ inner: Arc::new(inner) }})").unwrap();
            writeln!(out, "    }}").unwrap();
        }
        // Sync `&self` method (Lunaris::recall, pipeline-handle toggles).
        //
        // Plan 08-02 Rule 1 fix: the pipeline-toggle method is declared as
        // `toggle(on: bool)` in the codegen surface, but the Rust-side
        // GraphPipelineHandle / ConsolidatorPipelineHandle expose
        // `enable()` / `disable()` rather than a unified `toggle(on)`. We
        // special-case the method name here so emitted code dispatches to
        // the real Rust API. Calling `toggle` on any other type keeps the
        // straight pass-through (future toggle callers would add a method
        // with that literal name).
        (IrAsync::No, IrReceiver::RefSelf) => {
            writeln!(
                out,
                "    fn {name}(&self{params}) -> PyResult<{ret}> {{",
                name = m.name,
                params = format_params(&m.params, /* leading_comma */ true),
                ret = py_sync_return_ty(&m.returns.ty, m.returns.fallible)
            )
            .unwrap();
            if m.name == "toggle"
                && (type_name == "GraphPipelineHandle"
                    || type_name == "ConsolidatorPipelineHandle")
            {
                // Rust surface is enable()/disable(); dispatch on the single
                // `on` bool arg.
                writeln!(
                    out,
                    "        if on {{ self.inner.enable(); }} else {{ self.inner.disable(); }}"
                )
                .unwrap();
                writeln!(out, "        Ok(())").unwrap();
            } else {
                // Plan 11-02b Rule 1 extension — pre-depythonize Named /
                // Json / Vec / Option / Handle params with an EXPLICIT
                // owned-type annotation so the call site sees the concrete
                // Rust type (mirrors the async-ref_self and sync-owned
                // clone_self arms). Load-bearing for
                // `MeetingNotesMemory::attendees(Vec<String>)` whose
                // emitted param is `&Bound<'_, PyAny>` at the FFI layer.
                let mut owned_names: Vec<String> = Vec::with_capacity(m.params.len());
                for p in &m.params {
                    let owned_name = format!("{}_owned", p.name);
                    match &p.ty {
                        IrTyRef::Json | IrTyRef::Named { .. } | IrTyRef::Option { .. } | IrTyRef::Vec { .. } => {
                            writeln!(
                                out,
                                "        let {owned_name}: {ty} = pythonize::depythonize(&{param}).map_err(|e| pyo3::exceptions::PyValueError::new_err(format!(\"{param}: {{e}}\")))?;",
                                owned_name = owned_name,
                                ty = rust_owned_ty(&p.ty),
                                param = p.name
                            )
                            .unwrap();
                            owned_names.push(owned_name);
                        }
                        IrTyRef::Handle { name: handle_name } => {
                            writeln!(
                                out,
                                "        let {owned_name}: ::std::sync::Arc<::lunaris::{handle_name}> = {param}.inner.clone();",
                                owned_name = owned_name,
                                handle_name = handle_name,
                                param = p.name
                            )
                            .unwrap();
                            owned_names.push(owned_name);
                        }
                        _ => owned_names.push(p.name.clone()),
                    }
                }
                let call_args = m
                    .params
                    .iter()
                    .zip(owned_names.iter())
                    .map(|(p, owned)| match &p.ty {
                        IrTyRef::Str => format!("&{}", owned),
                        _ => owned.clone(),
                    })
                    .collect::<Vec<_>>()
                    .join(", ");
                writeln!(
                    out,
                    "        let out = self.inner.{name}({call_args});",
                    name = m.name,
                    call_args = call_args
                )
                .unwrap();
                writeln!(out, "        {ret}", ret = py_sync_return_expr(&m.returns)).unwrap();
            }
            writeln!(out, "    }}").unwrap();
        }
        // Sync `self`-consuming builder method (RetrievalBuilder chain).
        //
        // WR-01 fix (Phase 8 code review): return a typed
        // `PyNotImplementedError` instead of `unimplemented!(...)`.
        // `unimplemented!` panics — and PyO3 converts Rust panics into
        // `PanicException`, a `BaseException` subclass that Python's
        // `except RuntimeError:` / `except LunarisError:` cannot catch.
        // By returning `Err(PyNotImplementedError::new_err(...))` the
        // FFI boundary surfaces a proper `NotImplementedError` (a normal
        // `Exception` subclass), matching the shape of the TS emitter's
        // `Err(napi::Error::from_reason(...))` path.
        // Plan 11-02a D6(b) — owned-self builder with `clone_self = true`
        // hint. Replaces the legacy `PyNotImplementedError` stub with a
        // clone-and-rewrap body: clone the inner `Arc<Inner>`, consume it
        // through the Rust builder method, re-wrap into the target wrapper
        // class. `&self` receiver (not `PyRefMut`) because we never
        // actually consume `self` at the PyO3 layer — the `Arc` clone is
        // cheap.
        (IrAsync::No, IrReceiver::Owned) if m.clone_self => {
            let target_ty = owned_self_target_ty(type_name, &m.returns.ty);
            writeln!(
                out,
                "    fn {name}(&self{params}) -> PyResult<{target_ty}> {{",
                name = m.name,
                params = format_params(&m.params, /* leading_comma */ true),
                target_ty = target_ty
            )
            .unwrap();
            // Plan 11-02b Rule 1 extension — pre-depythonize every
            // Named / Json / Vec / Option / Handle param with an EXPLICIT
            // owned-type annotation so the clone-and-rewrap call site sees
            // the concrete Rust type. Mirrors the async-ref_self arm's
            // Send-safety pattern (even though this is a sync body, the
            // explicit annotation is load-bearing for `impl Into<T>` Rust
            // wrapper params like DocumentKnowledgeBase::filter).
            let mut owned_names: Vec<String> = Vec::with_capacity(m.params.len());
            for p in &m.params {
                let owned_name = format!("{}_owned", p.name);
                match &p.ty {
                    IrTyRef::Json | IrTyRef::Named { .. } | IrTyRef::Option { .. } | IrTyRef::Vec { .. } => {
                        writeln!(
                            out,
                            "        let {owned_name}: {ty} = pythonize::depythonize(&{param}).map_err(|e| pyo3::exceptions::PyValueError::new_err(format!(\"{param}: {{e}}\")))?;",
                            owned_name = owned_name,
                            ty = rust_owned_ty(&p.ty),
                            param = p.name
                        )
                        .unwrap();
                        owned_names.push(owned_name);
                    }
                    IrTyRef::Handle { name: handle_name } => {
                        writeln!(
                            out,
                            "        let {owned_name}: ::std::sync::Arc<::lunaris::{handle_name}> = {param}.inner.clone();",
                            owned_name = owned_name,
                            handle_name = handle_name,
                            param = p.name
                        )
                        .unwrap();
                        owned_names.push(owned_name);
                    }
                    _ => owned_names.push(p.name.clone()),
                }
            }
            let call_args = m
                .params
                .iter()
                .zip(owned_names.iter())
                .map(|(p, owned)| match &p.ty {
                    IrTyRef::Str => format!("&{}", owned),
                    _ => owned.clone(),
                })
                .collect::<Vec<_>>()
                .join(", ");
            writeln!(
                out,
                "        let out = self.inner.as_ref().clone().{name}({call_args});",
                name = m.name,
                call_args = call_args
            )
            .unwrap();
            if m.returns.fallible {
                writeln!(out, "        let out = out.map_err(py_err)?;").unwrap();
            }
            writeln!(
                out,
                "        Ok({target_ty} {{ inner: Arc::new(out) }})",
                target_ty = target_ty
            )
            .unwrap();
            writeln!(out, "    }}").unwrap();
        }
        // Sync `self`-consuming builder method (RetrievalBuilder chain)
        // WITHOUT the `clone_self` hint — legacy stub preserved so the
        // committed Plan 08-01 snapshot stays byte-identical.
        //
        // WR-01 fix (Phase 8 code review): return a typed
        // `PyNotImplementedError` instead of `unimplemented!(...)`.
        // `unimplemented!` panics — and PyO3 converts Rust panics into
        // `PanicException`, a `BaseException` subclass that Python's
        // `except RuntimeError:` / `except LunarisError:` cannot catch.
        // By returning `Err(PyNotImplementedError::new_err(...))` the
        // FFI boundary surfaces a proper `NotImplementedError` (a normal
        // `Exception` subclass), matching the shape of the TS emitter's
        // `Err(napi::Error::from_reason(...))` path.
        (IrAsync::No, IrReceiver::Owned) => {
            writeln!(
                out,
                "    fn {name}(slf: PyRefMut<'_, Self>{params}) -> PyResult<Py{type_name}> {{",
                name = m.name,
                params = format_params(&m.params, /* leading_comma */ true)
            )
            .unwrap();
            writeln!(
                out,
                "        // Builder methods consume self; we clone the inner Arc so Python can keep the prior handle alive."
            )
            .unwrap();
            writeln!(
                out,
                "        let _ = slf; let _ = ({unused}); // wired by Plan 08-02's emitter body; Plan 08-01 snapshot freezes the signature.",
                unused = format_call_args(&m.params)
            )
            .unwrap();
            writeln!(
                out,
                "        Err(pyo3::exceptions::PyNotImplementedError::new_err(\"Use lunaris.RetrievalBuilder from lunaris.dsl for a working builder; the PyO3-frozen class method is not wired.\"))"
            )
            .unwrap();
            writeln!(out, "    }}").unwrap();
        }
        // Plan 11-02a — async owned-self with `clone_self = true`. Used by
        // DocumentKnowledgeBase::search et al. when the Rust signature is
        // `async fn search(self, query: &str) -> Result<Vec<Hit>>`. Clone
        // the inner Arc BEFORE the async move (PyO3 GIL invariant:
        // future_into_py owns every `.await`), then call & wrap. Non-clone
        // async-owned falls through to the `_ =>` stub below.
        (IrAsync::Yes, IrReceiver::Owned) if m.clone_self => {
            let target_ty = owned_self_target_ty(type_name, &m.returns.ty);
            writeln!(
                out,
                "    fn {name}<'py>(&self, py: Python<'py>{params}) -> PyResult<Bound<'py, PyAny>> {{",
                name = m.name,
                params = format_params(&m.params, /* leading_comma */ true)
            )
            .unwrap();
            writeln!(out, "        let cloned = self.inner.as_ref().clone();").unwrap();
            // Pre-depythonize params for Send-safety (same rationale as
            // the async ref_self arm).
            let mut owned_names: Vec<String> = Vec::with_capacity(m.params.len());
            for p in &m.params {
                let owned_name = format!("{}_owned", p.name);
                match &p.ty {
                    IrTyRef::Json | IrTyRef::Named { .. } | IrTyRef::Option { .. } | IrTyRef::Vec { .. } => {
                        writeln!(
                            out,
                            "        let {owned_name}: {ty} = pythonize::depythonize(&{param})?;",
                            owned_name = owned_name,
                            ty = rust_owned_ty(&p.ty),
                            param = p.name
                        )
                        .unwrap();
                        owned_names.push(owned_name);
                    }
                    IrTyRef::Handle { name: handle_name } => {
                        writeln!(
                            out,
                            "        let {owned_name}: ::std::sync::Arc<::lunaris::{handle_name}> = {param}.inner.clone();",
                            owned_name = owned_name,
                            handle_name = handle_name,
                            param = p.name
                        )
                        .unwrap();
                        owned_names.push(owned_name);
                    }
                    _ => owned_names.push(p.name.clone()),
                }
            }
            writeln!(out, "        pyo3_async_runtimes::tokio::future_into_py(py, async move {{")
                .unwrap();
            let call_args = m
                .params
                .iter()
                .zip(owned_names.iter())
                .map(|(p, owned)| match &p.ty {
                    IrTyRef::Str => format!("&{}", owned),
                    _ => owned.clone(),
                })
                .collect::<Vec<_>>()
                .join(", ");
            if m.returns.fallible {
                writeln!(
                    out,
                    "            let out = cloned.{name}({call_args}).await.map_err(py_err)?;",
                    name = m.name
                )
                .unwrap();
            } else {
                writeln!(
                    out,
                    "            let out = cloned.{name}({call_args}).await;",
                    name = m.name
                )
                .unwrap();
            }
            // Return-shape — async-owned + clone_self + RefSelf/Named
            // produces a wrapper-class construction; other shapes fall
            // back to pythonize (matches the async-ref_self pattern).
            match &m.returns.ty {
                IrTyRef::RefSelf | IrTyRef::Named { .. } => {
                    writeln!(
                        out,
                        "            Ok({target_ty} {{ inner: Arc::new(out) }})",
                        target_ty = target_ty
                    )
                    .unwrap();
                }
                _ => {
                    writeln!(
                        out,
                        "            {ret}",
                        ret = py_return_expr(&m.returns.ty)
                    )
                    .unwrap();
                }
            }
            writeln!(out, "        }})").unwrap();
            writeln!(out, "    }}").unwrap();
        }
        // Unhandled shapes (MutSelf / async Owned without clone_self) —
        // defensive stub. The v0.1.1 15-item surface does not exercise
        // either.
        _ => {
            writeln!(
                out,
                "    // TODO: unsupported receiver/async combination for {}::{} — emitter stub.",
                type_name, m.name
            )
            .unwrap();
        }
    }
    out.push('\n');
}

/// Plan 11-02a D6(b) — resolve the target wrapper class name for a
/// clone-and-rewrap owned-self body.
/// - `IrTyRef::RefSelf` — chainable builder returns its own `Py{Self}`.
/// - `IrTyRef::Named { name }` — returns `Py{name}` (e.g.
///   `.channel() -> SlackArchiveQuery` lands as `PySlackArchiveQuery`).
/// - Anything else — fall back to `Py{type_name}` (safe default; legacy
///   wrappers only ever exercise RefSelf).
fn owned_self_target_ty(type_name: &str, ret_ty: &IrTyRef) -> String {
    match ret_ty {
        IrTyRef::RefSelf => format!("Py{type_name}"),
        IrTyRef::Named { name } => format!("Py{name}"),
        _ => format!("Py{type_name}"),
    }
}

fn format_params(params: &[IrParam], leading_comma: bool) -> String {
    let mut s = String::new();
    for (i, p) in params.iter().enumerate() {
        if leading_comma || i > 0 {
            s.push_str(", ");
        }
        s.push_str(&p.name);
        s.push_str(": ");
        s.push_str(&py_param_ty(&p.ty));
    }
    s
}

fn format_call_args(params: &[IrParam]) -> String {
    params
        .iter()
        .map(|p| match &p.ty {
            IrTyRef::Str => format!("&{}", p.name),
            IrTyRef::Json => format!("pythonize::depythonize(&{})?", p.name),
            _ => p.name.clone(),
        })
        .collect::<Vec<_>>()
        .join(", ")
}

fn py_param_ty(ty: &IrTyRef) -> String {
    match ty {
        IrTyRef::Unit => "()".to_string(),
        IrTyRef::Str => "String".to_string(),
        IrTyRef::Usize => "usize".to_string(),
        IrTyRef::Bool => "bool".to_string(),
        IrTyRef::Json => "&Bound<'_, PyAny>".to_string(),
        IrTyRef::RefSelf => "&Self".to_string(),
        IrTyRef::Named { .. } => "&Bound<'_, PyAny>".to_string(),
        IrTyRef::Option { .. } => "Option<&Bound<'_, PyAny>>".to_string(),
        IrTyRef::Vec { .. } => "&Bound<'_, PyAny>".to_string(),
        // Plan 11-02a D3(a) — Handle wrappers pass the PyO3 class reference
        // (`&PyLunaris`) directly; the emitter then clones `.inner` (an
        // `Arc`) at the call site. No pythonize round-trip.
        IrTyRef::Handle { name } => format!("&Py{name}"),
    }
}

/// Plan 08-02 Rule 1 addition — Rust owned-type spelling used as the
/// explicit type annotation on `let {name}_owned: {ty} = pythonize::depythonize(...)`
/// so type inference works at the call site regardless of how the Rust
/// method was declared.
fn rust_owned_ty(ty: &IrTyRef) -> String {
    match ty {
        IrTyRef::Json => "serde_json::Value".to_string(),
        IrTyRef::Named { name } => match name.as_str() {
            "Episode" => "::lunaris::Episode".to_string(),
            "ForgetRequest" => "::lunaris::forget::ForgetRequest".to_string(),
            "Hlc" => "::lunaris::Hlc".to_string(),
            "EntityId" => "::lunaris::EntityId".to_string(),
            "RetrievalBuilder" => "::lunaris::RetrievalBuilder".to_string(),
            // Plan 11-02a D5 — explicit allow-list entries for the Phase
            // 10/11 wrapper surface. Each maps to `::lunaris::{name}`
            // (same as the fallback) — umbrella re-exports carry them.
            // Listed explicitly for grep-ability; bit-stable vs. fallback.
            "Hit" => "::lunaris::Hit".to_string(),
            "ConsolidationReport" => "::lunaris::ConsolidationReport".to_string(),
            "SlackArchiveQuery" => "::lunaris::SlackArchiveQuery".to_string(),
            "MeetingNotesQuery" => "::lunaris::MeetingNotesQuery".to_string(),
            // Plan 11-02b Rule 1 extension — concrete-spelling allow-list
            // entries for Phase 10/11 wrapper param shapes that have no
            // clean `IrTyRef` grammar today. Annotated in surface.toml as
            // `ty = { kind = "named", name = "<TagName>" }`; the emitter
            // lowers through pythonize / serde_json::from_value exactly
            // like `Episode` / `ForgetRequest`. No IR grammar change.
            //
            // - `DocumentChunks` — `Vec<(String, serde_json::Map<...>)>` used
            //   by every documentary ingest method (D4(b) — planner said
            //   `kind = "json"` but that lands `serde_json::Value` which
            //   doesn't coerce to the tuple-of-map shape).
            // - `UnixMs` — plain `i64` for `CodeRepoMemory::ingest_commit`'s
            //   committer_date_unix_ms param.
            // - `StrList` — `Vec<String>` for `MeetingNotesMemory::attendees`
            //   after the pre-authorised ≤3-LOC Rust widen from `&[&str]`.
            // - `JsonValue` — `serde_json::Value` for
            //   `DocumentKnowledgeBase::filter(value: impl Into<Value>)` —
            //   the `impl Into<Value>` blanket accepts a typed Value.
            "DocumentChunks" => {
                "Vec<(String, serde_json::Map<String, serde_json::Value>)>".to_string()
            }
            "UnixMs" => "i64".to_string(),
            "StrList" => "Vec<String>".to_string(),
            "JsonValue" => "serde_json::Value".to_string(),
            _ => format!("::lunaris::{name}"),
        },
        IrTyRef::Option { inner } => format!("Option<{}>", rust_owned_ty(inner)),
        IrTyRef::Vec { inner } => format!("Vec<{}>", rust_owned_ty(inner)),
        // Plan 11-02a D3(a) — Handle lowers to `Arc<::lunaris::{name}>` on
        // the owned-binding side.
        IrTyRef::Handle { name } => format!("::std::sync::Arc<::lunaris::{name}>"),
        _ => "serde_json::Value".to_string(),
    }
}

fn py_return_expr(ty: &IrTyRef) -> String {
    match ty {
        IrTyRef::Named { name } if name == "Lsn" => {
            "Python::with_gil(|py| Ok(out.to_string().into_pyobject(py)?.into_any().unbind()))"
                .into()
        }
        IrTyRef::Unit => "Ok(Python::with_gil(|py| py.None()))".into(),
        _ => "Python::with_gil(|py| Ok(pythonize::pythonize(py, &out)?.unbind()))".into(),
    }
}

fn py_sync_return_ty(ty: &IrTyRef, _fallible: bool) -> String {
    // Both fallible and infallible sync methods wrap in `PyResult<T>` at the
    // outer signature layer; the caller formats the `PyResult<...>` around
    // this return so here we only produce the inner type name. The
    // `_fallible` argument is preserved in the signature for future
    // differentiation (e.g. if we want to drop the `PyResult` wrapper on
    // trivially infallible toggles) without churning every caller.
    match ty {
        IrTyRef::Unit => "()".into(),
        IrTyRef::RefSelf => "Self".into(),
        IrTyRef::Named { name } => format!("Py{name}"),
        other => format!("<{other:?}>"),
    }
}

fn py_sync_return_expr(r: &crate::ir::IrReturn) -> String {
    match (&r.ty, r.fallible) {
        (IrTyRef::Unit, _) => "let _ = out; Ok(())".into(),
        (IrTyRef::RefSelf, _) => "Ok(Self { inner: Arc::new(out) })".into(),
        // Plan 08-02 Rule 1 fix: for a sync `&self` method returning a
        // named-type (e.g. `Lunaris::recall() -> RetrievalBuilder`), the
        // wrapper must construct the TARGET PyFoo, not `Self` — `Self`
        // would resolve to the current `impl Py{source}` block and produce
        // `Py{source} { inner: Arc::new(<RetrievalBuilder>) }`, which fails
        // to typecheck.
        (IrTyRef::Named { name }, false) => {
            format!("Ok(Py{name} {{ inner: Arc::new(out) }})")
        }
        _ => "Ok(out)".into(),
    }
}
