//! napi-rs 3.x emitter.
//!
//! Converts a [`SurfaceIR`] into the two artefacts Plan 08-03 will land at
//! `crates/lunaris-ts/src/generated.rs` + `crates/lunaris-ts/generated.d.ts`
//! (Wave 3 host crate doesn't exist yet — Plan 08-01 commits the snapshots
//! at `crates/lunaris-codegen/snapshots/generated_ts.{rs,d.ts}` per revision
//! 2).
//!
//! napi-rs 3.x handles the `Promise<T>` conversion for async fns natively;
//! the emitter simply marks async methods with `#[napi]` and returns
//! `napi::Result<T>`. The `.d.ts` side mirrors the class / async shape.

use std::fmt::Write as _;

use crate::ir::{IrAsync, IrKind, IrMethod, IrParam, IrReceiver, IrTyRef, IrType, SurfaceIR};

const RUST_HEADER: &str = "\
// @generated by lunaris-codegen — do not edit
//
// Phase 8 Plan 08-01 (BIND-GEN-01..03). napi-rs 3.x wrapper surface emitted
// from `crates/lunaris-codegen/annotations/surface.toml`. Regenerate with
// `cargo run -p lunaris-codegen -- --emit ts`.
";

const DTS_HEADER: &str = "\
// @generated by lunaris-codegen — do not edit
//
// Phase 8 Plan 08-01 (BIND-GEN-01..03). TypeScript declarations mirroring
// the napi-rs bindings. Regenerate with
// `cargo run -p lunaris-codegen -- --emit ts`.
";

/// Paired emitter output: Rust glue (lands at `src/generated.rs`) plus the
/// `.d.ts` declarations (lands at `generated.d.ts` alongside the built
/// `.node` binary).
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct TsOutput {
    pub rust_glue: String,
    pub dts: String,
}

/// Emit napi-rs glue + matching `.d.ts` for the given [`SurfaceIR`].
///
/// The emitted Rust file is designed to be consumed as a proper module
/// (`mod generated;`) by the host crate (Plan 08-03 `crates/lunaris-ts`),
/// NOT via `include!` — napi-rs 3.x's `#[napi]` proc-macro maintains
/// global struct-registration state that `include!` disrupts, surfacing
/// as "Did not find struct `X` parsed before expand #[napi] for impl"
/// on factory methods. Using a real module keeps proc-macro expansion
/// order stable.
///
/// The emitted file references `super::errors::napi_err` so the host
/// crate wires error mapping by placing an `errors.rs` with a
/// `pub(crate) fn napi_err(err) -> napi::Error` sibling.
pub fn emit_ts(ir: &SurfaceIR) -> TsOutput {
    let mut rust = String::new();
    let mut dts = String::new();
    rust.push_str(RUST_HEADER);
    rust.push('\n');
    rust.push_str("use napi_derive::napi;\n");
    rust.push_str("use std::sync::Arc;\n");
    rust.push_str("\n");
    rust.push_str("use super::errors::napi_err;\n\n");

    dts.push_str(DTS_HEADER);
    dts.push('\n');

    for module in &ir.modules {
        let crate_path = module.rust_crate_path.as_deref().unwrap_or("::lunaris");
        for ty in &module.types {
            emit_ts_type_rust(&mut rust, ty, crate_path);
            emit_ts_type_dts(&mut dts, ty);
        }
    }
    TsOutput { rust_glue: rust, dts }
}

fn emit_ts_type_rust(out: &mut String, ty: &IrType, crate_path: &str) {
    if let Some(doc) = &ty.doc {
        writeln!(out, "/// {doc}").unwrap();
    }
    writeln!(
        out,
        "#[napi]\npub struct {name} {{\n    #[allow(dead_code)]\n    pub(crate) inner: Arc<{crate_path}::{name}>,\n}}",
        name = ty.name,
        crate_path = crate_path
    )
    .unwrap();
    out.push('\n');
    writeln!(out, "#[napi]\nimpl {name} {{", name = ty.name).unwrap();
    for m in &ty.methods {
        emit_ts_method_rust(out, &ty.name, m, ty.kind.clone(), crate_path);
    }
    writeln!(out, "}}\n").unwrap();
}

fn emit_ts_method_rust(
    out: &mut String,
    type_name: &str,
    m: &IrMethod,
    _kind: IrKind,
    crate_path: &str,
) {
    if let Some(doc) = &m.doc {
        writeln!(out, "    /// {doc}").unwrap();
    }
    match (m.is_async, m.receiver) {
        // Static async constructor (e.g. `Lunaris::open`).
        //
        // Plan 08-03 Rule 1 fix (mirror of Plan 08-02's emit_py.rs fix):
        // pre-convert every `Named` / `Vec` / `Option` / `Json` param via
        // `serde_json::from_value::<T>` BEFORE the `Lunaris::open` call so
        // the Rust-side inherent method sees owned typed values rather
        // than a raw `serde_json::Value`. napi-rs 3.x has no GIL analog,
        // but the same pre-conversion pattern keeps the emitted code
        // typecheck-clean against the v0.1.0 Rust surface.
        (IrAsync::Yes, IrReceiver::None) => {
            writeln!(out, "    #[napi(factory)]").unwrap();
            writeln!(
                out,
                "    pub async fn {name}({params}) -> napi::Result<Self> {{",
                name = m.name,
                params = format_params_rust(&m.params, /* with_self */ false)
            )
            .unwrap();
            let owned_names = emit_ts_owned_bindings(out, &m.params);
            let call_args = ts_call_args_from_owned(&m.params, &owned_names);
            writeln!(
                out,
                "        let inner = {crate_path}::{type_name}::{name}({call_args}).await.map_err(napi_err)?;",
                crate_path = crate_path,
                type_name = type_name,
                name = m.name
            )
            .unwrap();
            writeln!(out, "        Ok(Self {{ inner: Arc::new(inner) }})").unwrap();
            writeln!(out, "    }}").unwrap();
        }
        // Async instance method (e.g. `Lunaris::ingest`, `Lunaris::forget`,
        // `Lunaris::snapshot`).
        //
        // Plan 08-03 Rule 1 fix: eager `serde_json::from_value` for every
        // non-primitive param so `inner.ingest(Episode)` / `inner.forget(ForgetRequest)`
        // call sites see the concrete Rust owned type. `String` / `bool` /
        // `u32` pass through as-is.
        (IrAsync::Yes, IrReceiver::RefSelf) => {
            writeln!(out, "    #[napi]").unwrap();
            writeln!(
                out,
                "    pub async fn {name}(&self{params}) -> napi::Result<{ret}> {{",
                name = m.name,
                params = format_params_rust(&m.params, /* with_self */ true),
                ret = ts_async_return_ty_rust(&m.returns.ty)
            )
            .unwrap();
            let owned_names = emit_ts_owned_bindings(out, &m.params);
            let call_args = ts_call_args_from_owned(&m.params, &owned_names);
            writeln!(
                out,
                "        let out = self.inner.{name}({call_args}).await.map_err(napi_err)?;",
                name = m.name
            )
            .unwrap();
            writeln!(out, "        {ret}", ret = ts_return_expr_rust(&m.returns.ty)).unwrap();
            writeln!(out, "    }}").unwrap();
        }
        // Sync static constructor (Vector::new, Keyword::bm25, Graph::anchored).
        //
        // Plan 08-03 Rule 1 fix: the Graph::anchored path takes
        // `Vec<EntityId>` — same convert-before-call shape as the async
        // ref_self branch. `Str` / `Usize` / `Bool` pass through.
        //
        // WR-02 fix (Phase 8 code review): if ANY param requires serde
        // deserialization (`Vec<T>` / `Named<T>` / `Option<T>` / `Json`),
        // the factory MUST return `napi::Result<Self>` and route serde
        // errors through `.map_err(napi_err)?`. Previously the
        // infallible path called `.unwrap_or_else(|e| panic!(...))`
        // which surfaces as a Rust panic crossing the FFI boundary —
        // napi-rs 3.x installs a panic hook that converts this to a JS
        // `Error` but the behaviour is runtime-dependent and the
        // emitted message is less structured than the typed
        // `napi::Result<T>` path. Using `emit_ts_owned_bindings` (the
        // fallible variant) collapses the two paths.
        (IrAsync::No, IrReceiver::None) => {
            let any_fallible = m.params.iter().any(|p| {
                matches!(
                    &p.ty,
                    IrTyRef::Vec { .. }
                        | IrTyRef::Named { .. }
                        | IrTyRef::Option { .. }
                        | IrTyRef::Json
                )
            });
            let ret_ty = if any_fallible { "napi::Result<Self>" } else { "Self" };
            let ok_wrap = if any_fallible {
                "Ok(Self { inner: Arc::new(inner) })"
            } else {
                "Self { inner: Arc::new(inner) }"
            };
            writeln!(out, "    #[napi(factory)]").unwrap();
            writeln!(
                out,
                "    pub fn {name}({params}) -> {ret_ty} {{",
                name = m.name,
                params = format_params_rust(&m.params, /* with_self */ false),
                ret_ty = ret_ty,
            )
            .unwrap();
            // Use the fallible bindings emitter when any param can
            // serde-fail; otherwise the infallible primitive-only path
            // (Vector::new, Keyword::bm25) is still structurally
            // equivalent.
            let owned_names = if any_fallible {
                emit_ts_owned_bindings(out, &m.params)
            } else {
                emit_ts_owned_bindings_infallible(out, &m.params)
            };
            let call_args = ts_call_args_from_owned(&m.params, &owned_names);
            writeln!(
                out,
                "        let inner = {crate_path}::{type_name}::{name}({call_args});",
                crate_path = crate_path,
                type_name = type_name,
                name = m.name
            )
            .unwrap();
            writeln!(out, "        {ok_wrap}", ok_wrap = ok_wrap).unwrap();
            writeln!(out, "    }}").unwrap();
        }
        // Sync `&self` method (Lunaris::recall, pipeline-handle toggles).
        //
        // Plan 08-03 Rule 1 fix: the pipeline-toggle method is declared as
        // `toggle(on: bool)` in the codegen surface, but the Rust-side
        // GraphPipelineHandle / ConsolidatorPipelineHandle expose
        // `enable()` / `disable()` rather than a unified `toggle(on)`. We
        // special-case the method name here so emitted code dispatches to
        // the real Rust API — mirror of the emit_py.rs fix.
        //
        // For `Lunaris::recall() -> RetrievalBuilder` the wrapper must
        // construct the TARGET napi class (`RetrievalBuilder { inner: Arc::new(out) }`),
        // not serialise a non-serde-derivable builder to JSON.
        (IrAsync::No, IrReceiver::RefSelf) => {
            writeln!(out, "    #[napi]").unwrap();
            writeln!(
                out,
                "    pub fn {name}(&self{params}) -> napi::Result<{ret}> {{",
                name = m.name,
                params = format_params_rust(&m.params, /* with_self */ true),
                ret = ts_sync_return_ty_rust(&m.returns.ty)
            )
            .unwrap();
            if m.name == "toggle"
                && (type_name == "GraphPipelineHandle"
                    || type_name == "ConsolidatorPipelineHandle")
            {
                // Rust surface is enable()/disable(); dispatch on the single
                // `on` bool arg.
                writeln!(
                    out,
                    "        if on {{ self.inner.enable(); }} else {{ self.inner.disable(); }}"
                )
                .unwrap();
                writeln!(out, "        Ok(())").unwrap();
            } else {
                writeln!(
                    out,
                    "        let out = self.inner.{name}({call_args});",
                    name = m.name,
                    call_args = format_call_args(&m.params)
                )
                .unwrap();
                writeln!(out, "        {ret}", ret = ts_sync_return_expr_rust(&m.returns.ty)).unwrap();
            }
            writeln!(out, "    }}").unwrap();
        }
        // Plan 11-02a D6(b) — owned-self builder with `clone_self = true`
        // hint. Clone the inner `Arc<Inner>` via `as_ref().clone()`,
        // consume through the Rust builder, re-wrap. Mirror of the
        // emit_py.rs clone-and-rewrap arm.
        (IrAsync::No, IrReceiver::Owned) if m.clone_self => {
            let target_ty = ts_owned_self_target_ty(type_name, &m.returns.ty);
            writeln!(out, "    #[napi]").unwrap();
            writeln!(
                out,
                "    pub fn {name}(&self{params}) -> napi::Result<{target_ty}> {{",
                name = m.name,
                params = format_params_rust(&m.params, /* with_self */ true),
                target_ty = target_ty
            )
            .unwrap();
            let owned_names = emit_ts_owned_bindings(out, &m.params);
            let call_args = ts_call_args_from_owned(&m.params, &owned_names);
            writeln!(
                out,
                "        let out = self.inner.as_ref().clone().{name}({call_args});",
                name = m.name,
                call_args = call_args
            )
            .unwrap();
            if m.returns.fallible {
                writeln!(out, "        let out = out.map_err(napi_err)?;").unwrap();
            }
            writeln!(
                out,
                "        Ok({target_ty} {{ inner: Arc::new(out) }})",
                target_ty = target_ty
            )
            .unwrap();
            writeln!(out, "    }}").unwrap();
        }
        (IrAsync::No, IrReceiver::Owned) => {
            writeln!(out, "    #[napi]").unwrap();
            writeln!(
                out,
                "    pub fn {name}(&self{params}) -> napi::Result<{type_name}> {{",
                name = m.name,
                params = format_params_rust(&m.params, /* with_self */ true),
                type_name = type_name
            )
            .unwrap();
            writeln!(
                out,
                "        // Owned-self builder methods return a new wrapper; Plan 08-03 wires the body."
            )
            .unwrap();
            writeln!(out, "        let _ = ({unused});", unused = format_call_args(&m.params))
                .unwrap();
            writeln!(out, "        Err(napi::Error::from_reason(\"Plan 08-03 wires the body\"))")
                .unwrap();
            writeln!(out, "    }}").unwrap();
        }
        // Plan 11-02a — async owned-self + clone_self. napi-rs 3.x handles
        // `async fn` natively; we clone the inner Arc, await the owned
        // builder method, re-wrap.
        (IrAsync::Yes, IrReceiver::Owned) if m.clone_self => {
            let target_ty = ts_owned_self_target_ty(type_name, &m.returns.ty);
            writeln!(out, "    #[napi]").unwrap();
            writeln!(
                out,
                "    pub async fn {name}(&self{params}) -> napi::Result<{target_ty}> {{",
                name = m.name,
                params = format_params_rust(&m.params, /* with_self */ true),
                target_ty = target_ty
            )
            .unwrap();
            writeln!(out, "        let cloned = self.inner.as_ref().clone();").unwrap();
            let owned_names = emit_ts_owned_bindings(out, &m.params);
            let call_args = ts_call_args_from_owned(&m.params, &owned_names);
            if m.returns.fallible {
                writeln!(
                    out,
                    "        let out = cloned.{name}({call_args}).await.map_err(napi_err)?;",
                    name = m.name,
                    call_args = call_args
                )
                .unwrap();
            } else {
                writeln!(
                    out,
                    "        let out = cloned.{name}({call_args}).await;",
                    name = m.name,
                    call_args = call_args
                )
                .unwrap();
            }
            writeln!(
                out,
                "        Ok({target_ty} {{ inner: Arc::new(out) }})",
                target_ty = target_ty
            )
            .unwrap();
            writeln!(out, "    }}").unwrap();
        }
        _ => {
            writeln!(
                out,
                "    // TODO: unsupported receiver/async combination for {}::{} — emitter stub.",
                type_name, m.name
            )
            .unwrap();
        }
    }
    out.push('\n');
}

/// Plan 08-03 Rule 1 — emit `let {name}_owned: {ty} = serde_json::from_value(...)` lines
/// for every non-primitive param. Returns the per-param bound name (either
/// the original `p.name` for primitives or `"{p.name}_owned"` for typed
/// Named / Vec / Option / Json). Used by async methods that must `?` the
/// error back up through the napi::Result return.
fn emit_ts_owned_bindings(out: &mut String, params: &[IrParam]) -> Vec<String> {
    let mut names: Vec<String> = Vec::with_capacity(params.len());
    for p in params {
        match &p.ty {
            // `Vec<serde_json::Value>` needs to be wrapped in
            // `serde_json::Value::Array(...)` before `serde_json::from_value`
            // can coerce it into a typed `Vec<T>`.
            IrTyRef::Vec { .. } => {
                let owned_name = format!("{}_owned", p.name);
                writeln!(
                    out,
                    "        let {owned_name}: {ty} = serde_json::from_value(serde_json::Value::Array({param}.clone())).map_err(napi_err)?;",
                    owned_name = owned_name,
                    ty = rust_owned_ty_ts(&p.ty),
                    param = p.name
                )
                .unwrap();
                names.push(owned_name);
            }
            IrTyRef::Named { .. } | IrTyRef::Json | IrTyRef::Option { .. } => {
                let owned_name = format!("{}_owned", p.name);
                writeln!(
                    out,
                    "        let {owned_name}: {ty} = serde_json::from_value({param}.clone()).map_err(napi_err)?;",
                    owned_name = owned_name,
                    ty = rust_owned_ty_ts(&p.ty),
                    param = p.name
                )
                .unwrap();
                names.push(owned_name);
            }
            IrTyRef::Str | IrTyRef::Usize | IrTyRef::Bool | IrTyRef::Unit | IrTyRef::RefSelf => {
                names.push(p.name.clone());
            }
            // Plan 11-02a D3(a) — Handle wrapper: clone `.inner` directly,
            // no serde round-trip.
            IrTyRef::Handle { name } => {
                let owned_name = format!("{}_owned", p.name);
                writeln!(
                    out,
                    "        let {owned_name}: ::std::sync::Arc<::lunaris::{name}> = {param}.inner.clone();",
                    owned_name = owned_name,
                    name = name,
                    param = p.name
                )
                .unwrap();
                names.push(owned_name);
            }
        }
    }
    names
}

/// Same as [`emit_ts_owned_bindings`] but used for sync infallible contexts
/// (e.g. `Vector::new`) where the caller signature doesn't return
/// `napi::Result<T>`. napi-rs 3.x allows any param that accepts JSON values
/// (like `Vec<serde_json::Value>` for `Graph::anchored`) to fail
/// deserialization — in the sync case we surface the failure as a `panic!`
/// with the serde error so it bubbles up as a JS `Error` with a readable
/// reason instead of silent coercion. Only `Graph::anchored` currently
/// exercises this path.
fn emit_ts_owned_bindings_infallible(out: &mut String, params: &[IrParam]) -> Vec<String> {
    let mut names: Vec<String> = Vec::with_capacity(params.len());
    for p in params {
        match &p.ty {
            IrTyRef::Vec { .. } => {
                let owned_name = format!("{}_owned", p.name);
                writeln!(
                    out,
                    "        let {owned_name}: {ty} = serde_json::from_value(serde_json::Value::Array({param}.clone())).unwrap_or_else(|e| panic!(\"{param}: {{e}}\"));",
                    owned_name = owned_name,
                    ty = rust_owned_ty_ts(&p.ty),
                    param = p.name
                )
                .unwrap();
                names.push(owned_name);
            }
            IrTyRef::Named { .. } | IrTyRef::Json | IrTyRef::Option { .. } => {
                let owned_name = format!("{}_owned", p.name);
                writeln!(
                    out,
                    "        let {owned_name}: {ty} = serde_json::from_value({param}.clone()).unwrap_or_else(|e| panic!(\"{param}: {{e}}\"));",
                    owned_name = owned_name,
                    ty = rust_owned_ty_ts(&p.ty),
                    param = p.name
                )
                .unwrap();
                names.push(owned_name);
            }
            IrTyRef::Str | IrTyRef::Usize | IrTyRef::Bool | IrTyRef::Unit | IrTyRef::RefSelf => {
                names.push(p.name.clone());
            }
            // Plan 11-02a D3(a) — Handle wrapper: clone `.inner` directly,
            // no serde round-trip (mirror of the fallible branch).
            IrTyRef::Handle { name } => {
                let owned_name = format!("{}_owned", p.name);
                writeln!(
                    out,
                    "        let {owned_name}: ::std::sync::Arc<::lunaris::{name}> = {param}.inner.clone();",
                    owned_name = owned_name,
                    name = name,
                    param = p.name
                )
                .unwrap();
                names.push(owned_name);
            }
        }
    }
    names
}

/// Per-param call-site expression. Mirrors emit_py.rs:
/// - `&str` params → `&{name}` (leading `&` for Rust borrow)
/// - `Usize` params stay as `u32` at the napi boundary; we cast to `usize`
///   at the call site because `Vector::new` et al. take `usize`.
/// - Everything else uses the pre-depythonized owned value (or the raw name
///   for primitives).
fn ts_call_args_from_owned(params: &[IrParam], owned: &[String]) -> String {
    params
        .iter()
        .zip(owned.iter())
        .map(|(p, owned)| match &p.ty {
            IrTyRef::Str => format!("&{}", owned),
            IrTyRef::Usize => format!("{} as usize", owned),
            _ => owned.clone(),
        })
        .collect::<Vec<_>>()
        .join(", ")
}

/// Plan 08-03 — Rust owned-type spelling used as the explicit type
/// annotation on `let {name}_owned: {ty} = serde_json::from_value(...)`.
/// Mirrors `emit_py.rs::rust_owned_ty` so the two emitters stay in lockstep
/// on which Rust spelling each surface.toml `kind = "named"` maps to.
fn rust_owned_ty_ts(ty: &IrTyRef) -> String {
    match ty {
        IrTyRef::Json => "serde_json::Value".to_string(),
        IrTyRef::Named { name } => match name.as_str() {
            "Episode" => "::lunaris::Episode".to_string(),
            "ForgetRequest" => "::lunaris::forget::ForgetRequest".to_string(),
            "Hlc" => "::lunaris::Hlc".to_string(),
            "EntityId" => "::lunaris::EntityId".to_string(),
            "RetrievalBuilder" => "::lunaris::RetrievalBuilder".to_string(),
            // Plan 11-02a D5 — explicit allow-list; same spelling as the
            // fallback (umbrella re-exports). Listed for grep-ability;
            // bit-stable vs. fallback arm.
            "Hit" => "::lunaris::Hit".to_string(),
            "ConsolidationReport" => "::lunaris::ConsolidationReport".to_string(),
            "SlackArchiveQuery" => "::lunaris::SlackArchiveQuery".to_string(),
            "MeetingNotesQuery" => "::lunaris::MeetingNotesQuery".to_string(),
            _ => format!("::lunaris::{name}"),
        },
        IrTyRef::Option { inner } => format!("Option<{}>", rust_owned_ty_ts(inner)),
        IrTyRef::Vec { inner } => format!("Vec<{}>", rust_owned_ty_ts(inner)),
        // Plan 11-02a D3(a) — Handle lowers to `Arc<::lunaris::{name}>`.
        IrTyRef::Handle { name } => format!("::std::sync::Arc<::lunaris::{name}>"),
        _ => "serde_json::Value".to_string(),
    }
}

fn emit_ts_type_dts(out: &mut String, ty: &IrType) {
    if let Some(doc) = &ty.doc {
        writeln!(out, "/** {doc} */").unwrap();
    }
    writeln!(out, "export class {} {{", ty.name).unwrap();
    for m in &ty.methods {
        emit_ts_method_dts(out, m);
    }
    writeln!(out, "}}\n").unwrap();
}

fn emit_ts_method_dts(out: &mut String, m: &IrMethod) {
    if let Some(doc) = &m.doc {
        writeln!(out, "  /** {doc} */").unwrap();
    }
    let is_static = matches!(m.receiver, IrReceiver::None);
    let prefix = if is_static { "  static " } else { "  " };
    let params = m
        .params
        .iter()
        .map(|p| format!("{}: {}", p.name, ts_param_ty_dts(&p.ty)))
        .collect::<Vec<_>>()
        .join(", ");
    let ret = match (&m.is_async, &m.returns.ty) {
        (IrAsync::Yes, _) => format!("Promise<{}>", ts_return_ty_dts(&m.returns.ty)),
        (IrAsync::No, ty) => ts_return_ty_dts(ty),
    };
    writeln!(out, "{prefix}{name}({params}): {ret};", name = m.name).unwrap();
}

fn format_params_rust(params: &[IrParam], _with_self: bool) -> String {
    let mut s = String::new();
    for p in params {
        s.push_str(", ");
        s.push_str(&p.name);
        s.push_str(": ");
        s.push_str(&ts_param_ty_rust(&p.ty));
    }
    // If `_with_self` is false (static), trim the leading ", " — napi-rs
    // factory functions don't take `&self` but do take leading parameters.
    if !_with_self && s.starts_with(", ") {
        s = s[2..].to_string();
    }
    s
}

fn format_call_args(params: &[IrParam]) -> String {
    params
        .iter()
        .map(|p| match &p.ty {
            IrTyRef::Str => format!("&{}", p.name),
            IrTyRef::Json => {
                format!("serde_json::from_value({}.clone()).map_err(napi_err)?", p.name)
            }
            _ => p.name.clone(),
        })
        .collect::<Vec<_>>()
        .join(", ")
}

fn ts_param_ty_rust(ty: &IrTyRef) -> String {
    match ty {
        IrTyRef::Unit => "()".to_string(),
        IrTyRef::Str => "String".to_string(),
        IrTyRef::Usize => "u32".to_string(),
        IrTyRef::Bool => "bool".to_string(),
        IrTyRef::Json => "serde_json::Value".to_string(),
        IrTyRef::RefSelf => "&Self".to_string(),
        IrTyRef::Named { .. } => "serde_json::Value".to_string(),
        IrTyRef::Option { .. } => "Option<serde_json::Value>".to_string(),
        IrTyRef::Vec { .. } => "Vec<serde_json::Value>".to_string(),
        // Plan 11-02a D3(a) — Handle: napi-rs class reference (by Rust
        // struct name, which equals the TS class name for napi exports).
        IrTyRef::Handle { name } => format!("&{name}"),
    }
}

fn ts_param_ty_dts(ty: &IrTyRef) -> String {
    match ty {
        IrTyRef::Unit => "void".into(),
        IrTyRef::Str => "string".into(),
        IrTyRef::Usize => "number".into(),
        IrTyRef::Bool => "boolean".into(),
        IrTyRef::Json => "object".into(),
        IrTyRef::RefSelf => "this".into(),
        IrTyRef::Named { name } => name.clone(),
        IrTyRef::Option { inner } => format!("{} | null", ts_param_ty_dts(inner)),
        IrTyRef::Vec { inner } => format!("Array<{}>", ts_param_ty_dts(inner)),
        // Plan 11-02a D3(a) — Handle: TS class name (same as Rust struct).
        IrTyRef::Handle { name } => name.clone(),
    }
}

/// Async-context return-type spelling. Named returns serialise to
/// `serde_json::Value` (napi-rs 3.x maps that straight to `any` at the TS
/// layer; the matching .d.ts line carries the concrete type name from
/// `ts_return_ty_dts`). Lsn is the one special case — we `to_string()` it.
fn ts_async_return_ty_rust(ty: &IrTyRef) -> String {
    match ty {
        IrTyRef::Unit => "()".into(),
        IrTyRef::Named { name } if name == "Lsn" => "String".into(),
        IrTyRef::Named { .. } => "serde_json::Value".into(),
        IrTyRef::RefSelf => "Self".into(),
        _ => ts_param_ty_rust(ty).to_string(),
    }
}

/// Sync-context return-type spelling. Named returns use the TARGET napi
/// wrapper class (e.g. `Lunaris::recall() -> RetrievalBuilder` constructs
/// the TS-side `RetrievalBuilder { inner: Arc::new(...) }`). Serialising a
/// non-serde-derivable `lunaris::RetrievalBuilder` via `to_value` would
/// fail to compile — Plan 08-03 Rule 1 fix.
fn ts_sync_return_ty_rust(ty: &IrTyRef) -> String {
    match ty {
        IrTyRef::Unit => "()".into(),
        IrTyRef::Named { name } if name == "Lsn" => "String".into(),
        IrTyRef::Named { name } => name.clone(),
        IrTyRef::RefSelf => "Self".into(),
        _ => ts_param_ty_rust(ty).to_string(),
    }
}

fn ts_return_expr_rust(ty: &IrTyRef) -> String {
    match ty {
        IrTyRef::Unit => "let _ = out; Ok(())".into(),
        IrTyRef::Named { name } if name == "Lsn" => "Ok(out.to_string())".into(),
        // Async methods returning a Named serde-derivable value (ForgetReceipt)
        // serialise to JSON. The napi-rs side accepts serde_json::Value but the
        // .d.ts sees the TS class name — mirror of emit_py.rs behaviour.
        IrTyRef::Named { .. } => "Ok(serde_json::to_value(&out).map_err(napi_err)?)".into(),
        _ => "Ok(serde_json::to_value(&out).map_err(napi_err)?)".into(),
    }
}

fn ts_sync_return_expr_rust(ty: &IrTyRef) -> String {
    match ty {
        IrTyRef::Unit => "let _ = out; Ok(())".into(),
        // Plan 08-03 Rule 1 fix: sync `&self -> Named` returns wrap the
        // inner Rust value in the matching napi class rather than serialising
        // it. `Lunaris::recall() -> RetrievalBuilder` is the load-bearing
        // caller — `RetrievalBuilder` doesn't derive Serialize on the Rust
        // side, so serde_json::to_value would fail to compile.
        IrTyRef::Named { name } => {
            format!("Ok({name} {{ inner: Arc::new(out) }})")
        }
        _ => "Ok(serde_json::to_value(&out).map_err(napi_err)?)".into(),
    }
}

fn ts_return_ty_dts(ty: &IrTyRef) -> String {
    match ty {
        IrTyRef::Unit => "void".into(),
        IrTyRef::Named { name } if name == "Lsn" => "string".into(),
        IrTyRef::Named { name } => name.clone(),
        IrTyRef::RefSelf => "this".into(),
        IrTyRef::Str => "string".into(),
        IrTyRef::Usize => "number".into(),
        IrTyRef::Bool => "boolean".into(),
        IrTyRef::Json => "object".into(),
        // Plan 11-02a D3(a) — Handle: TS class name.
        IrTyRef::Handle { name } => name.clone(),
        IrTyRef::Option { inner } => format!("{} | null", ts_return_ty_dts(inner)),
        IrTyRef::Vec { inner } => format!("Array<{}>", ts_return_ty_dts(inner)),
    }
}

/// Plan 11-02a D6(b) — mirror of emit_py.rs::owned_self_target_ty. TS
/// doesn't prefix wrapper classes with `Py` — the napi-rs struct name
/// equals the TS class name equals the source Rust struct name.
fn ts_owned_self_target_ty(type_name: &str, ret_ty: &IrTyRef) -> String {
    match ret_ty {
        IrTyRef::RefSelf => type_name.to_string(),
        IrTyRef::Named { name } => name.clone(),
        _ => type_name.to_string(),
    }
}
