//! PyO3 0.26 emitter.
//!
//! Converts a [`SurfaceIR`] into a Rust source string that Plan 08-02 will
//! land at `crates/lunaris-py/src/generated.rs` (Wave 2 host crate doesn't
//! exist yet — Plan 08-01 commits the snapshot at
//! `crates/lunaris-codegen/snapshots/generated_py.rs` per revision 2).
//!
//! ## GIL discipline (CLAUDE.md)
//!
//! Every async Rust method maps to a wrapper that uses
//! `pyo3_async_runtimes::tokio::future_into_py`. The emitter places EVERY
//! `.await` inside the `future_into_py` closure — `tests/emitter_shape.rs`
//! grep-asserts the invariant (`py_emits_future_into_py`).
//!
//! ## Emission shape per type kind
//!
//! - `Opaque` → `#[pyclass(name = "...", unsendable)]` struct with
//!   `std::sync::Arc<::lunaris::Inner>`, `#[pymethods]` impl block.
//! - `Builder` → same shape, but builder-mutator methods are emitted as
//!   `#[pymethods]` that return `PyResult<Self>` (owned-self consuming).
//! - `Value` → pass-through JSON helper (not exercised in v0.1.1).
//!
//! ## Determinism
//!
//! The emitter iterates modules / types / methods in the order provided by
//! the IR. Given identical input the output is byte-identical — asserted by
//! the emit-determinism test.

use std::fmt::Write as _;

use crate::ir::{IrAsync, IrKind, IrMethod, IrParam, IrReceiver, IrTyRef, IrType, SurfaceIR};

const GENERATED_HEADER: &str = "\
// @generated by lunaris-codegen — do not edit
//
// Phase 8 Plan 08-01 (BIND-GEN-01..03). PyO3 0.26 wrapper surface emitted
// from `crates/lunaris-codegen/annotations/surface.toml`. Regenerate with
// `cargo run -p lunaris-codegen -- --emit py`.
//
// CLAUDE.md invariant: every `.await` in this file is wrapped in
// `pyo3_async_runtimes::tokio::future_into_py` — the GIL is released across
// every async boundary. The parity-check CI job
// (`.github/workflows/ci.yml::parity-check`) fails the PR on any drift from
// this snapshot.
";

/// Emit PyO3 wrapper code for the given [`SurfaceIR`].
pub fn emit_py(ir: &SurfaceIR) -> String {
    let mut out = String::new();
    out.push_str(GENERATED_HEADER);
    out.push('\n');
    out.push_str("use pyo3::prelude::*;\n");
    out.push_str("use pyo3::types::PyModule;\n");
    out.push_str("use std::sync::Arc;\n\n");

    for module in &ir.modules {
        for ty in &module.types {
            emit_py_type(&mut out, ty);
        }
        // Canonical `#[pymodule]` registration at the tail — callers load
        // this via `pyo3::append_to_inittab!` from lunaris-py's crate root.
        writeln!(
            out,
            "#[pymodule]\nfn {}(_py: Python<'_>, m: &Bound<'_, PyModule>) -> PyResult<()> {{",
            module.name
        )
        .unwrap();
        for ty in &module.types {
            writeln!(out, "    m.add_class::<Py{}>()?;", ty.name).unwrap();
        }
        writeln!(out, "    Ok(())\n}}").unwrap();
    }
    out
}

fn emit_py_type(out: &mut String, ty: &IrType) {
    if let Some(doc) = &ty.doc {
        writeln!(out, "/// {doc}").unwrap();
    }
    writeln!(
        out,
        "#[pyclass(name = \"{name}\", unsendable)]\npub struct Py{name} {{\n    #[allow(dead_code)]\n    pub(crate) inner: Arc<::lunaris::{name}>,\n}}",
        name = ty.name
    )
    .unwrap();
    out.push('\n');
    writeln!(out, "#[pymethods]\nimpl Py{name} {{", name = ty.name).unwrap();
    for m in &ty.methods {
        emit_py_method(out, &ty.name, m, ty.kind.clone());
    }
    writeln!(out, "}}\n").unwrap();
}

fn emit_py_method(out: &mut String, type_name: &str, m: &IrMethod, _kind: IrKind) {
    if let Some(doc) = &m.doc {
        writeln!(out, "    /// {doc}").unwrap();
    }
    match (m.is_async, m.receiver) {
        // Static async constructor (e.g. `Lunaris::open`).
        (IrAsync::Yes, IrReceiver::None) => {
            writeln!(out, "    #[staticmethod]").unwrap();
            writeln!(
                out,
                "    fn {name}<'py>(py: Python<'py>{params}) -> PyResult<Bound<'py, PyAny>> {{",
                name = m.name,
                params = format_params(&m.params, /* leading_comma */ true)
            )
            .unwrap();
            writeln!(out, "        pyo3_async_runtimes::tokio::future_into_py(py, async move {{")
                .unwrap();
            writeln!(
                out,
                "            let inner = ::lunaris::{type_name}::{name}({call_args}).await.map_err(py_err)?;",
                type_name = type_name,
                name = m.name,
                call_args = format_call_args(&m.params)
            )
            .unwrap();
            writeln!(out, "            Ok(Py{type_name} {{ inner: Arc::new(inner) }})").unwrap();
            writeln!(out, "        }})").unwrap();
            writeln!(out, "    }}").unwrap();
        }
        // Async instance method (e.g. `Lunaris::ingest`, `Lunaris::snapshot`,
        // `Lunaris::forget`).
        (IrAsync::Yes, IrReceiver::RefSelf) => {
            writeln!(
                out,
                "    fn {name}<'py>(&self, py: Python<'py>{params}) -> PyResult<Bound<'py, PyAny>> {{",
                name = m.name,
                params = format_params(&m.params, /* leading_comma */ true)
            )
            .unwrap();
            writeln!(out, "        let inner = self.inner.clone();").unwrap();
            writeln!(out, "        pyo3_async_runtimes::tokio::future_into_py(py, async move {{")
                .unwrap();
            writeln!(
                out,
                "            let out = inner.{name}({call_args}).await.map_err(py_err)?;",
                name = m.name,
                call_args = format_call_args(&m.params)
            )
            .unwrap();
            writeln!(out, "            {ret}", ret = py_return_expr(&m.returns.ty)).unwrap();
            writeln!(out, "        }})").unwrap();
            writeln!(out, "    }}").unwrap();
        }
        // Sync static constructor (Vector::new, Keyword::bm25, Graph::anchored).
        (IrAsync::No, IrReceiver::None) => {
            writeln!(out, "    #[staticmethod]").unwrap();
            writeln!(
                out,
                "    fn {name}({params}) -> PyResult<Self> {{",
                name = m.name,
                params = format_params(&m.params, /* leading_comma */ false)
            )
            .unwrap();
            writeln!(
                out,
                "        let inner = ::lunaris::{type_name}::{name}({call_args});",
                type_name = type_name,
                name = m.name,
                call_args = format_call_args(&m.params)
            )
            .unwrap();
            writeln!(out, "        Ok(Self {{ inner: Arc::new(inner) }})").unwrap();
            writeln!(out, "    }}").unwrap();
        }
        // Sync `&self` method (Lunaris::recall, pipeline-handle toggles).
        (IrAsync::No, IrReceiver::RefSelf) => {
            writeln!(
                out,
                "    fn {name}(&self{params}) -> PyResult<{ret}> {{",
                name = m.name,
                params = format_params(&m.params, /* leading_comma */ true),
                ret = py_sync_return_ty(&m.returns.ty, m.returns.fallible)
            )
            .unwrap();
            writeln!(
                out,
                "        let out = self.inner.{name}({call_args});",
                name = m.name,
                call_args = format_call_args(&m.params)
            )
            .unwrap();
            writeln!(out, "        {ret}", ret = py_sync_return_expr(&m.returns)).unwrap();
            writeln!(out, "    }}").unwrap();
        }
        // Sync `self`-consuming builder method (RetrievalBuilder chain).
        (IrAsync::No, IrReceiver::Owned) => {
            writeln!(
                out,
                "    fn {name}(slf: PyRefMut<'_, Self>{params}) -> PyResult<Py{type_name}> {{",
                name = m.name,
                params = format_params(&m.params, /* leading_comma */ true)
            )
            .unwrap();
            writeln!(
                out,
                "        // Builder methods consume self; we clone the inner Arc so Python can keep the prior handle alive."
            )
            .unwrap();
            writeln!(
                out,
                "        let _ = slf; let _ = ({unused}); // wired by Plan 08-02's emitter body; Plan 08-01 snapshot freezes the signature.",
                unused = format_call_args(&m.params)
            )
            .unwrap();
            writeln!(out, "        unimplemented!(\"Plan 08-02 wires the body\")").unwrap();
            writeln!(out, "    }}").unwrap();
        }
        // Unhandled shapes (MutSelf / async Owned) — defensive stub. The v0.1.1
        // 15-item surface does not exercise either.
        _ => {
            writeln!(
                out,
                "    // TODO: unsupported receiver/async combination for {}::{} — emitter stub.",
                type_name, m.name
            )
            .unwrap();
        }
    }
    out.push('\n');
}

fn format_params(params: &[IrParam], leading_comma: bool) -> String {
    let mut s = String::new();
    for (i, p) in params.iter().enumerate() {
        if leading_comma || i > 0 {
            s.push_str(", ");
        }
        s.push_str(&p.name);
        s.push_str(": ");
        s.push_str(py_param_ty(&p.ty));
    }
    s
}

fn format_call_args(params: &[IrParam]) -> String {
    params
        .iter()
        .map(|p| match &p.ty {
            IrTyRef::Str => format!("&{}", p.name),
            IrTyRef::Json => format!("pythonize::depythonize(&{})?", p.name),
            _ => p.name.clone(),
        })
        .collect::<Vec<_>>()
        .join(", ")
}

fn py_param_ty(ty: &IrTyRef) -> &'static str {
    match ty {
        IrTyRef::Unit => "()",
        IrTyRef::Str => "String",
        IrTyRef::Usize => "usize",
        IrTyRef::Bool => "bool",
        IrTyRef::Json => "&Bound<'_, PyAny>",
        IrTyRef::RefSelf => "&Self",
        IrTyRef::Named { .. } => "&Bound<'_, PyAny>",
        IrTyRef::Option { .. } => "Option<&Bound<'_, PyAny>>",
        IrTyRef::Vec { .. } => "&Bound<'_, PyAny>",
    }
}

fn py_return_expr(ty: &IrTyRef) -> String {
    match ty {
        IrTyRef::Named { name } if name == "Lsn" => {
            "Python::with_gil(|py| Ok(out.to_string().into_pyobject(py)?.into_any().unbind()))"
                .into()
        }
        IrTyRef::Unit => "Ok(Python::with_gil(|py| py.None()))".into(),
        _ => "Python::with_gil(|py| Ok(pythonize::pythonize(py, &out)?.unbind()))".into(),
    }
}

fn py_sync_return_ty(ty: &IrTyRef, _fallible: bool) -> String {
    // Both fallible and infallible sync methods wrap in `PyResult<T>` at the
    // outer signature layer; the caller formats the `PyResult<...>` around
    // this return so here we only produce the inner type name. The
    // `_fallible` argument is preserved in the signature for future
    // differentiation (e.g. if we want to drop the `PyResult` wrapper on
    // trivially infallible toggles) without churning every caller.
    match ty {
        IrTyRef::Unit => "()".into(),
        IrTyRef::RefSelf => "Self".into(),
        IrTyRef::Named { name } => format!("Py{name}"),
        other => format!("<{other:?}>"),
    }
}

fn py_sync_return_expr(r: &crate::ir::IrReturn) -> String {
    match (&r.ty, r.fallible) {
        (IrTyRef::Unit, _) => "let _ = out; Ok(())".into(),
        (IrTyRef::RefSelf, _) | (IrTyRef::Named { .. }, false) => {
            "Ok(Self { inner: Arc::new(out) })".into()
        }
        _ => "Ok(out)".into(),
    }
}
