// Emit the TypeScript SDK's embedding matrix for the fixed parity corpus.
//
// Driven by `run_sdk_embedder_parity.rs`. Mirrors py_matrix.py, including the
// exit codes: 3 = binding built without `bindings-it`, 4 = no embedder model.
// The driver classifies; this script never decides to skip.
//
// Resolution order matters. `index.mjs` is a HAND-WRITTEN ESM shim with an
// explicit export list; `index.js` is regenerated by `napi build` from the
// actual binding. A `bindings-it` hook lands in the generated surface and the
// raw `.node`, but nobody adds it to the shim — so probing the shim reports
// "missing" against a binding that has it, and the driver turns that into a
// skip. Fall through to the `.node` itself and say on stderr which surface
// answered, so exit 3 keeps meaning "genuinely built without the feature".
import fs from "node:fs";
import path from "node:path";
import { createRequire } from "node:module";

const [, , bindingPath, inputsPath, outPath] = process.argv;
const require = createRequire(import.meta.url);

// Both hooks, not one: the gate and the .node fallback must key on the
// SAME symbols the probe actually calls, or the fallback can accept a
// binding the gate then rejects.
const has = (m) =>
  typeof m?.embedderConfigFromEnv === "function" &&
  typeof m?.embedderConfigEmbedBatch === "function";

function unwrap(m) {
  return m && typeof m === "object" && "default" in m && !("EmbedderConfig" in m) ? m.default : m;
}

const bindingDir = path.dirname(path.resolve(bindingPath));
const nodeFile = fs.existsSync(bindingDir)
  ? fs.readdirSync(bindingDir).find((f) => f.endsWith(".node"))
  : undefined;

let l;
try {
  l = unwrap(await import(path.resolve(bindingPath)));
} catch (err) {
  // `index.js` is COMMITTED, so it is present even in jobs that never run
  // `napi build` — and napi's loader throws when the native binding beside it
  // is absent. That is "no bindings available", the same condition exit 3
  // already means, but it surfaced as an unhandled rejection: exit 1, which the
  // driver refuses to treat as a skip. (`feature-build smoke (no backend)` runs
  // this driver with no SDK build at all.)
  //
  // Narrow on purpose: only a MISSING `.node` is a skip. If one is present and
  // still fails to load, that is a real defect and must keep failing loudly.
  if (nodeFile) throw err;
  process.stderr.write(`BINDING-NOT-BUILT: ${err?.message ?? err}\n`);
  process.exit(3);
}
let via = bindingPath;

if (!has(l)) {
  // The entry we were handed is a shim that does not re-export the hook. Ask
  // the binding itself before concluding the feature is absent.
  const dir = bindingDir;
  const node = nodeFile;
  if (node) {
    const raw = require(path.join(dir, node));
    if (has(raw)) {
      process.stderr.write(
        `NOTE: ${bindingPath} does not re-export the bindings-it hooks; ` +
          `resolved it from ${node} instead.\n`,
      );
      l = raw;
      via = node;
    }
  }
}

if (!has(l)) {
  process.stderr.write("BINDING-LACKS-BINDINGS-IT\n");
  process.exit(3);
}

const inputs = JSON.parse(fs.readFileSync(inputsPath, "utf8"));
let cfg;
try {
  cfg = await l.embedderConfigFromEnv();
} catch (err) {
  process.stderr.write(`NO-EMBEDDER: ${err?.message ?? err}\n`);
  process.exit(4);
}

const matrix = await l.embedderConfigEmbedBatch(cfg, inputs);
if (!matrix.some((row) => row.some((v) => v !== 0))) {
  // `resolve_default_embedder` warns and returns NoopEmbedder rather than
  // failing, and two Noops agree perfectly — so this is a skip, not a pass.
  process.stderr.write("NO-EMBEDDER: resolved to NoopEmbedder (all-zero vectors)\n");
  process.exit(4);
}
fs.writeFileSync(outPath, JSON.stringify(matrix));
process.stdout.write(`TS-MATRIX-OK ${matrix.length} ${matrix[0]?.length ?? 0} via=${via}\n`);
